### ISSUE TITLE
.prettierrc file not affect on rules

### ISSUE THREAD

**Issue by OriAmir** [prettier/eslint-plugin-prettier#103]
Hi,I write project using create-react-app and want to integrate prettier with eslint .

 My **package.json** contain :
`"eslint-config-prettier": "^2.9.0",
    "eslint-plugin-prettier": "^2.6.2",
     "prettier": "^1.13.7", "pretty-quick": "^1.6.0"`

**.eslintrc** file contain:
`{
  "extends": ["react-app", "plugin:prettier/recommended"],
}
`

Now i have error that annoyed me and i want to cancel him:
_[eslint] Replace `'../Admin.module.css'` with `"../Admin.module.css"` (prettier/prettier)_

So , I try to add **.prettierrc**  file to my project and to add him this json:
`{
  "avoidEscape": true
}`

and also try to set this:
`{
singleQuote: true
}`

But nothing happened! I try to add also another rules but also nothing happened ..it's looks like this file not affect anything and it's stay the same
What I am doing wrong?

Thanks!

**Comment by not-an-aardvark** [comment]
Hi,

Try using the `singleQuote: true` option in your `.prettierrc` file. I don't think prettier has an `avoidEscape` option.

**Comment by OriAmir** [comment]
@not-an-aardvark 
Hi, thank for your quick replay.
I try to put this line also but nothing happend , same error.
Maybe my . prettierrc has not have any effect on rules ? i could i know this?

tnx!

**Comment by not-an-aardvark** [comment]
What version of `prettier` are you using?

**Comment by OriAmir** [comment]
`    "prettier": "^1.13.7",
    "pretty-quick": "^1.6.0"`

@not-an-aardvark

**Comment by texastoland** [comment]
👍🏽 My symptom one is ESLint claims Prettier wants single quotes but it's but the default is not overridden in my `.prettierrc.yaml`.

**Comment by texastoland** [comment]
I logged the `context` getting passed in and tracked my issue to `plugin:shopify/typescript-prettier`.

**Comment by jorgegonzalez** [comment]
@beardedpayton @OriAmir Which rules specifically are not being applied?

**Comment by jorgegonzalez** [comment]
I was having this issue where a `.prettierrc` was not changing any rules and it was because a `.editorconfig` in the same directory was overriding them. Specifically the `quote_type` and `indent_size` settings.

**Comment by pmithunish** [comment]
Using the following setup
```
{
  "extends": ["react-app", "prettier"],
  "rules": {
    "prettier/prettier": "error"
  },
  "plugins": ["prettier"]
}
```
instead of the shorthand `{ extends: ["react-app", "plugin:prettier/recommended"] }` did the trick for me.
Read more about this [here](https://prettier.io/docs/en/eslint.html).
Hope it helps 😃.

**Comment by xuchaobei** [comment]
I also meet the issue. After a long time research, I think the eslint plugin of vscode casue the issue. Only changing rules in .prettier.js , the eslint server plugged in  vsocde doesn't reload the updated rules. But if you run eslint through terminal, you will find the new rules are applied. 

One solution is to reopen the vscode, then eslint server will restart and load the new  rules in .prettier.js.

**Comment by mimafogeus2** [comment]
Just had the same problem, and solved it.
Apparently, there was a `"prettier"` definition inside the project's `package.json` file. When I removed it, my custom `.prettierrc` settings were finally taken into account.

**Comment by robertsLando** [comment]
Just go to vs-code actions and select `ESLINT: Restart ESLint Server`

**Comment by penance316** [comment]
> Just go to vs-code actions and select `ESLINT: Restart ESLint Server`

I have been having the same issue in PHPstorm recently, it can be solved by a simple restart of the IDE to refresh the ESLint server just the same as for VSCode.

Thanks fo the tip

**Comment by PabloRosales** [comment]
> "prettier/prettier": "error"

I'm using IDEA IntelliJ and a restart was also needed.

**Comment by PabloRosales** [comment]
> I also meet the issue. After a period of trial, I think the eslint plugin of vscode casue the issue. When changing rules in .prettier.js , the eslint server plugged in vsocde doesn't reload the updated rules. But if you run eslint through terminal, you will find the new rules are applied.
> 
> One solution is to reopen the vscode, then eslint server will restart and load the new rules in .prettier.js.

I'm using IDEA IntelliJ and a restart was also needed.

**Comment by DaviidMM** [comment]
> Just go to vs-code actions and select `ESLINT: Restart ESLint Server`

This did the trick for me. Thanks!
