### ISSUE TITLE
eslint failure when i use plugins prettier

### ISSUE THREAD

**Issue by ufoqhmdt** [prettier/eslint-plugin-prettier#109]
**What version of `eslint` are you using?**
5.5

**What version of `prettier` are you using?**
1.14.2

**What version of `eslint-plugin-prettier` are you using?**
2.6.2

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```
{
  "plugins": [
    "react",
    "standard",
    "prettier"
  ],
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "commonjs": true,
    "node": true,
    "es6": true,
    "amd": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier",
    "prettier/react",
    "prettier/standard"
  ],
  "parserOptions": {
    "ecmaVersion": 9,
    "sourceType": "module",
    "ecmaFeatures": {
      "esversion": 9,
      "destructuring": true,
      "generators": true,
      "superInFunctions": true,
      "experimentalObjectRestSpread": true,
      "jsx": true
    }
  },
  "rules": {
    "prettier/prettier": ["error", "fb"],
    "no-console": "warn",
    "linebreak-style": [
      "error",
      "unix"
    ],
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "semi": [
      "error",
      "always"
    ],
    "react/jsx-uses-react": "error",
    "react/jsx-uses-vars": "error",
    "quotes": [
      "error",
      "single",
      {
        "allowTemplateLiterals": true
      }
    ],

    "space-before-function-paren": [
      "off",
      {
        "anonymous": "always",
        "named": "always"
      }
    ]
  }

}
```

**What source code are you linting?**

```
@observer
class AsyncTree extends React.Component {
  renderTreeNodes = data => {
    return data.map(item => {
      if (item.children) {
        return (
          <TreeNode
            title={item.title}
            key={item.key}
            disableCheckbox={item.disableCheckbox}
            dataRef={item}
            className={classNames(
              'auto-tree-node',
              `auto-tree-node-${item.nodeIconType}`,
            )}
          >
            {this.renderTreeNodes(item.children)}
          </TreeNode>
        );
      }
      return (
        <TreeNode
          {...item}
          dataRef={item}
          className={classNames(
            'auto-tree-node',
            `auto-tree-node-${item.nodeIconType}`,
          )}
        />
      );
    });
  };
  render() {
```

**What did you expect to happen?**
can be working!

**What actually happened?**
![image](https://user-images.githubusercontent.com/1751382/45261075-57892800-b42b-11e8-8830-d5c850af6bec.png)

**Comment by ufoqhmdt** [comment]
`import React from 'react';
import { Tree } from 'antd';
import { observer } from 'mobx-react';
import classNames from 'classnames';
import './index.css';

const TreeNode = Tree.TreeNode;

@observer
class AsyncTree extends React.Component {
  renderTreeNodes = data => {
    return data.map(item => {
      if (item.children) {
        return (
          <TreeNode
            title={item.title}
            key={item.key}
            disableCheckbox={item.disableCheckbox}
            dataRef={item}
            className={classNames(
              'auto-tree-node',
              `auto-tree-node-${item.nodeIconType}`,
            )}
          >
            {this.renderTreeNodes(item.children)}
          </TreeNode>
        );
      }
      return (
        <TreeNode
          {...item}
          dataRef={item}
          className={classNames(
            'auto-tree-node',
            `auto-tree-node-${item.nodeIconType}`,
          )}
        />
      );
    });
  };
  render() {
    const { store } = this.props;
    return (
      <Tree
        checkable={store.checkable}
        checkStrictly={store.checkStrictly}
        multiple={store.multiple}
        showIcon
        onCheck={(keys, eventObj) => {
          store.onCheckNode(keys, eventObj);
        }}
        defaultExpandedKeys={store.defaultExpandedKeys}
        checkedKeys={store.stateCheckedKeys}
      >
        {this.renderTreeNodes(store.treeData)}
      </Tree>
    );
  }
}

export default AsyncTree;
`

**Comment by ufoqhmdt** [comment]
> `import React from 'react';
import { Tree } from 'antd';
import { observer } from 'mobx-react';
import classNames from 'classnames';
import './index.css';

const TreeNode = Tree.TreeNode;

@observer
class AsyncTree extends React.Component {
  renderTreeNodes = data => {
    return data.map(item => {
      if (item.children) {
        return (
          <TreeNode
            title={item.title}
            key={item.key}
            disableCheckbox={item.disableCheckbox}
            dataRef={item}
            className={classNames(
              'auto-tree-node',
              `auto-tree-node-${item.nodeIconType}`,
            )}
          >
            {this.renderTreeNodes(item.children)}
          </TreeNode>
        );
      }
      return (
        <TreeNode
          {...item}
          dataRef={item}
          className={classNames(
            'auto-tree-node',
            `auto-tree-node-${item.nodeIconType}`,
          )}
        />
      );
    });
  };
  render() {
    const { store } = this.props;
    return (
      <Tree
        checkable={store.checkable}
        checkStrictly={store.checkStrictly}
        multiple={store.multiple}
        showIcon
        onCheck={(keys, eventObj) => {
          store.onCheckNode(keys, eventObj);
        }}
        defaultExpandedKeys={store.defaultExpandedKeys}
        checkedKeys={store.stateCheckedKeys}
      >
        {this.renderTreeNodes(store.treeData)}
      </Tree>
    );
  }
}

export default AsyncTree;
`

**Comment by ufoqhmdt** [comment]
sorry, github can not be prettier my code。 it looks like bad。

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. Could you paste the full output of ESLint, instead of a screenshot? That will make it easier to tell what's going on.

**Comment by ufoqhmdt** [comment]
` ✘ didi@MacBook-Pro-2  ~/workspaces/sh-fe/auto/afe-auto-prime-web   feature_financial_plan ●✚  npx eslint src --fix
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.
Unexpected token @ (9:1)
   7 | const TreeNode = Tree.TreeNode;
   8 |
>  9 | @observer
     | ^
  10 | class AsyncTree extends React.Component {
  11 |   renderTreeNodes = data => {
  12 |     return data.map(item => {`

**Comment by ufoqhmdt** [comment]
![image](https://user-images.githubusercontent.com/1751382/45261231-5dcdd300-b430-11e8-8d07-c12cb96d547d.png)
That makes it a little bit clearer

**Comment by anjaleec** [comment]
The eslint-prettier plugin is not working for me, too. It worked on a small piece of code during trials (10 .js files - nodejs) but now when I apply it to a larger project - it stops running. Just stops giving any output.

Here are the versions of the packages I installed (directly pasting from package.json):
eslint: ^5.16.0,
eslint-config-prettier: ^4.1.0,
eslint-plugin-prettier": ^3.0.1,
prettier": 1.17.0

Contents of ".prettierrc.json": 

{
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": true,
    "singleQuote": true,
    "bracketSpacing": true
}

Contents of ".eslintrc.json" :

{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "prettier"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "plugins": [
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error",
        "no-console": [
            "warn"
        ],
        "no-undef": [
            "warn"
        ],
        "camelcase": [
            "error",
            {
                "properties": "always"
            }
        ],
        "semi": [
            "error",
            "always"
        ],
        "quotes": [
            "warn",
            "single"
        ],
        "no-extra-semi": [
            "warn"
        ]
    }
}

I've tried all permutations & combinations (removing from plugins, removing from extends), yet it isn't working.

Can this issue be sorted by any means?

**Comment by rafalskyi** [comment]
same problem on mac

**Comment by marcosguti** [comment]
Hi, i'm not sure if is related with this but i'm having this problem 
![capture](https://user-images.githubusercontent.com/18442798/70672273-06cb3500-1c55-11ea-8f8c-563b82e73710.png) i can't see any warning and suggestions to fix problems, can help me with that? 

this is my package.json 
```
 "devDependencies": {
    "@babel/cli": "^7.6.2",
    "@babel/core": "^7.6.2",
    "@babel/node": "^7.6.2",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-export-namespace-from": "^7.5.2",
    "@babel/plugin-proposal-function-sent": "^7.5.0",
    "@babel/plugin-proposal-json-strings": "^7.2.0",
    "@babel/plugin-proposal-numeric-separator": "^7.2.0",
    "@babel/plugin-proposal-throw-expressions": "^7.2.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-syntax-import-meta": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.2",
    "@babel/register": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "babel-eslint": "^10.0.3",
    "chalk": "^2.4.2",
    "core-js": "^3.2.1",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.3.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "jest": "^24.9.0",
    "jest-cli": "^24.9.0",
    "lodash": "^4.17.15",
    "minimist": "^1.2.0",
    "node-random-name": "^1.0.1",
    "nodemon": "^1.19.3",
    "prettier": "1.19.1",
    "regenerator-runtime": "^0.13.3",
    "rethinkdbdash": "^2.3.31"
  },

```
and eslintrc.json

```{
  "env": {
    "es6": true,
    "node": true
  },
  "extends": ["standard", "prettier", "plugin:prettier/recommended"],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "semi": false,
        "jsxSingleQuote": true
      }
    ]
  }
}
 ```

**Comment by JounQin** [comment]
This issue seems stale, feel free to create a new one with reproduction, thanks.
