### ISSUE TITLE
Documentation: Recommendation of using prettier-eslint

### ISSUE THREAD

**Issue by thernstig** [prettier/eslint-plugin-prettier#127]
https://github.com/prettier/eslint-plugin-prettier#recommended-configuration has this recommendation:

> If your desired formatting does not match the `prettier` output, you should use a different tool such as [prettier-eslint](https://github.com/prettier/prettier-eslint) instead.

At the same time, the recommendation says:

```json
{
  "extends": ["plugin:prettier/recommended"]
}
```

The purpose of prettier-eslint is to run `prettier`, followed by `eslint --fix`. If one has set the above configuration (`"extends": ["plugin:prettier/recommended"]`), then prettier will already be run with `eslint --fix`. I am thus wondering if it is correct to recommend to use prettier-eslint together with that configuration? In practice what will happen then is:
1. `prettier` is run.
2. `eslint --fix` is run.
 a. `eslint --fix` runs the the prettier plugin and the rule called prettier, which again formats according in the same way as 1.

Should the documentation be updated to remove the sentence about prettier-eslint?

**Comment by not-an-aardvark** [comment]
To clarify, the recommendation is to use `prettier-eslint` as an alternative to `eslint-plugin-prettier` if your desired formatting does not match the `prettier `output. I wouldn't suggest using both `prettier-eslint` and `eslint-plugin-prettier` at the same time.

**Comment by thernstig** [comment]
@not-an-aardvark Thank you for the clarification. That makes more sense. Maybe it could be clarified in someway, I am uncertain how.

Another confusion that stems from this is the VS Code extension for Prettier. This section https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration reads:

> `prettier-eslint` and `prettier-tslint` are included with the installation of this extension. There is no need for a separate local or global install of either for functionality.

That section specifically talks about integrating Prettier with VS Code with the recommendation of using prettier-eslint.

Further down the chapter [VSCode Specific Settings](https://github.com/prettier/prettier-vscode#vscode-specific-settings) reads:

> Use prettier-eslint instead of prettier. Other settings will only be fallbacks in case they could not be inferred from ESLint rules

I understand this is another repository than this one, but it belongs to the same user https://github.com/prettier

Considering https://prettier.io/docs/en/eslint.html says to use `"extends": ["plugin:prettier/recommended"]` it gets mildly confusing.

Would you recon the VS Code extension for Prettier is doing something wrong here? Using the supplied instructions there would get you exactly into the scenario I describe in the original post.

**Comment by JounQin** [comment]
@thernstig 

`eslintIntegration` is used for `prettier-eslint` rather than `eslint-plugin-prettier`. And it seems this option has been removed.

https://github.com/prettier/prettier-vscode/search?q=eslintIntegration

**Comment by thernstig** [comment]
@JounQin yes this is quite outdated now, the recommendations overall for Prettier for integrations has changed since this was posted: https://prettier.io/docs/en/integrating-with-linters.html

I am closing this.
