### ISSUE TITLE
eslint-plugin-prettier not handling syntax errors gracefully

### ISSUE THREAD

**Issue by siric1** [prettier/eslint-plugin-prettier#140]
eslint 5.11.0
prettier 1.15.3
eslint-plugin-prettier 3.0.0
eslint-config-prettier 3.3.0
vscode 1.30.1

```
  "extends": [
    "airbnb-base",
    "plugin:vue/recommended",
    "plugin:prettier/recommended",
    "prettier/vue"
  ]
```

```
<template>
  <div>
</template>
```

<img width="467" alt="eslint-toast" src="https://user-images.githubusercontent.com/31568598/50481491-1751b380-09e2-11e9-9fa1-320f126f52b5.png">

vscode keeps throwing these notifications. 
https://github.com/Microsoft/vscode-eslint/issues/587
https://github.com/Microsoft/vscode-eslint/issues/593

**Comment by BPScott** [comment]
Thanks for the bug report!
