### ISSUE TITLE
Conflict with eslint-plugin-vue

### ISSUE THREAD

**Issue by blowsie** [prettier/eslint-plugin-prettier#167]
**What version of `eslint` are you using?** ^5.14.1

**What version of `prettier` are you using?** 1.16.4

**What version of `eslint-plugin-prettier` are you using?** 3.0.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: ['@nuxtjs', 'plugin:vue/recommended', 'plugin:prettier/recommended'],
  plugins: ['prettier', 'vue'],
  // add your custom rules here
  rules: {}
}
```

**What source code are you linting?**
Both of these will show cause eslint to error when using 
 'plugin:prettier/recommended' and  'plugin:vue/recommended'

```<img src="one.jpg" />```
```<img src="one.jpg">```

![image](https://user-images.githubusercontent.com/308572/53407278-b3347700-39b3-11e9-9c82-039f885a9455.png)
![image](https://user-images.githubusercontent.com/308572/53407291-bf203900-39b3-11e9-98bc-f42ae8c81b95.png)

**What did you expect to happen?**
To be able to format an image without error

**What actually happened?**
Impossible to format image without error.

--- 
Its worth noting that this conflict on appears on certain versions (current latest included)

A snippet of my versions from `package.json`
```
    "eslint": "^5.14.1",
    "eslint-config-prettier": "^4.0.0",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-prettier": "3.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
```

**Comment by blowsie** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/832

**Comment by j-f1** [comment]
Try extending `prettier/vue` too.

**Comment by aldarund** [comment]
@j-f1 extending prettier/vue doesnt help

**Comment by j-f1** [comment]
Make sure you put all the Prettier `extends` at the end of the list.

**Comment by aldarund** [comment]
ye, it was the end. But it wasnt working for some reason and then started to work. Some weird cache issue.

**Comment by mittalyashu** [comment]
@j-f1 Something like this?

```js
extends: [
	"eslint:recommended",
	"plugin:vue/recommended",
	"plugin:prettier/recommended"
]
```

**Comment by CMCDragonkai** [comment]
I'm using vue3, this doesn't work. There's lots of rules that are conflicting between `plugin:vue/vue3-recommended` and `plugin:prettier/recommended`. And using `prettier` or `prettier/vue` from `eslint-config-prettier` doesn't help.

**Comment by Sovai** [comment]
> I'm using vue3, this doesn't work. There's lots of rules that are conflicting between `plugin:vue/vue3-recommended` and `plugin:prettier/recommended`. And using `prettier` or `prettier/vue` from `eslint-config-prettier` doesn't help.

try this
`    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:prettier/recommended',
    'prettier/vue',`
![image](https://user-images.githubusercontent.com/8064796/140893919-2cd78c47-f515-43d6-9fbc-298cb4bfc115.png)
