### ISSUE TITLE
Incorrect formatting of <template> tag

### ISSUE THREAD

**Issue by jtsom** [prettier/eslint-plugin-prettier#169]
**What version of `eslint` are you using?**
^5.15.1
**What version of `prettier` are you using?**
<img width="294" alt="image" src="https://user-images.githubusercontent.com/13488/53578569-e9096500-3b45-11e9-809b-eae55633f3c7.png">

**What version of `eslint-plugin-prettier` are you using?**
<img width="274" alt="image" src="https://user-images.githubusercontent.com/13488/53578611-f6265400-3b45-11e9-8f56-24753ad33eee.png">

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**Please show your full configuration:**

```
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: ['plugin:vue/essential', '@vue/prettier'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    singleQuote: true,
    'prettier/prettier': [
      'warn',
      {
        singleQuote: true,
        semi: true,
        trailingComma: 'es5',
        printWidth: 140,
        jsxBracketSameLine: true,
      },
    ],
  },
  parserOptions: {
    parser: 'babel-eslint',
  },
};
```

**What did you do?**	

```vue
<template v-slot:header>Word Bank</template>
```

**What did you expect to happen?**
VS Code shows a linting error:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/13488/53571819-ca9c6d00-3b37-11e9-9565-60e741499729.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/13488/53571804-c07a6e80-3b37-11e9-8fcf-832a3751dff5.png">

Fixing the error should format as:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/13488/53571874-ec95ef80-3b37-11e9-8f24-815dab24a7d8.png">

**What actually happened?**

Formats as:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/13488/53571905-fd466580-3b37-11e9-9247-5016a8af9ed4.png">

**Comment by j-f1** [comment]
This is intentional behavior. See our explanation here: https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting
