### ISSUE TITLE
line-by-line error reporting

### ISSUE THREAD

**Issue by vjeux** [prettier/eslint-plugin-prettier#17]
Hey @not-an-aardvark, thanks a ton for working on this plugin, this turned out to be the way most people are integrating prettier inside of their stack :)

We've been working on a different implementation at Facebook. At first we started it to support annotating files with `@format` (like `@flow`) and only running the lint rule on them, for a migration path.

In the process, we added a super nice feature where instead of reporting a single eslint message at the top of the file, we diff the file and the prettier output and give suggestions for each line that needs to be changed. When you have an editor integration, it shows it inline like any other lint rule, which is really nice.

https://github.com/zertosh/eslint-plugin-prettify

I was wondering if we could figure out a way to get those two projects to converge, so that people using prettier have the best possible integration :)

Thanks!

**Comment by zertosh** [comment]
This is a huge ask, but maybe @not-an-aardvark is open to moving `eslint-plugin-prettier` to the Prettier org - then I could deprecate `eslint-plugin-prettify` and move over the code to `eslint-plugin-prettier`.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the issue.

> In the process, we added a super nice feature where instead of reporting a single eslint message at the top of the file, we diff the file and the prettier output and give suggestions for each line that needs to be changed. When you have an editor integration, it shows it inline like any other lint rule, which is really nice.

Seems useful! This is similar to what I had in mind for https://github.com/not-an-aardvark/eslint-plugin-prettier/issues/7, but I never ended up implementing it.

> This is a huge ask, but maybe @not-an-aardvark is open to moving `eslint-plugin-prettier` to the Prettier org - then I could deprecate `eslint-plugin-prettify` and move over the code to `eslint-plugin-prettier`.

Sure, that sounds good to me. I haven't had much time to maintain this recently, so if other people want to make improvements/help maintain the plugin, that would be a win-win situation.

**Comment by not-an-aardvark** [comment]
I just accepted the invitation to the prettier org -- should I go ahead and transfer the repo?

**Comment by vjeux** [comment]
Yup, should be good to go!

**Comment by not-an-aardvark** [comment]
Done.

**Comment by vjeux** [comment]
Woot woot!

**Comment by vjeux** [comment]
@zertosh is splitting the work he has done on his repo into distinct pull requests that he will send here. If you are happy with them, then we can start merge them :)

It has a compatible API, so it shouldn't disrupt existing users, they are just going to get a better experience out of the box and will be able to use more options :)
