### ISSUE TITLE
README: simplify instructions to integrate eslint-config-prettier

### ISSUE THREAD

**Issue by lunelson** [prettier/eslint-plugin-prettier#180]
I suggest you remove and deprecate the `plugin:prettier/recommended` config. It is well-intended but it obscures more than it helps. The `eslint-plugin-prettier` README says to do the following:

```json
{
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error"
  }
}
```
...and then says in order to integrate `eslint-config-prettier` you install it and then ADD the following:

```json
{
  "extends": ["plugin:prettier/recommended"]
}
```

But that single line actually replaces the previous configurations, because it's equivalent to this:

```json
{
  "extends": ["prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error"
  }
}
```
...which is stated, but not easily understood because the user is told to ADD the `plugin:prettier/recommended` line, not to REPLACE the previous config with it. 

IMO what would be simpler, easier to follow and easier to understand for anyone reading an `.eslintrc` file, is to tell the user to install `eslint-config-prettier` and add the following line to the configuration they've already written:

```json
{
  "extends": ["prettier"]
}
```
...which incidentally has the benefit of also agreeing with the README of the `eslint-config-prettier` package, which is important because many use-cases will require further exclusions and require consulting that README as well.

I think a plugin exporting a config which re-adds that same plugin (rather than adding a ruleset) is an anti-pattern. If it added a complex list of obscure dependencies in a specific order it might be worthwhile but here the full explicit config is actually easier to read and understand

**Comment by lunelson** [comment]
The 'recommended' config is only saving four lines, and it doesn't match the instructions at `eslint-config-prettier` which just makes it confusing. The full config OTOH conforms to eslint convention, which also makes it easier to understand to anyone opening a new project and reading the `.eslintrc` file. I think at least the README here should be adjusted to explain this better.

**Comment by anchnk** [comment]
I agree with @lunelson, each time I have to set up and configure a new project I do find the instructions quite confusing and, at worst, misleading. IMO it's not crystal clear and can lead to bad configurations. Either removing the recommended configuration either improving the current explanations can solve this.

**Comment by sshmyg** [comment]
Good explanation about differences between plugin and config https://stackoverflow.com/questions/44690308/whats-the-difference-between-prettier-eslint-eslint-plugin-prettier-and-eslint

**Comment by sveyret** [comment]
I agree with @lunelson because it may also create an issue. Indeed, _eslint_ resolves the configuration relative to the configuration file requiring it, which here is `eslint-plugin-prettier` configuration. But `eslint-config-prettier` is not a direct dependency of `eslint-plugin-prettier`, and therefore, depending on the package manager you are using (try with `pnpm` for example), the `eslint-config-prettier` will not be found.

**Comment by ranisalt** [comment]
> But `eslint-config-prettier` is not a direct dependency of `eslint-plugin-prettier`, and therefore, depending on the package manager you are using (try with `pnpm` for example), the `eslint-config-prettier` will not be found.

It is though, if you don't install `eslint-config-prettier` manually you will see:

```
Oops! Something went wrong! :(
ESLint: 7.26.0
ESLint couldn't find the config "prettier" to extend from. Please check that the name of the config is correct.
The config "prettier" was referenced from the config file in "/builds/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js".
If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```

Using the "recommended" config

**Comment by JounQin** [comment]
`eslint-config-prettier` disables conflict rules with `prettier`, `eslint-plugin-prettier` runs `prettier` in ESLint, they are totally different.
