### ISSUE TITLE
Can't make usePrettierrc work under recommended config

### ISSUE THREAD

**Issue by maxiR8** [prettier/eslint-plugin-prettier#184]
**What version of `eslint` are you using?**
eslint: "5.16.0

**What version of `prettier` are you using?**
prettier: 1.17.0

**What version of `eslint-plugin-prettier` are you using?**
eslint-plugin-prettier: 3.0.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
//.eslintrc
{
    "root": true,
    "env": {
        "browser": true,
        "es6": true,
        "commonjs": true,
        "jquery": true
    },
    "extends": ["plugin:prettier/recommended"],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "babel-eslint",
    "rules": {
        "prettier/prettier": [
            "error",
            {},
            {
                "usePrettierrc": true
            }
        ]
    }
}
```
```
//.prettierrc.json

{
    "singleQuote": true,
    "trailingComma": "all",
    "semi": true,
    "tabWidth": 2
}
```

**What source code are you linting?**
Believe doesn't matter, any js code.

**What did you expect to happen?**
I am trying to setup eslint and prettier to work together under the same rules. I followed the instructions in README for Option 2 in using the usePrettierc, however, it works inconsistently when using the recommended config("extends": ["plugin:prettier/recommended"],). Expected proposed Option 2 in README (with usePrettierrc option) to work same as option 1.

**What actually happened?**
It doesn't follow the prettierrc options, or eslint complains that prettier formatted incorrectly (Ie regarding indentation.). This happens when using "extends": ["plugin:prettier/recommended"]. If I don't use the recommended config it works correctly.  I am using vscode prettier extension with "prettier.eslintIntegration": true. Maybe this is the cause.

Sorry If the mistake is on my end, a bit new to this.

**Comment by BPScott** [comment]
`usePrettierrc: true` is the default behaviour, you don't need to opt into this explicitly.

Did you also install `eslint-config-prettier` per the 1st part of the recommended configuration? If you've installed `eslint-config-prettier` and `eslint-plugin-prettier` then the following should work:

```
{
    "root": true,
    "env": {
        "browser": true,
        "es6": true,
        "commonjs": true,
        "jquery": true
    },
    "extends": ["plugin:prettier/recommended"],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "babel-eslint"
}
```

**Comment by maxiR8** [comment]
Hello Ben, thank you for the prompt reply.

Yes I have both `eslint-config-prettier` (4.1.0) and `eslint-plugin-prettier` installed.

The config that you suggested, I tried, it doesn't work for me.

I currently went with the config below. It is working, however, judging by the output from `eslint --print-config` it is the same thing if I am not mistaken. So I am not sure why one works and the suggested doesn't.

```
{
    "root": true,
    "env": {
        "browser": true,
        "es6": true,
        "commonjs": true,
        "jquery": true
    },
    "extends": ["airbnb-base", "prettier"],
    "plugins": ["prettier"],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "babel-eslint",
    "rules": {
        "prettier/prettier": "error"
    }
}
```

**Comment by Raju** [comment]
> Hello Ben, thank you for the prompt reply.
> 
> Yes I have both `eslint-config-prettier` (4.1.0) and `eslint-plugin-prettier` installed.
> 
> The config that you suggested, I tried, it doesn't work for me.
> 
> I currently went with the config below. It is working, however, judging by the output from `eslint --print-config` it is the same thing if I am not mistaken. So I am not sure why one works and the suggested doesn't.
> 
> ```
> {
>     "root": true,
>     "env": {
>         "browser": true,
>         "es6": true,
>         "commonjs": true,
>         "jquery": true
>     },
>     "extends": ["airbnb-base", "prettier"],
>     "plugins": ["prettier"],
>     "globals": {
>         "Atomics": "readonly",
>         "SharedArrayBuffer": "readonly"
>     },
>     "parser": "babel-eslint",
>     "rules": {
>         "prettier/prettier": "error"
>     }
> }
> ```

Well to see the changes you have to restart Eslint and then it works. 

I tried both and both are working fine but any changes to `.prettierrc` file for it to reflect we need to `restart eslint server`.
