### ISSUE TITLE
inter] Error running ESLint Error: require(...).getLocationFromRangeIndex is not a function(…)

### ISSUE THREAD

**Issue by christianalfoni** [prettier/eslint-plugin-prettier#19]
Hi there!

I have installed this plugin as instructed on the repo. I am using latest version of Atom with latest version of linter-eslint, and also latest eslint installed to my project. Also latest prettier.

For some reason when I save I get the error in the title of this issue. Not sure where to start here :) The error goes away when I remove the prettier rule from the rules map.

**Comment by not-an-aardvark** [comment]
Thanks for the report. This also occurred in https://github.com/prettier/eslint-plugin-prettier/issues/11, although I don't think we ever figured out why. It seems like restarting Atom fixed the issue in https://github.com/prettier/eslint-plugin-prettier/issues/11.

**Comment by christianalfoni** [comment]
Hi and thanks for the answer :-)

What I notice is that this only happens when I have React code in my file. I have tried to restart and it did not help. Hm hm...

This is my config file:

```js
module.exports = {
  "parserOptions": {
    "ecmaVersion": 2016,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "node": true
  },
  plugins: [
      "prettier",
      "react"
  ],
  extends: [
    "plugin:react/recommended",
    "prettier",
    "prettier/react"
  ],
  rules: {
    "prettier/prettier": "error"
  }
};
```

**Comment by christianalfoni** [comment]
Okay, I figured it out:

It was my global eslint messing it up. Made sure the "Use global eslint" config at the bottom of the linter-eslint plugin for Atom was turned off and installed eslint and eslint-plugin-react again to my local project.

**Comment by iameli** [comment]
I got the same error in VS Code, with a similar workaround -- I had `eslint-plugin-prettier` installed globally but not locally.

Mostly throwing this here 'cause it pops up first on Google for the error.
