### ISSUE TITLE
Parsing error when using via stdin (w/ typescript)

### ISSUE THREAD

**Issue by terlar** [prettier/eslint-plugin-prettier#195]
When using this plugin together with the `@typescript-eslint/parser` and a piece of typescript code that includes something like `[] as any[]`. `prettier/prettier` will receive a parsing error.

I am not 100% sure it is the fault of this plugin, or if it is a combination, but other rules seems to apply without error. This is an error that only occurs when using `--stdin` pointing to the file directly is fine.

**What version of `eslint` are you using?**
5.16.0

**What version of `prettier` are you using?**
1.17.0

**What version of `eslint-plugin-prettier` are you using?**
3.0.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
`.prettierrc`
```json
{
  "printWidth": 100,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5"
}
```

`.eslintrc`
```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint"
  ],
  "plugins": ["@typescript-eslint", "prettier"],
  "rules": {
    "prettier/prettier": "error",
    "@typescript-eslint/array-type": ["error", "array-simple"],
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-object-literal-type-assertion": "off",
    "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
    "@typescript-eslint/no-use-before-define": "off"
  }
}
```

**What source code are you linting?**
```typescript
export const data = {
  key: [] as any[],
  hello: 'world',
}
```

**What did you expect to happen?**
Just like this gives no output/errors:
```
$ eslint_d src/sample.ts
```

This should as well give no errors:
```
$ cat src/sample.ts | ./node_modules/.bin/eslint --stdin
```

**What actually happened?**
```
$ cat src/sample.ts | ./node_modules/.bin/eslint --stdin
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.

<text>
  2:12  error  Parsing error: Unexpected token, expected ","  prettier/prettier
```

**Comment by BPScott** [comment]
Prettier uses filenames  to guess the language used. When you're passing contents from stdin it is unable to guess so it assumes javascript.

You can fix this by using the `--stdin-filename` eslint option which will provide a filename hint for content passed into stdin.

Does this work if you do?

```
$ cat src/sample.ts | ./node_modules/.bin/eslint --stdin --stdin-filename=index.ts
```

**Comment by terlar** [comment]
Ah, thank you! Mystery solved, that indeed does work and makes sense.
