### ISSUE TITLE
Allow to pass a custom version of prettier as a dependency

### ISSUE THREAD

**Issue by onigoetz** [prettier/eslint-plugin-prettier#197]
**What version of `eslint` are you using?**
latest, 5.16.0

**What version of `prettier` are you using?**
latest, 1.17.1

**What version of `eslint-plugin-prettier` are you using?**
latest, 3.1.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

I use a configuration tool, Crafty, that handles that for me, but related to prettier my config is : 

```
rules: {
    "prettier/prettier": ["warn", { parser: "babel" }],
}
```

**What source code are you linting?**
N/A

**What did you expect to happen?**
The code to be linted

**What actually happened?**

```
./src/index.ts
Error: Cannot find module 'prettier'
Occurred while linting .../src/index.ts:1
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

So, yes, the problem is obvious, I don't have Prettier installed.
The thing is, I'm the maintainer of a tool that bundles all the tools you need to build/lint code in a single dependency (similar to create-react-app) .

Now I would like to be able to pass the full path of the prettier module as a configuration option, this way I can add prettier as a dependency. Same as you would do for a Babel Preset or other tool's configuration.
In the case of a simple user configuration it's not necessary but in case of Yarn PNP or simply a configuration that is inherited, it's better to have everything bundled.

I can provide a pull-request if necessary

**Comment by not-an-aardvark** [comment]
I'm confused about why a `peerDependency` causes a problem here. It seems like if you install both `eslint-plugin-prettier` and `prettier`, then `eslint-plugin-prettier` will be able to load `prettier` since it's specified as a `peerDependency`. Is that not the case?

**Comment by onigoetz** [comment]
in the case of Yarn PNP it works only if the dependency is at the top level.
For example

Standard usage : 

```
- my app
  - prettier
  - eslint-plugin-prettier
```

This will work fine as Yarn PNP will see the top level dependency and resolve it for eslint-plugin-prettier

Plugin bundled:

```
- my app
  - prettier
  - my-eslint-plugin-bundle
    - eslint-plugin-prettier
```
In this case it will work as well as prettier is still at the top level.

Plugin and Prettier bundled:

```
- my app
  - my-eslint-plugin-bundle
    - eslint-plugin-prettier
    - prettier
```

This is the case where Yarn PNP will be unhappy as the dependency is not resolved directly, it won't know where to look for the files as Yarn PNP doesn't create a node_modules hierarchy.

The pull-request that I made solves this exact problem.

**Comment by not-an-aardvark** [comment]
If that's true, it seems to be a bug in Yarn PNP. If `my-eslint-plugin-bundle` specifies both `eslint-plugin-prettier` and `prettier`, then `prettier` should be loadable from `eslint-plugin-prettier` because it's specified as a `peerDependency`.

**Comment by BPScott** [comment]
I think I agree with @not-an-aardvark, This works without Yarn PnP - we do something somewhat similar to having a package that provides all our shared tooling configuration at work. So the issue seems to lie with Yarn PnP's resolution and the fix should be on their side.

**Comment by onigoetz** [comment]
Thanks for your input. I'll make some more tests and if this is the case, close the PR

**Comment by BPScott** [comment]
Hi @onigoetz, did you fine a root cause of the issue within Yarn PnP, and can this issue and the associated PR be closed?

**Comment by onigoetz** [comment]
Oh, sorry I left it open for so long.
I dropped yarn pnp from my tool for the moment, mainly due to compatibilty issues with TypeScript.
I'll open a new issue if I still encounter issues with eslint-plugin-prettier.

**Comment by BPScott** [comment]
No worries :) Thanks for the update.
