### ISSUE TITLE
Router-link format error on VUE

### ISSUE THREAD

**Issue by abhayathapa** [prettier/eslint-plugin-prettier#198]
On "eslint.autoFixOnSave": true,
  "editor.formatOnSave": false

Issue with router-link gets formatted to multiples lines as this
``` javascript   
<router-link
    class="event-link"
    :to="{ name: 'event-show', params: { id: '1' } }"
  > ```

**Comment by BPScott** [comment]
That seems inline with that [prettier formats that text to](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTACgB4AnCAV3lIFoAbASygGsAdKTTzMOgQzTR5WIOADcEMekzYh2XTEhgQhIYJii8AtnCSYA5GIk00ACwgB3PQBpMAB16ktaXWoYATXXoCMezAF9-YTlMAD4AMwgIYgB6cio4WkYWEIBKAG4QKxAIWxgGdGRQB3JzAAUHBDRkEF5RCHdMkAAjRzBmOBgAZXswJgBzZBhSCjgskxhNOgB1EwZ4NB64Tsq5hlE5gE9qsAFGpjQEmFLHPs1eZDDeOgOsgCs0bAAhVvaurTgAGSY4C6ubkHu2E6-TocAAihQIPBftdRiB7KQDqRqqIRo1bKQmDApu4YCZkAAOAAMWQxEAOU0ctmqGLgSPEjQAjpD4McclUUPwaFA4HA3HzGqQ4MyGELjrxTuckJdYVkDpoGINhnC0CDwSyftK-nCYLwmji3HjkAAmLJDXgMJJ9ADCEE0Z2qUGgPyyFAOABU9RyZQc-H4gA). If you think that formatting is incorrect please raise an issue in the prettier/prettier repo.
