### ISSUE TITLE
error Delete `·` prettier/prettier in a fresh Nuxt.js app with Prettier and Eslint

### ISSUE THREAD

**Issue by jedrekdomanski** [prettier/eslint-plugin-prettier#216]
Fresh Nuxt.js applicatioin with Eslint and Prettier.

**What version of `eslint` are you using?**
`"^5.15.1"`
**What version of `prettier` are you using?**
`"^1.16.4"`
**What version of `eslint-plugin-prettier` are you using?**
`"^3.0.1"`
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
`.prettierrc`
```
{
  "semi": false,
  "singleQuote": true
}
```
`.eslinterc`
```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'prettier',
    'prettier/vue',
    'plugin:prettier/recommended',
    '@nuxtjs',
    'plugin:nuxt/recommended'
  ],
  plugins: [
    'prettier'
  ],
  // add your custom rules here
  rules: {
  }
}
```
**What source code are you linting?**
`plugins/axios.js` (https://axios.nuxtjs.org/extend)
```
export default function ({ $axios, redirect }) {
  $axios.onRequest(config => {})
}
```
**What did you expect to happen?**
No error
**What actually happened?**
![image](https://user-images.githubusercontent.com/5911945/61789206-621a9900-ae14-11e9-8806-e3a82dfb394a.png)

`package.json`
```
{
  "name": "create-ensemble",
  "version": "1.0.0",
  "description": "App for creative people",
  "author": "Jędrek Domański",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint",
    "test": "jest",
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "bootstrap-vue": "^2.0.0-rc.11",
    "bootstrap": "^4.1.3",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/pwa": "^2.6.0",
    "nuxt": "^2.0.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "@nuxtjs/eslint-module": "^0.0.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.15.1",
    "eslint-config-standard": ">=12.0.0",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "prettier": "^1.16.4",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "vue-jest": "^3.0.3",
    "nodemon": "^1.18.9"
  }
}

```

**Comment by BPScott** [comment]
That all seems to be good.

[Prettier wants there to be no space between function keywords and brackets for anonymous functions](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jyowYBLaPACmDwBJS1mBnADR5scAoxEM8AXwCUeYAB0oeLj34A6aACU4AR3Jw+MVpCjFGAczwBeAHzzZSqSAEgIGJtD7JQpbNggAdwAFPwRvFFIANwhGAhcQACNsUjAAazgYAGUMVMYoC2QYbANXAAsYAFtKAHUyxng+XLA4LPCGxiiGgE9kcD5vV3y+OFxglItK0mQyShHXACs+NAAhFPTMrNJKuAAZfLgZ0jm4ReWs-ItKOABFcgh4I5PXXOwR7D7E0kTuymgEjDYfIwGpxGBlZAADgADC8AiMaikMH1AYZRlFDq59A84ON3BEQKQ+ABaKBwUSiBIifTiXETKZPeYgEaVRhFEqnZmXa53HGMzkwb6ggjg5AAJlcxVIjEolwAwhBKgyUFBoJiQOQRgAVb4RWYjKRSIA)


The file that was generated doesn't adhere to prettier's styling. If you think it should then you should fix the issue in wherever generates that code.

**Comment by linlinNB** [comment]
No help for this problem, very angry on this issue. Did not give a good solution

**Comment by BPScott** [comment]
> No help for this problem.

I'm unsure how I can help? This is a project that allows you to use prettier's formatting opinions. The file provided does not follow prettier's formatting and the "error" is telling you that you should edit your code to follow prettier's formatting.

If you don't like that then either stop using prettier, or open an issue in prettier to change the behaviour

**Comment by jwkicklighter** [comment]
Could at least link to the relevant issue: https://github.com/prettier/prettier/issues/3845

**Comment by phen0menon** [comment]
If you want to disable this annoying warnings/errors from prettier like `delete '.'` and so on, you can create `.eslintignore` file in the root of your project and set folders to ignore:

```
/components/**
/pages/**
/layouts/**
```

You may want to add more folders and you're free to do it.
This works for me, thanks.

**Comment by FrankMwandi** [comment]
This helped me **npm run lint -- --fix**  _( I hope it can work for yarn as well )_

**Comment by mitnick2012** [comment]
@phen0menon  thanks for this solution it's saved my day!

**Comment by anderson916** [comment]
adding `  "semi": false` to .prettierrc fixes.

**Comment by vinikatyal** [comment]
> This helped me **npm run lint -- --fix** _( I hope it can work for yarn as well )_

Thanks

**Comment by xsfxtsxxr** [comment]
"javascript.format.insertSpaceBeforeFunctionParenthesis": false

**Comment by v-radev** [comment]
For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.

**Comment by maitrungduc1410** [comment]
I believe that's because you're copy and paste code from internet.

I was reading [Content](https://content.nuxtjs.org/displaying/) module of Nuxt and tried to copy and paste and it causes the problem, manually type helps

**Comment by Ifeanyichukwuwebdeve** [comment]
Am getting a Delete "cr" problem

**Comment by zhj778930960** [comment]
so,   whati is solution?

**Comment by gokolo** [comment]
So I was getting the error when I tried to commit.
I did this and it worked:
git commit -m "<commit-mesage>" **--no-verify**

I also followed this for VSCode
https://medium.com/@csmunuku/windows-and-linux-eol-sequence-configure-vs-code-and-git-37be98ef71df

**Comment by v-radev** [comment]
@gokolo this will just skip the validation when you commit, it doesn't fix your error. If you have a CI this will fail or if prettier runs for all the files in the project this will fail again on your next commit.

**Comment by betoflakes** [comment]
Here is the solution @v-radev 

Like say @phen0menon:
> I found that the CRLF/LF types do not work correctly on Windows OS, but there are no such problems on Mac/Linux. Try also going through all the files that give you errors and formatting the contents using Prettier.

we fixed formating every file in VS Code, Format Document, Prettier Option and save.

**Comment by v-radev** [comment]
@betoflakes yeah, I already fixed it, mentioning my comment below:
> For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.
I'm on Linux with PHPStorm and I have `.gitattributes` and `.editorconfig` with LF.

**Comment by zhj778930960** [comment]
OK thanks
________________________________
发件人: Ventsislav Radev ***@***.***>
发送时间: 2021年7月8日 14:26
收件人: prettier/eslint-plugin-prettier ***@***.***>
抄送: 张豪杰 ***@***.***>; Comment ***@***.***>
主题: Re: [prettier/eslint-plugin-prettier] error Delete `・` prettier/prettier in a fresh Nuxt.js app with Prettier and Eslint (#216)


@betoflakes<https://github.com/betoflakes> yeah, I already fixed it, mentioning my comment below:

For me it was indentation problem. You can run npx eslint folder/file.js --fix.

I'm on Linux with PHPStorm and I have .gitattributes and .editorconfig with LF.

―

**Comment by zhj778930960** [comment]
thanks
________________________________
发件人: Ventsislav Radev ***@***.***>
发送时间: 2021年7月8日 14:26
收件人: prettier/eslint-plugin-prettier ***@***.***>
抄送: 张豪杰 ***@***.***>; Comment ***@***.***>
主题: Re: [prettier/eslint-plugin-prettier] error Delete `・` prettier/prettier in a fresh Nuxt.js app with Prettier and Eslint (#216)


@betoflakes<https://github.com/betoflakes> yeah, I already fixed it, mentioning my comment below:

For me it was indentation problem. You can run npx eslint folder/file.js --fix.

I'm on Linux with PHPStorm and I have .gitattributes and .editorconfig with LF.

―
