### ISSUE TITLE
error  Delete `··`  prettier/prettier

### ISSUE THREAD

**Issue by IceApriler** [prettier/eslint-plugin-prettier#219]
**What version of `eslint` are you using?**
No use
**What version of `prettier` are you using?**
"prettier": "^1.18.2"
**What version of `eslint-plugin-prettier` are you using?**
"eslint-plugin-prettier": "^3.1.0"
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```json
{
  "printWidth": 80,
  "eslintIntegration": true,
  "stylelintIntegration": true,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": false
}
```
```json
{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": [
    "plugin:@typescript-eslint/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "prettier"],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly",
    "wx": "readonly",
    "getCurrentPages": "readonly",
    "getApp": "readonly",
    "Page": "readonly",
    "Component": "readonly",
    "App": "readonly"
  },
  "root": true,
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.json"
  },
  "rules": {
    "prettier/prettier": "error",
    "@typescript-eslint/member-delimiter-style": "off",
    "@typescript-eslint/interface-name-prefix": ["warn", "always"],
    "@typescript-eslint/explicit-function-return-type": ["error", {
      "allowExpressions": true,
      "allowTypedFunctionExpressions": true,
      "allowHigherOrderFunctions": true
    }],
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/indent": ["error", 2]
  }
}
```
**What source code are you linting?**
```ts
/**
 * 小程序配置文件
 */

const isProd = false
const isMock = false

const config: IConfig = {
  version: '1.5.7',
  versionDesc: `xxxxxx`,
  isProd,
  env: isProd ? 'pro' : 'dev',
  rootUrl: isProd
    ? 'https://xxx.funxi.cn'
    : isMock
      ? 'http://xxx:8017'
      : 'https://xxx.cn',
  tabBarUrlList: []
}

export default config

```
**What did you expect to happen?**
fix error
**What actually happened?**
Here's a error message：
![image](https://user-images.githubusercontent.com/29689307/63325899-a0e13780-c35d-11e9-84e7-f9cd9234268a.png)

Here's a hint from gulp-eslint：
As you can see, "fixed" is true, and the error indicates that it has been fixed, but the actual situation is not fixed. This misleads me into a constant cycle of error reporting and fixing.
```json
{ filePath:
   '/Users/april/myfile/www/gitstore/wechat_cabinet/src/config.ts',
  messages:
   [ { ruleId: 'prettier/prettier',
       severity: 2,
       message: 'Delete `··`',
       line: 16,
       column: 5,
       nodeType: null,
       endLine: 16,
       endColumn: 7,
       fix: [Object] },
     { ruleId: 'prettier/prettier',
       severity: 2,
       message: 'Delete `··`',
       line: 17,
       column: 1,
       nodeType: null,
       endLine: 17,
       endColumn: 3,
       fix: [Object] } ],
  errorCount: 2,
  warningCount: 0,
  fixableErrorCount: 2,
  fixableWarningCount: 0,
  output:
   '/**\n * 小程序配置文件\n */\n\nconst isProd = false\nconst isMock = false\n\nconst config: IConfig = {\n  version: \'1.5.7\',\n  versionDesc: `xxxxxx`,\n  isProd,\n  env: isProd ? \'pro\' : \'dev\',\n  rootUrl: isProd\n    ? \'https://xxx.funxi.cn\'\n    : isMock\n      ? \'http://xxx:8017\'\n      : \'https://xxx.cn\',\n  tabBarUrlList: []\n}\n\nexport default config\n',
  fixed: true }
```
However, if I change 'printWidth' to 400, then 'rootUrl' will not prompt error messages and will not format line breaks, so the above problem will not occur, but it will not solve the root problem.

**Comment by BPScott** [comment]
[Prettier belives you've got too many spaces on lines 16 and 17](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3QeB1BoL0Hi9QWUTA7f0HDTQN7kd9UcdIoBnGXASzYAUAnCABNcAXlwAzAIYAbNnBbQO3NgFkIYANZjJs+cyitlrCVwDmSXAEkAwtFNmdwBrgBucfmy7RLAcgCMAHQArIEA7L4ANC7unt5QACJwbGCWAAYAHlnZadF4KgLCebi4CK6WPIUiAPy4vgAOgr64fkJwrlEughAwAKr8MhV8gkIuJbW+ABYwMPVsSKio2YESAK5QGVyBYFC+Yy0q6lr743XTswtLWUgAHAAM-hEnB1Mzc5fLO535MFIARgAhKT8foyAAyPBglgA2gBdHAAXwMcAy9Qg-E4bWkqxknBM5hAkRAEHqMHibGQoGBggA7rxgQgKSgpK4IFwhISQH9+FItHAYABleq8rhQMzIGD8VZwInTAC2MgA6pMuPA2MKwHABYzVVxXKqAJ7IcBsClE0XyDECKRmOVSZDSOQykAAKzYGQBPL5gqkcrgEKgcAdemdboyAtFZhkcAAiqsekGkI75EThZ4PMa-v8DTJoJzGqKYIr2TBJsh7qnBPJFTz6sbGskPO5OQBHePwQpzY1SNgAWkDcDaHKJ-Dgba4o+ttvtSZDRPkcq4Eqlzq8YujcYTwadRN+f2LQlLyAATLueVwZJG7HK7caoNAg0TVvIACr-JnJuAIhFAA). As such we seem to be reporting the error from prettier correctly.

If running eslint with the `--fix` flag does not cause this to be fixed then I expect you have some other eslint rule conflicting with prettier's fix that is putting the spacing back.

I note that you are not extending the [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) configuration. You should configure that there are no eslint rules that conflict with prettier's formatting.

**Comment by mutaimwiti** [comment]
Check and make sure you don't have the `indent` eslint rule.

**Comment by Dozorengel** [comment]
@mutaimwiti or, you can add this line to your `.prettierrc`

`"endOfLine": "auto"`

**Comment by ufon** [comment]
As @Dozorengel described, problem is probably related with your line ending file format. 
Try to setup `.editorconfg` file https://editorconfig.org/ or try to change line ending in your editor.

**Comment by justice47** [comment]
None of this helped me actually

**Comment by v-radev** [comment]
For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.

**Comment by indolent-developer** [comment]
make sure add rules: {'prettier/prettier': ['error', {endOfLine: 'auto'}]}, line in .eslintrc.js and also enable prettier plugin in vs code.

**Comment by Joseph-Anthony-King** [comment]
None of this is helpful

**Comment by mohibk** [comment]
No of the solution fixed my problem. Please help.

**Comment by mohibk** [comment]
None of the solutions fixed my error. Please help.

**Comment by Voland91** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/56713746/110337879-ab8a1d00-8026-11eb-9258-2e9ee9da4a17.PNG)
Changing from CRLF to LF helps

**Comment by viniciusbe** [comment]
I don't know if it's an obvius mistake that I did, but I solved this by removing "editor.formatOnSave": true from vscode settings.json

**Comment by ehduardu** [comment]
put this in eslintrc.js, worked for me:

`rules: {
    'prettier/prettier': ['off', { singleQuote: true }],
}`

**Comment by ehduardu** [comment]
put this in eslint file, worked for me:

`"prettier/prettier": ["error", { "endOfLine": "off" }]`

**Comment by vishnumishra** [comment]
Run
> yarn run lint --fix
This fix the issues for me

**Comment by jorgerabello3** [comment]
Here I'm using npm and so I run the equivalent command:

> npm run lint --fix

Solved here !

**Comment by vocongdat** [comment]
"prettier/prettier": [
            "warn",
            { "singleQuote": true, "endOfLine": "auto", "tabWidth": 4 }
        ],

**Comment by lixiangincrypto** [comment]
disable your default formatter, only use eslint as code formatter

**Comment by lojickse7en** [comment]
> Here I'm using npm and so I run the equivalent command:
> 
> > npm run lint --fix
> 
> Solved here !

for those confused still, you may want to check this vid for context. https://www.youtube.com/watch?v=St1YSNoB36Y&t=121s

I was able to eventually solve my issue. I added a script under "scripts" in the package.json===>   "lintfix": "eslint ./src --fix --ext .js"  <===then a ran npm run lintfix

**Comment by Moranilt** [comment]
here is my solution. Pay attention on line with rules for prettier. Just add **{"endOfLine": "auto"}** for prettier rules. 

**.eslintrc:**
```json
{
  "extends": [
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "react-app",
    "react-app/jest",
    "prettier"
  ],
  "plugins": ["@typescript-eslint", "prettier"],
  "parser": "@typescript-eslint/parser",
  "rules": {
    "prettier/prettier": ["warn",  {"endOfLine": "auto"}],
    "testing-library/prefer-screen-queries": "error",
    "testing-library/no-manual-cleanup": "error",
    "testing-library/prefer-wait-for": "error",
    "testing-library/no-await-sync-events": "error",
  }
}
```
**.prettierrc:**
```json
{
    "tabWidth": 2,
    "quoteProps": "as-needed",
    "singleQuote": true,
    "printWidth": 120,
    "semi": true,
    "useTabs": false,
    "trailingComma": "all",
    "arrowParens": "avoid",
    "endOfLine": "auto"
}
```

**dependencies:**
![image](https://user-images.githubusercontent.com/22654219/127449831-3728cbeb-ab95-4482-82ef-c6a43a450ab3.png)

**Comment by tashrifbillah** [comment]
@v-radev 's solution:

> For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.

worked for me.

---

In my file, I had many lines like:
```javascript
       await fetchJson('/api/admin/sites', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify(body),
       });
       await fetchJson('/api/admin/sites', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify(body),
       });
```

I inserted one linear line like:
```javascript
     await sendVerificationEmail({ email: a, token: b })
```

Which broke the eslint rule. After running the solution, I see that it got restructured like the rest:
```javascript
       await sendVerificationEmail({
         email: a,
         token: b,
       });
```

**Comment by Pirhot01** [comment]
1. npm run lint --fix
2. open file .prettierrc and add this "endOfLine": "auto"

**Comment by tomleo** [comment]
Not sure this will help anyone else, but errors didn't go away for me until I restarted vscode.

**Comment by vcheeney** [comment]
> Not sure this will help anyone else, but errors didn't go away for me until I restarted vscode.

@tomleo It did! I changed my `tabWidth` property in my `.prettierrc` file and I believe the VS Code Prettier extension did not immediately pickup the change. I saved a file and saw the tab width change to the new setting and then straight back to the original one while having eslint yelling at me that my indentation was incorrect. Reloading VS Code seems to have forced the Prettier extension to pick up the new config and now when I save a file my code indentation matches the newly set config without issues. Therefore thanks for your comment, it helped out! 😅

**Comment by radek-vizlib** [comment]
Restarting vscode helped. It has some issue with detecting changes in prettier config

**Comment by mfapproach** [comment]
There is a setting in Visual Studio Code "Javascript > Format: Enable" that can potentially conflict with the Prettier formatting. After disabling this setting, Prettier was able to take full control and fixed this problem for me.

<img width="866" alt="Screen Shot 2022-06-10 at 12 03 04 AM" src="https://user-images.githubusercontent.com/20707705/172993881-b1ce6684-5864-4d10-9e6c-82923bf6cde5.png">

**Comment by elioenays** [comment]
> "prettier/prettier": ["error", { "endOfLine": "off" }]

solve for me

**Comment by JounQin** [comment]
> > "prettier/prettier": ["error", { "endOfLine": "off" }]
> 
> solve for me

This is not a good practice IMO.

**Comment by codthing** [comment]
> ![Przechwytywanie](https://user-images.githubusercontent.com/56713746/110337879-ab8a1d00-8026-11eb-9258-2e9ee9da4a17.PNG) Changing from CRLF to LF helps

it works for me, thx

**Comment by JounQin** [comment]
It seems you need a `.edtorconfig` file with `end_of_line = lf`

**Comment by alinpruness** [comment]
<img width="253" alt="Screenshot 2022-09-14 at 22 29 20" src="https://user-images.githubusercontent.com/104574935/190245256-db1feede-4964-4a7d-aaba-6cf54c2cd79a.png">
<img width="594" alt="Screenshot 2022-09-14 at 22 27 07" src="https://user-images.githubusercontent.com/104574935/190245259-8e824b83-a2ec-4091-84a8-60582608fd75.png">

Just select "Trim Trailing Whitespaces" if you use VSCode.
For other editors, I would suggest to default your code formatter to eslint or avoid formatting until the end and then use `eslint --fix`.

**Comment by shunyue1320** [comment]
this worked for me 


.vscode/settings.json
```js
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  //  add this line for you file type, prettier save, not eslint save
  "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true,
      "source.addMissingImports": true
  },
  "eslint.enable": true,
  "eslint.format.enable": true
}
```

**Comment by nazzalra** [comment]
Disable default typescript formatter. This fixed the issues for me

**Comment by ashfaqnisar** [comment]
Most of the above solutions should have the fixed the issue for you. 
But, if the issue still persists check whether you have multiple prettier config files or prettier config in any other file. Like: 
- **prettier.config.js**
- **prettierrc**

You should only have **only one prettier config**. Simple Bug but wastes time.

**Comment by wicaksana94** [comment]
> @mutaimwiti or, you can add this line to your `.prettierrc`
> 
> `"endOfLine": "auto"`

This one helped me, I tried it for the first time and it doesn't solved the issue, until I re-open my vscode.

**Comment by airdropdrone** [comment]
> For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.

working thanks for help

**Comment by JosephZamalloa** [comment]
On "setting.json" change this, some times "modification" works, some times "file" works, just try it 
![image](https://github.com/prettier/eslint-plugin-prettier/assets/94031606/5c7054bc-cce2-42aa-a446-a4e66b0c8bba)

**Comment by slushnys** [comment]
Not sure who may find this useful, but I realised this happened because I was declaring an anonymous function which somehow affected formatting of prettier. Rewriting the function declaration to be a named function helped. Also it's a benefit because tracing named functions give you the name, while anonymous functions may be harder to trace.

**Comment by improm** [comment]
While lint command fixed the issue, it reappeared as soon as I changed content of the file.  Disabling this option in VS Code fixed the issue:

JavaScript > Format: Insert Space After Opening And Before Closing Jsx Expression Braces

<img width="755" alt="Screenshot 2023-10-11 at 12 29 38 AM" src="https://github.com/prettier/eslint-plugin-prettier/assets/10056427/127a4a99-7675-44f7-af2f-a95afd65b66d">

**Comment by andyeryto** [comment]
> make sure add rules: {'prettier/prettier': ['error', {endOfLine: 'auto'}]}, line in .eslintrc.js and also enable prettier plugin in vs code.

it helps me!!!

![image](https://github.com/prettier/eslint-plugin-prettier/assets/1946115/79cf3f65-a8fd-4203-b138-9035e85ba458)

**Comment by Serpentarius13** [comment]
Can someone help me? I created new Nest project and the error happens to me whenever I use `.prettierrc` fixes or `eslintrc` ones. Repo: https://github.com/Serpentarius13/nest-eslint-error. I use webstorm

**Comment by JounQin** [comment]
@Serpentarius13 Thanks for repo, please raise a new issue instead, I'll take a look later.

**Comment by NascentKiosk** [comment]
i run the following command in the terminal: 
npm run lint --fix

this fixed the issue

**Comment by dan1xk** [comment]
> @mutaimwiti or, you can add this line to your `.prettierrc`
> 
> `"endOfLine": "auto"`

works for me

**Comment by Robert-Roos** [comment]
This works:
```
"prettier/prettier": [
      "off",
      {
        "endOfLine": "auto"
      }
    ]
```
But i'm pretty sure it's just a workaround and not the actual fix.

**Comment by lyonsun** [comment]
I am using VSCode, and adding the following additional setting option worked for me.
```
"eslint.format.enable": true,
```
I need to run prettier and auto fix everything afterwards though.

**Comment by w2xi** [comment]
> For me it was indentation problem. You can run `npx eslint folder/file.js --fix`.

This works for me.

**Comment by zhengchchen** [comment]
> put this in eslint file, worked for me:
> 
> `"prettier/prettier": ["error", { "endOfLine": "off" }]`

This works for me.

**Comment by TatyanaMolchanova** [comment]
In eslintrc:
 "rules": {
        "prettier/prettier": "off",

**Comment by Gojo1729** [comment]
"prettier/prettier": ["error", { "tabWidth": 4 }] solved the issue

**Comment by mrklwnc** [comment]
> put this in eslint file, worked for me:
> 
> `"prettier/prettier": ["error", { "endOfLine": "off" }]`

this fixed mine

**Comment by User-ChengQian** [comment]
"prettier/prettier": ["error", { "endOfLine": "off" }] use this to resolve
ssssssssssssssssssssssshit and stupid bug

**Comment by jeremytenjo** [comment]
This worked for me:

`eslint.config.js`
```js
rules: {
  'prettier/prettier': ['off'],
...
```

`package.json`
```json
"eslint": "9.39.1",
"eslint-plugin-prettier": "5.5.4"
```
