### ISSUE TITLE
Incorrect behavior with multiline comments and strings

### ISSUE THREAD

**Issue by xarety** [prettier/eslint-plugin-prettier#229]
```
type IAmIncredibleLongParameterType = {};
const IAmAnotherFunctionName = (_0: IAmIncredibleLongParameterType) => {};
export const IAmIncredibleLongFunctionName = IAmAnotherFunctionName(
    (_0: IAmIncredibleLongParameterType) => {
        setTimeout(() => {
            /*
                Multiline comment
                Multiline comment
                Multiline comment
            */
            console.log(
                'Multiline string\
                 Multiline string\
                 Multiline string'
            );
        });
    }
);
```
**Before running `lint --fix`:**

![before](https://user-images.githubusercontent.com/17852627/65254692-5b06c300-db05-11e9-829c-8ad8cae4369b.PNG)

Errors:
```
   6:15  error  Delete `␍`  prettier/prettier
   7:34  error  Delete `␍`  prettier/prettier
   8:34  error  Delete `␍`  prettier/prettier
   9:34  error  Delete `␍`  prettier/prettier
  12:35  error  Delete `␍`  prettier/prettier
  13:35  error  Delete `␍`  prettier/prettier
```
**After running `lint --fix`:**

![after](https://user-images.githubusercontent.com/17852627/65254717-66f28500-db05-11e9-8c53-487086edc148.PNG)

**What version of `eslint` are you using?**
6.0.1

**What version of `prettier` are you using?**
1.18.2

**What version of `eslint-plugin-prettier` are you using?**
3.1.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
{
  "printWidth": 100,
  "tabWidth": 4,
  "singleQuote": true,
  "quoteProps": "consistent"
}
```
```
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module'
    },
    plugins: ['import', 'folder-schema', 'processors-stub', 'react-hooks'],
    extends: ['plugin:import/typescript', 'plugin:prettier/recommended'],
    rules: {
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn'
    }
};
```

**What source code are you linting?**
*.tsx

**What did you expect to happen?**
Equal line endings for the whole file.

**What actually happened?**
The plugin is requiring and replacing CRLF with LF in multiline strings and comments

**Comment by BPScott** [comment]
The plugin shouldn't manipulate line endings itself - it just renders what is given to us by prettier.

Can you try and run just prettier over your file from the command line to see if the same issue occurs? If so then the issue is with prettier, not with this plugin and in which case you should open an issue in https://github.com/prettier/prettier

**Comment by xarety** [comment]
Closed in favor: https://github.com/prettier/prettier/issues/6501
