### ISSUE TITLE
Allow Use of Prettier Plugins

### ISSUE THREAD

**Issue by shellscape** [prettier/eslint-plugin-prettier#234]
**What version of `eslint` are you using?** 6.5.1

**What version of `prettier` are you using?** 1.18.2

**What version of `eslint-plugin-prettier` are you using?** 3.1.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**What source code are you linting?** n/a

**What did you expect to happen?**

I'd like to be able to use prettier plugins along with this ESLint plugin. See: https://prettier.io/docs/en/plugins.html

**What actually happened?**

We presently cannot specify plugins for prettier to use, and plugins aren't picked up by default (for an unknown reason).

**Comment by BPScott** [comment]
Hi @shellscape, can you please provide a repository that demonstrates this problem? With the info you've gave currently I've don't understand what the problem is or how to reproduce it so the issue can be investigated.

**Comment by shellscape** [comment]
Well the request is pretty straightforward - Prettier has a plugin API now and it has command line flags and options for the API that instruct it to use specific plugins. Extending that to what can be passed to Prettier via this ESLint plugin is a logical progression. I had thought that would be apparent. 

If you really need a repo, you can look to https://github.com/rollup/plugins. If you need a functional example of how the command line flag for plugins is used, you can look to https://github.com/rollup/plugins/blob/master/packages/beep/package.json#L26. 

Citing the [docs](https://prettier.io/docs/en/plugins.html) linked above, specifying a plugin via the API:

```js
prettier.format("code", {
  parser: "foo",
  pluginSearchDirs: ["./dir-with-plugins"],
  plugins: ["./foo-plugin"]
});
```

Citing this ESLint plugin's [docs](https://github.com/prettier/eslint-plugin-prettier/blob/master/README.md), there's no available way to specify Prettier plugin(s) that Prettier should run when executed via eslint-plugin-prettier.

Hopefully that's sufficiently verbose.

**Comment by BPScott** [comment]
Thanks for the extra info :)

The prettier docs page you linked to suggests "Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located. Plugin package names must start with `@prettier/plugin-` or `prettier-plugin-` or @<scope>/prettier-plugin- to be registered." which suggests that hopefully in most cases no explicit config would be needed.


In the cases where config is needed the [first object that you pass into the eslint rule](https://github.com/prettier/eslint-plugin-prettier/blob/master/README.md#options) gets passed through to [`prettier.format()`](https://github.com/prettier/eslint-plugin-prettier/blob/4c1d69a8022c709cd62e964a82c7dbc7963f0544/eslint-plugin-prettier.js#L240) (after a bit of massaging), so it looks like you should already be able to do:

```
"prettier/prettier": ["error", {"pluginSearchDirs": ["./dir-with-plugins"], "plugins": ["./foo-plugin"]}]
```

Our docs link to https://prettier.io/docs/en/options.html which doesn't mention those plugin options that are mentioned on https://prettier.io/docs/en/plugins.html so I appreciate that is not very clear, sorry about that.

---

Regarding https://github.com/rollup/plugins I'm still not quite sure what I'm looking at - I can see that you're using `prettier-plugin-package` and it looks like that plugin only has any effect on package.json. In https://github.com/rollup/plugins however I can't see any point where you're running eslint over package.json at the moment, even in non-master branches. So I'm not quite sure if you're running a problem with this currently.

**Comment by shellscape** [comment]
> I can't see any point where you're running eslint over package.json at the moment, even in non-master branches. So I'm not quite sure if you're running into a problem with this currently, what am I missing?

Peculiar. This is a fairly standard setup these days, with the exception that it's a monorepo, which is less standard but becoming more common. Linting is run on both Circle CI and Github for CI, and just about every modern editor has the capability to run linting in real time or on save. ESLint is tooling, after all.

I clearly can't explain this sufficiently at the moment and I feat it will become a time suck, so I'm going to leave it there. I would say it would behoove the team to add a test for running a plugin through the mentioned first object, but I leave that in your hands. Hopefully that just works.
