### ISSUE TITLE
react/jsx-curly-spacing "never" + Prettier - Incorrect removal of parentheses around multiline JSX

### ISSUE THREAD

**Issue by jamesopti** [prettier/eslint-plugin-prettier#252]
## UPDATE - Issue resolved

IMO this is not clear in the docs at all, but a second prettier extends was needed:

```js
extends: [
    'airbnb',
    'plugin:fetch/recommended',
    'plugin:prettier/recommended',
    'prettier/react',  // THIS OVERRIDES SPECIFIC REACT RULES THAT CONFLICT WITH PRETTIER
  ],
```

## Issue

The error I'm encountering only manifests when the following react rule is enabled (the Airbnb config has this):

`'react/jsx-curly-spacing': ['error', 'never', { allowMultiline: true }],`

➡️ **Input:**
```jsx
function App() {
  return (
    <div
      className={ {display: "flex"} }
      activator={ (
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      ) }>
      My app
    </div>
  );
}

```

❌ **Output (_with `react/jsx-curly-spacing` "never"_):** Opening paren remains, causing compile error
```jsx
function App() {
  return (
    <div
      className={{display: "flex"}}
      activator={(
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      }
    >
      My app
    </div>
  );
}

```

✅ **Output (_with `react/jsx-curly-spacing` "always"_):** BUT this conflicts with Prettier
```jsx
function App() {
  return (
    <div
      className={ {display: "flex"} }
      activator={
        <div>
          my really long divvvvvvvvvvvvvvvvvvvv
          <span>some child</span>
        </div>
      }>
      My app
    </div>
  );
}
```

**What version of `eslint` are you using?**
`v6.7.2`

**What version of `prettier` are you using?**
`1.19.1`

**What version of `eslint-plugin-prettier` are you using?**
`eslint-plugin-prettier@3.1.1`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**.eslintrc**

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    'plugin:react/recommended',
    'plugin:prettier/recommended'
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly'

  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: [
    'react',
    'prettier'
  ],
  rules: {
    'react/jsx-curly-spacing': ['error', 'always', { allowMultiline: true }], // OK (but conflicts with Prettier)
    'react/jsx-curly-spacing': ['error', 'never', { allowMultiline: true }], // ERROR
    'prettier/prettier': 'error'
  },
};
```

**What source code are you linting?**
A simple react component

**What did you expect to happen?**

With the `react/jsx-curly-spacing` "never" setting, the parentheses should be removed correctly, as seen in the 2nd ✅ output example.

This happens when running `yarn eslint --fix "<path-to-component>"` as well as in VSCode

With the *ALWAYS* setting:
![eslint-error-1](https://user-images.githubusercontent.com/3718812/70648426-e1f8a280-1bff-11ea-8142-6a075513cc3d.gif)

With the *NEVER* setting:
![eslint-error-2](https://user-images.githubusercontent.com/3718812/70648450-e9b84700-1bff-11ea-91ad-0652e3c1d8cf.gif)

**What actually happened?**

Only the trailing parenthesis was removed, causing a compile error.

**Comment by BPScott** [comment]
This is documented in eslint-config-prettier readme https://github.com/prettier/eslint-config-prettier

**Comment by KarineBrandelli** [comment]
Well, the issue remains.

![image](https://github.com/prettier/eslint-plugin-prettier/assets/108953489/ebd32b0c-f001-4689-984a-f7a37ddc3068)

and no, adding 'prettier' to the extends (it is only prettier now, not prettier/react btw) didn't solved it.

any ideias?

```ts
    'react/jsx-curly-spacing': [
        'error',
        {
            when: 'always',
            children: true,
            allowMultiline: true
        }
    ]
    
        extends: [
        'eslint:recommended',
        'plugin:cypress/recommended',
        'plugin:import/recommended',
        'plugin:import/typescript',
        'plugin:react/recommended',
        'plugin:react/jsx-runtime',
        'plugin:react-hooks/recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:prettier/recommended',
        'prettier'
    ],
```

**Comment by JounQin** [comment]
@KarineBrandelli reload VSCode or restart VSCode ESLint progress after eslint config changed.

**Comment by KarineBrandelli** [comment]
@JounQin I've restarted my laptop and it still didn't work 🤷🏻‍♀️

**Comment by JounQin** [comment]
@KarineBrandelli Then a minimal online reproduction is required. Please open a new issue with required info.
