### ISSUE TITLE
Failed to load config "prettier" to extend from Referenced from: .../node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js

### ISSUE THREAD

**Issue by marcosguti** [prettier/eslint-plugin-prettier#253]
**What version of `eslint` are you using?**
"eslint": "^6.5.1"
**What version of `prettier` are you using?**
"prettier": "^1.18.2"
**What version of `eslint-plugin-prettier` are you using?**
"eslint-plugin-prettier": "^3.1.1"
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```{
  "env": {
    "es6": true,
    "node": true
  },
  "extends": ["standard", "prettier", "plugin:prettier/recommended"],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "semi": false,
        "jsxSingleQuote": true
      }
    ]
  }
}
```
**What source code are you linting?**
nodejs/express
**What did you expect to happen?**
show warnings a suggestion to solve problems
**What actually happened?**
not show any warning or suggestion and this error
![error](https://user-images.githubusercontent.com/18442798/70756207-57549800-1d12-11ea-8212-ca36f93d6a7a.png)

**Comment by richard-lopes-ifood** [comment]
Did you found what's wrong? @marcosguti

**Comment by marcosguti** [comment]
yeah, is was and error importing folders, we cant not import folder with two repos, the correct practice is import first folder then add second folder to workspace and save workspace

**Comment by kaytwo** [comment]
I just had this error: I was manually installing the prettier modules, and only had `eslint-plugin-prettier` but not `eslint-config-prettier`. running `npm install --save-dev eslint-config-prettier` fixed this error.

**Comment by brettz9** [comment]
I was getting this error due to not having installed `eslint` (only the plugin and config). :-)

**Comment by derekschinke** [comment]
I have all of those things installed, and I'm getting the error. `eslint`, `eslint-plugin-prettier`, and `eslint-config-prettier`
