### ISSUE TITLE
Parsing error: Unexpected token )

### ISSUE THREAD

**Issue by lipis** [prettier/eslint-plugin-prettier#26]
I have isolated the problem in a self contain project and here you can see the actual problem:

https://github.com/lipis/prettier-tests/issues/1

What am I doing wrong? Why do I get this error..?

**Comment by not-an-aardvark** [comment]
Your file has a syntax error. To fix it, you should remove the comma at the end of line 5.

**Comment by lipis** [comment]
That was my problem.. that this comma was added when I was trying to `--fix` it. The `parserOption` did the trick! Thank you..

**Comment by lipis** [comment]
Actually not.. this comma at the end of line 5 is added by Prettier and we can't go with the `ecmaVersion: 2017` (as more things are failing).

When I'm not using the `trailingComma: all` it works, but we want the trailing commas.

**Comment by not-an-aardvark** [comment]
Trailing function commas are a syntax error before ES2017.

If you want your code to have trailing commas, you can configure prettier to output them and configure ESLint to parse them, but this might break other tools that can't handle trailing function commas.

Alternatively, if you want your code to be valid without ES2017, ypu can configure `prettier` to not output trailing function commas (with the `es5` or `none` value for `trailingComma`).
