### ISSUE TITLE
Incorrect formatting

### ISSUE THREAD

**Issue by PatrikElfstrom** [prettier/eslint-plugin-prettier#261]
First of all I don't know if this is the right place for this issue but it seems to be a bug with prettier and eslint together.

I stumble upon this error when linting a big and ugly formatted project.  
And the issue seems to occur because of a combination of stuff with indentation, curly brackets etc.
For example, fixing the indentation manually or removing the `tabWidth` setting in the `.prettierrc` config will fix the issue.

I've created a repo that can reproduce the issue:  
https://github.com/PatrikElfstrom/eslint-prettier-bug

**What version of `eslint` are you using?**
6.8.0
**What version of `prettier` are you using?**
1.19.1
**What version of `eslint-plugin-prettier` are you using?**
3.1.2
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
**.eslintrc**
```
{
    "parser": "@typescript-eslint/parser",
    "extends": ["eslint-config-airbnb-base", "plugin:prettier/recommended"]
}
```

**.prettierrc**
```
{
  "tabWidth": 4
}
```
**What source code are you linting?**
See: https://github.com/PatrikElfstrom/eslint-prettier-bug/blob/master/index.ts

**What did you expect to happen?**
Code should be formatted with the correct amount of curly brackets.

**What actually happened?**
An extra curly bracket is added, breaking the code.

**Comment by haixiangyan** [comment]
Try this  (Not using short hand `"extends": ["plugin:prettier/recommended"]`:

```json
{
  "extends": ["eslint-config-airbnb-base", "prettier"],
  "rules": {
    "prettier/prettier": "error"
  },
  "plugins": ["prettier"]
}
```

Ref: https://github.com/prettier/eslint-plugin-prettier/issues/103#issuecomment-425670176

**Comment by PatrikElfstrom** [comment]
@haixiangyan While not a problem I have anymore it seems like that solved it. Thank you.
