### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MedinaGitHub** [prettier/eslint-plugin-prettier#265]
i have this problem 
![image](https://user-images.githubusercontent.com/16387514/74805349-8f072f80-52c1-11ea-9d52-0b3df754821e.png)
Thanks you for you help

**Comment by MedinaGitHub** [comment]
![image](https://user-images.githubusercontent.com/16387514/74805339-89a9e500-52c1-11ea-916c-5572e81e05d1.png)

**Comment by the-simian** [comment]
@MedinaGitHub Just to cover our bases, did you read the installation section in the ReadMe ?

https://github.com/prettier/eslint-plugin-prettier#installation

Of note `eslint-plugin-prettier does not install Prettier or ESLint for you. You must install these yourself.`

Not installing these could result in the fact this is throwing an error like this.

**Comment by BPScott** [comment]
It looks like you've not installed eslint and prettier. As @the-simian point out you'll need to install those yourself.
