### ISSUE TITLE
Removes trailing newline

### ISSUE THREAD

**Issue by Iambecomeroot** [prettier/eslint-plugin-prettier#27]
Using this plugin give me errors such as `error  Delete '⏎'  prettier/prettier` when using eslint. It is not a problem with prettier because running `prettier` directly does not remove them. I am using v2.1.1 of the plugin.

**Comment by not-an-aardvark** [comment]
Thanks for the report. Can you give more details? What source code are you running `eslint-plugin-prettier` on? Also, what version of `prettier` are you using?

**Comment by nickdecooman** [comment]
Same issue here.

You can reproduce it by running:
```
git clone -b bug/eslint-plugin-prettier git@github.com:nickdecooman/template-react-frontend.git
cd template-react-frontend/app
yarn install
./up.sh
```

The error that will appear is:
```
./src/Router.js
  Line 9:   Delete `·(`  prettier/prettier
  Line 17:  Delete `⏎)`  prettier/prettier
```

**Comment by not-an-aardvark** [comment]
Thanks for the additional info. I cloned your example, but I'm confused becauserunning `node_modules/.bin/prettier` on the file also makes that correction. So it seems like it's just an issue with `prettier` (or `prettier` is working fine and your file is just formatted incorrectly).

**Comment by Iambecomeroot** [comment]
Looking at it again I do believe you are correct. Prettier is making that correction too, I just didn't notice because my prompt automatically adds a newline if needed and my vim wasn't configured to reload files when they change.

**Comment by pieterwouda** [comment]
I somehow have the same error within my **.vue** files.

![Delete `⏎`  prettier/prettier](https://i.imgur.com/QjTULzz.png "Delete `⏎`  prettier/prettier")

I'm using VS Code with ESLint.
When I save the **.vue** file, it auto-'fixes' the file using prettier, only not in the preferred way.

![Fixed: Delete `⏎`  prettier/prettier](https://i.imgur.com/bSKuYuI.png "Fixed: Delete `⏎`  prettier/prettier")

There might be something wrong with my **.eslintrc.json** file, but I'm not sure what it is.

**.eslintrc.json**
```javascript
{
  "root": true,
  "parser": "babel-eslint",
  "env": {
    "browser": true
  },
  "extends": [
    "standard",
    "eslint:recommended",
    "prettier"
  ],
  "plugins": [
    "html",
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true
      }
    ]
  }
}
```

**.babelrc**
```javascript
{
  "presets": [
    "env",
    "stage-2"
  ]
}
```

**.vscode/settings.json**
```javascript
{
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    "javascript",
    {
      "language": "vue",
      "autoFix": true
    }
  ]
}
```
