### ISSUE TITLE
When will this be updated to use prettier 2.0

### ISSUE THREAD

**Issue by jrwpatterson** [prettier/eslint-plugin-prettier#270]
Just wondering how to use this with the new `Always add a space after the function keyword`

**Comment by BPScott** [comment]
We have a peerDependency of `"prettier": ">= 1.13.0"`, and we don't depend on prettier directly. This means there's nothing for us to do.  I don't think and of prettier's linting APIs that this plugin uses have changed.

So to update, go edit your package.json and increase your prettier dependency.
