### ISSUE TITLE
Use Prettier 2.0

### ISSUE THREAD

**Issue by DavidHenri008** [prettier/eslint-plugin-prettier#273]
**What version of `eslint` are you using?**
version 6.8.0

**What version of `prettier` are you using?**
version 2.0.1

**What version of `eslint-plugin-prettier` are you using?**
version 3.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.prettierrc
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "printWidth": 100,
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "always",
  "requirePragma": false,
  "endOfLine": "auto"
}

**What source code are you linting?**
const value = `${t(calculateShortActionLabel(action)).replace(/\.$/, '')} (${actionCount[action] ?? ''})`;

**What did you expect to happen?**
const value = `${t(calculateShortActionLabel(action)).replace(
              /\.$/,
              ''
            )} (${actionCount[action] ?? ''})`;

**What actually happened?**
const value = `${t(calculateShortActionLabel(action)).replace(
              /\.$/,
              ''
            )} (${actionCount[action] ?? ''})`;

but with error :
 Line 122:75:  Replace `␍⏎··············/\.$/,␍⏎··············''` with `/\.$/,·'')}·(${`                   prettier/prettier
 Line 125:13:  Replace `)}·(${actionCount[action]·??·''` with `··actionCount[action]·??·''␍⏎············`  prettier/prettier

**Comment by BPScott** [comment]
We have a peerDependency of "prettier": ">= 1.13.0", and we don't depend on prettier directly. This means there's nothing for us to do. I don't think and of prettier's linting APIs that this plugin uses have changed.

So to update, go edit your package.json and increase your prettier dependency. Make sure you're not depending on multiple versions of prettier lock file.

**Comment by DavidHenri008** [comment]
I will retry but the only way I was able to make my application work without error was to remove the eslint-plugin-prettier from the eslint configuration plugin list.

**Comment by BPScott** [comment]
The alternative is that you've got some other rule that conflicts with prettier - you'll need to find that and disable it -eslint-config-prettier contains configs for disabling most of the conflicting rules.

**Comment by Anxium** [comment]
@DavidHenri008 If it helps, i had to delete my package-lock and reinstall my dependencies after updating prettier to version 2.0.
