### ISSUE TITLE
Prettier 2.x

### ISSUE THREAD

**Issue by lpoulter** [prettier/eslint-plugin-prettier#277]
It would be great to have support for Prettier 2.x

**Comment by jeanmarcprevost** [comment]
Yes, very great and useful :).

**Comment by BPScott** [comment]
As I said in https://github.com/prettier/eslint-plugin-prettier/issues/273


> We have a peerDependency of "prettier": ">= 1.13.0", and we don't depend on prettier directly. This means there's nothing for us to do. I don't think and of prettier's linting APIs that this plugin uses have changed.
> So to update, go edit your package.json and increase your prettier dependency. Make sure you're not depending on multiple versions of prettier lock file.

**Comment by jeanmarcprevost** [comment]
Oh yes, thank you, we have been in trouble with the Pull request in failure with version 2.0. Thank you again for the rapid answer !
