### ISSUE TITLE
eslint(prettier/prettier) conflict for Space After Function

### ISSUE THREAD

**Issue by gregid** [prettier/eslint-plugin-prettier#282]
I updated all my dependencies including eslint and prettier to:
`eslint: 6.8.0`
`prettier: 2.0.4`
`eslint-plugin-prettier: 3.1.2`
My .eslintrc prettier related settings:
```json
    "extends": [
        "prettier"
    ],
    "plugins": [
        "prettier"
    ],
        "prettier/prettier": [
            "error",
            {
                "trailingComma": "es5",
                "singleQuote": true,
                "printWidth": 80,
                "tabWidth": 4,
                "endOfLine": "lf",
                "arrowParens": "always"
            }
        ],
```
Before the update everything worked fine, eslint executed prettier rules correctly. Now by adding last 2 rules (endOfLine and arrowParens) it almost works but fails with rule for `Space after function`.
`eslint .` passes but `vscode` keeps showing error for any `function ()` and wants to fix it by removing the space - the exact error: 
`Delete `·` eslint(prettier/prettier)`
What is surprising is that according to https://prettier.io/blog/2020/03/21/2.0.0.html
with the upgrade it should require the space after function.
So at the moment `eslint . --fix` adds the space after function and vscode list every instance of the fixed function as a problem. It seems there is no `spaceAfterFunction` option so how can this be fixed?

**Comment by BPScott** [comment]
The VSCode eslint plugin  caches the version of prettier you're using - so you'll need to restart it after update your node_modules in order for it to pick up the new prettier version.

Can you check if you're not accidentally got two versions of prettier in your dependencies, and if you do try and deduplicate them - if you're using yarn you can do `yarn why prettier` to investigate.

**Comment by gregid** [comment]
Great, you are right it started working today (after restart)! What got me confused is that the before the update I had a space after function everywhere and only after the update it wanted to remove it - I guess your (duplicate) explanation fits.

**Comment by bennettfrazier** [comment]
Thanks @BPScott for that suggestion! Restarting VS Code worked to fix my issue as well.
