### ISSUE TITLE
Template literals and printWidth plus eslint not working well

### ISSUE THREAD

**Issue by pthieu** [prettier/eslint-plugin-prettier#285]
**What version of `eslint` are you using?**
`"eslint": "^6.8.0",`
**What version of `prettier` are you using?**
`"prettier": "^2.0.4",`
**What version of `eslint-plugin-prettier` are you using?**
`"eslint-plugin-prettier": "^3.0.1",`
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.eslintrc.js
```
module.exports = {
  env: {
    es6: true,
    node: true,
    jest: true,
    jasmine: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:node/recommended',
    'plugin:promise/recommended',
  ],
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module',
    ecmaFeatures: {},
  },
  plugins: ['import', 'node', 'prettier', 'promise'],
  rules: {
    'import/order': [
      2,
      {
        groups: [
          ['builtin', 'external'],
          ['internal', 'parent', 'sibling', 'index'],
        ],
        'newlines-between': 'always',
      },
    ],
    'import/newline-after-import': [2],
    'linebreak-style': ['error', 'unix'],
    'no-console': 'off',
    'prettier/prettier': [
      'error',
      {
        arrowParens: 'always',
        bracketSpacing: true,
        jsxBracketSameLine: false,
        parser: 'babel',
        printWidth: 80,
        semi: true,
        singleQuote: true,
        trailingComma: 'all',
      },
    ],
    semi: ['error', 'always'],
  },
};
```

.prettierrc.js
```
module.exports = {
  // Fit code within this line limit
  printWidth: 80,

  // If true, will use single instead of double quotes
  singleQuote: true,

  // Controls the printing of trailing commas wherever possible.
  //
  // Valid options:
  //
  // "none" - No trailing commas
  // "es5"  - Trailing commas where valid in ES5 (objects, arrays, etc)
  // "all"  - Trailing commas wherever possible (function arguments)
  trailingComma: 'all',

  // Controls the printing of spaces inside array and objects
  bracketSpacing: true,

  // If true, puts the `>` of a multi-line jsx element at the end of
  // the last line instead of being alone on the next line
  jsxBracketSameLine: false,

  // Which parser to use. Valid options are "flow", "babylon",
  // "typescript" and "postcss".
  //
  // If CSS or TypeScript is detected in Sublime Text, the parser option
  // will always be internally overridden and set to "postcss" or
  // "typescript" respectively.
  parser: 'babel',

  // Whether to add a semicolon at the end of every line (semi: true), or
  // only at the beginning of lines that may introduce
  // ASI failures (semi: false)
  semi: true,
  arrowParens: 'always',
};
```
**What source code are you linting?**
```
function foo() {
  return [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `How would you rate your ability to assess a candidate's ${
          SKILLSET_TYPES[type]
        }?`,
      },
    },
  ]
}
```
![image](https://user-images.githubusercontent.com/2908721/79179147-fb3f7480-7dd4-11ea-8387-33400ab9cd19.png)

**What did you expect to happen?**
Prettier's formatting is correct. It's breaking the template literal at the variable when it hits the `printWidth: 80`.

I expected eslint to do the same and not give me an error.

**What actually happened?**
I got an eslint error:
```
   98:74  error  Replace `⏎··········SKILLSET_TYPES[type]⏎········` with `SKILLSET_TYPES[type]`  prettier/prettier
```

Telling me to remove the newlines.

I can't seem to find a configuration option to change this.

**Comment by ChucKN0risK** [comment]
I also have this issue :/

**Comment by TimRChen** [comment]
I have this issue. too.

**Comment by lydell** [comment]
This is how Prettier formats that piece of code:

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++ATnDOvbQNo113W1d0wBPAA5wk+AOQBnONjxRxAGk5988AB4wxPFV0Eix4gLb0A1gBMA7vKW8d6zfgAGACQgX8FiOgA2Z-AK8GAEN4fy96fCCAIxxvHEFVCEjJaRTI-DAgqDMcMxC4KXwAEm0dLgBlAGkASQAZWvKAUQAVAH1mgE0ABUbytj04AF1lHQBfAH5HGzHprlHZ4ahRkAUQCCFcaElkUCD6ejcuvYRtlCDvCyCBbdWo+iCwEyZyoQecKABzZBh6dDhVgAWMEM3gA6gD4nBJK8wHByid4jgAG7xATIcApFYgd7SegwLr3D6GILIVDnaSrABWkjUACF7o9nkFDHBau84KTyf8QNS1OV3h9vHAAIroCDwTneCkgV70XHoqLRODeLFCejvGCg3IwAHIAAcAAZVmqINJQfchOi1VC4PQkRzVgBHMXwAnrU4gIKSAC0UDgcDMAaxjGdOEYBKCRJJSDJUu50kMOG+v3jAqFovFHJjXNWMGiWrMOuQACZc-dYgKAMIQQzE9FQgCsWPQ0ma0VOselSL+1WyCBg5TA6o2AEFsuVBELJdJRqMgA)
```sh
--parser babel
```

**Input:**
```jsx
function foo() {
  return [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `How would you rate your ability to assess a candidate's ${
          SKILLSET_TYPES[type]
        }?`,
      },
    },
  ]
}
```

**Output:**
```jsx
function foo() {
  return [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `How would you rate your ability to assess a candidate's ${SKILLSET_TYPES[type]}?`,
      },
    },
  ];
}

```

There’s nothing eslint-plugin-prettier can do about that. eslint-plugin-prettier is basically just some glue code between ESLint and Prettier.
