### ISSUE TITLE
Node must be provided when reporting error if location is not provided

### ISSUE THREAD

**Issue by CalebDelbridge** [prettier/eslint-plugin-prettier#306]
This happens on random and most of the times the error is not current it also happens top pop up when I'm just typing code

Full-stack error
```
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:98:9)
    at /usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:311:9
    at Object.report (/usr/local/lib/node_modules/eslint/lib/linter/linter.js:917:41)
    at Program (/Users/Caleb/Desktop/Barnabus-development/main-bot/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:265:23)
    at /usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```
All my dev dependencies 
```
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.0.5"
```

**Comment by CalebDelbridge** [comment]
Yo this crap is still broken and messing with my workflow

**Comment by iamchathu** [comment]
@CalebDelbridge I'm also having this. What was the fix you have done?

**Comment by CalebDelbridge** [comment]
In all honesty, I'm not sure. Try restarting vscode, deleting node_modules, reinstalling the dependencies, and checking your config. These are all the things that I think I did, and it resolved itself. Best of luck mate

**Comment by basyusuf** [comment]
Has anyone found any solution? I am having this problem with files containing enum type

**Comment by ChenReuven** [comment]
me also, with enum

**Comment by tcamaraCS** [comment]
In my case, I was making use of **typescript-eslint** and this solved my issue: [no-unused-vars override](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md)

Detailed info here: [https://github.com/typescript-eslint/typescript-eslint/issues/2486](https://github.com/typescript-eslint/typescript-eslint/issues/2486
)

**Comment by basyusuf** [comment]
Hi @tcamaraCS , thank you 🎉  it solved my problem too but does not change the fact that it is a **bug** 😎

**Comment by Dwn96** [comment]
Currently experiencing this. Has anyone found a fix?

**Comment by antonfrolovsky** [comment]
@Dwn96 https://github.com/prettier/eslint-plugin-prettier/issues/306#issuecomment-783397862

**Comment by SergeyKazarinov** [comment]
I had a similar problem. Instead of redefining the rules. I corrected the cause in enum.

BEFORE
```
export enum CurrencyEnum {
  'RUB' = 'RUB',
  'EUR' = 'EUR',
  'USD' = 'USD',
}
```
AFTER
```
export enum CurrencyEnum {
  RUB = 'RUB',
  EUR = 'EUR',
  USD = 'USD',
}
```
After changing the enum the error is gone

**Comment by denis88k** [comment]
> I had a similar problem. Instead of redefining the rules. I corrected the cause in enum.
> 
> BEFORE
> 
> ```
> export enum CurrencyEnum {
>   'RUB' = 'RUB',
>   'EUR' = 'EUR',
>   'USD' = 'USD',
> }
> ```
> 
> AFTER
> 
> ```
> export enum CurrencyEnum {
>   RUB = 'RUB',
>   EUR = 'EUR',
>   USD = 'USD',
> }
> ```
> 
> After changing the enum the error is gone

the fixes helped me too. thank you!)))
мне тоже помогли соответствующие исправления. Спасибо, Сергей!

**Comment by heyakyra** [comment]
this doesn't help if the quotations are not redundant (names with dashes or whitespace, etc)

@Jaxenormus why was this closed?

**Comment by JounQin** [comment]
Please don't comment on old issues, intead, you should create a new issue with runnable reproduction if you're still facing the issue.
