### ISSUE TITLE
conflict react/jsx-indent and prettier

### ISSUE THREAD

**Issue by alikazemkhanloo** [prettier/eslint-plugin-prettier#308]
**What version of `eslint` are you using?**
7.2
**What version of `prettier` are you using?**
2.0.5
**What version of `eslint-plugin-prettier` are you using?**
6.11.0
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```JavaScript
module.exports = {
  env: {
    es2020: true,
  },
  extends: [
    "prettier",
    "plugin:react/recommended",
    "airbnb",
    "plugin:prettier/recommended",
  ],
  parser: "babel-eslint",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 11,
    sourceType: "module",
  },
  plugins: ["react", "prettier"],
  rules: {
    "prettier/prettier": "error",
    "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx"] }],
    "react/react-in-jsx-scope": [0],
  },
};

```
**What source code are you linting?**
```Javascript
const DrawerItem = (props:Props) => {
  const { text, icon, route } = props;
  const classes = useStyles();
  const router = useRouter();

  const goto = (target) => {
    router.push(target);
  };
  const selected = router.pathname === route;
  return (
      <ListItem button key={text} selected={selected} classes={{ root: classes.listItem }} onClick={() => goto(route)}>
      <ListItemIcon className={selected ? classes.itemSelectedText : classes.itemText}>{icon}</ListItemIcon>
      <ListItemText primary={text} className={selected ? classes.itemSelectedText : classes.itemText} />
    </ListItem>
  );
};

export default DrawerItem;

```
**What did you expect to happen?**
it should not break the code while formatting

**What actually happened?**
the gif below explains everything. when `jsx-indent` and `prettier` rules apply at the same time, the `>` character at the end of the tag will be removed.

![out](https://user-images.githubusercontent.com/25160928/85378658-14d90700-b550-11ea-8010-b80a6cb34177.gif)

**Comment by lydell** [comment]
Hi! Looks like you forgot to add `prettier/react` to `extends`:

```
  extends: [
    "plugin:react/recommended",
    "airbnb",
    "plugin:prettier/recommended",
    "prettier/react"
  ],
```

I removed `"prettier"` since it’s part of `"plugin:prettier/recommended"`.

You might also be able to remove `"plugin:react/recommended"` since airbnb configures react?

**Comment by alikazemkhanloo** [comment]
Hi @lydell, adding `'prettier/react'` did not solve the issue.

 I don't think I need to add anything extra to `package.json` for `'prettier/react'`, do I?

**Comment by lydell** [comment]
> I don't think I need to add anything extra to package.json for 'prettier/react', do I?

That’s right, installing `eslint-config-prettier` is all you need.

You can run `npx eslint --print-config path/to/main.js | npx eslint-config-prettier-check` to find conflicting rules. https://github.com/prettier/eslint-config-prettier#cli-helper-tool
