### ISSUE TITLE
Support ESLint 4

### ISSUE THREAD

**Issue by prayerslayer** [prettier/eslint-plugin-prettier#31]
ESLint is now available in version 4, [here](http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0#breaking-changes-for-plugincustom-rule-developers) are the breaking changes for plugin developers.

I don't know if there is actually something to do here aside from bumping the peerDependency semver :)

**Comment by not-an-aardvark** [comment]
Actually, this already happened in https://github.com/prettier/eslint-plugin-prettier/pull/30, but it hasn't been released yet.

**Comment by not-an-aardvark** [comment]
Published to npm as 2.1.2.

**Comment by prayerslayer** [comment]
Cool, thanks for the super-fast response!
