### ISSUE TITLE
Ordering of plugin and eslint-config-prettier exclusion rule sets in extends array

### ISSUE THREAD

**Issue by mnaamani** [prettier/eslint-plugin-prettier#314]
In the README the example shown lists the plugin before the exclusion rule sets:

```json
{
  "extends": [
    "plugin:prettier/recommended",
    "prettier/flowtype",
    "prettier/react",
    "prettier/standard"
  ]
}
```

Is the order important, or is this equivalent?

```json
{
  "extends": [
    "prettier/flowtype",
    "prettier/react",
    "prettier/standard"
    "plugin:prettier/recommended"
  ]
}
```

**Comment by BPScott** [comment]
ESLint extends apply in order, so any rules in an earlier ruleset will be overwritten by rules in a later ruleset.

Consider two rulesets: A enables rule "checkThing", while ruleset B disables "checkThing".

- ` "extends": [ 'A', 'B']` will result in the rule being disabled
- ` "extends": [ 'B', 'A']` will result in the rule being enabled


So the order does matter when rulesets define the same rule. However I expect that there are no overlapping rules between "plugin:prettier/recommended" and the prettier/* rulesets so functionally it probably doesn't matter.

If you're curious you can use eslint's [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#print-config) option to inspect the rules that get enabled depending on the ordering of your rulesets
