### ISSUE TITLE
Plug-in assuming usePrettierrc to be true if not configured

### ISSUE THREAD

**Issue by jwoodhull** [prettier/eslint-plugin-prettier#319]
**What version of `eslint` are you using?**
v7.4.0

**What version of `prettier` are you using?**
2.0.5

**What version of `eslint-plugin-prettier` are you using?**
3.1.4

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
From  eslint config

        'prettier/prettier': [
            'error',
            {
                singleQuote: true,
                tabWidth: 4,
                printWidth: 120,
                arrowParens: 'avoid',
            }
        ],

**What source code are you linting?**
Any ts file

**What did you expect to happen?**
Linting to run

**What actually happened?**
Error: Cannot find module 'node_modules' from '/Users/jwoodhul'
Occurred while linting /Path/To/File

I traced the issue down to this line:
https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L147

There is an assumption that if 
```
{
  usePrettierrc: true/false
}
```
is not in the rule configuration, then a config file should be present.  This is assumed even if Prettier configuration is provided in the rule config.   If this assumption is correct, then a better error would indicate that ```usePrettierrc``` should be false if no config file will be provided.

**Comment by BPScott** [comment]
I'm unclear how that option would result in an `Error: Cannot find module 'node_modules' from '/Users/jwoodhul'` message.  Are you able to provide a reproduction repository? That error would suggest you haven't got a node_modules folder and thus no copy of prettier available to run at all, which feels like a more fundamental problem than if prettier should search for a config file, as even if you had a config file everything would end up breaking as it shouldn't be able to find the prettier command to run.

--- 

https://github.com/prettier/eslint-plugin-prettier#options states "`usePrettierrc`: Enables loading of the Prettier configuration file, (default: true).". So this behaviour is already documented.

**Comment by jwoodhull** [comment]
The error is thrown here: https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L173

It looks like the code is looking for a .prettierrc file and it will keep lookup until it hit the home directory.  Then it will throw.  

If you PrettierRc is the default, then I'm mostly looking for better error handling as the message does not indicate the problem the a config file is required or should be turned off.  

I would contend that a better user experience would check if a developer had provided configuration and use that as an indication that a .prettierrc file should not be required.

**Comment by JounQin** [comment]
close as https://github.com/prettier/eslint-plugin-prettier/issues/319#issuecomment-668863065 described
