### ISSUE TITLE
Vue style attribute ; error

### ISSUE THREAD

**Issue by thefoxie** [prettier/eslint-plugin-prettier#331]
**What version of `eslint` are you using?**
"eslint": "7.7.0"
**What version of `prettier` are you using?**
"prettier": "2.1.1"
**What version of `eslint-plugin-prettier` are you using?**
"eslint-plugin-prettier": "3.1.4"
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
*.prettierrc*
```js
{
    "tabWidth": 4,
    "trailingComma": "es5",
    "semi": true,
    "arrowParens": "always",
    "singleQuote": false
}

```
*.eslintrc.json*
```js
{
    "root": true,
    "env": {
        "browser": true
    },
    "extends": [
        "plugin:vue/vue3-recommended",
        "eslint:recommended",
        "prettier/vue",
        "plugin:prettier/recommended"
    ],
    "rules": {
        "vue/component-name-in-template-casing": ["error", "PascalCase"]
    }
}

```
**What source code are you linting?**
```vue
<div class="column" style="height: 500px;">
...
</div>
```
**What did you expect to happen?**
No errors.
**What actually happened?**
```error  Delete `;`  prettier/prettier```
Everything worked in "prettier": "2.0.5"

**Comment by BPScott** [comment]
This is an intentional change in Prettier per according to [the 2.1 release blog post](https://prettier.io/blog/2020/08/24/2.1.0.html#omit-trailing-semicolon-on-single-line-style-attributes-8013httpsgithubcomprettierprettierpull8013-by-bschlenkhttpsgithubcombschlenk)

If you think this shouldn't be the case then please raise an issue on the [prettier](https://github.com/prettier/prettier) repo

**Comment by thefoxie** [comment]
Yes, but it's actually eslint-plugin-prettier which tells me to insert the semicolon (and adds it on save). The plugin doesn't follow the prettier rule I guess.

**Comment by bdrtsky** [comment]
I have same issue. This shouldn't be closed.

**Comment by bdrtsky** [comment]
@thefoxie ok, so you need to update Prettier to fix this issue 🙌

**Comment by thefoxie** [comment]
@bdrtsky I updated it but still got the issue. One wants me to keep it, the other one wants to delete it. Is it some config related issue:

**Comment by thefoxie** [comment]
![image](https://user-images.githubusercontent.com/15309350/93101196-47efea00-f6aa-11ea-99ed-35ce5ff9cf92.png)

**Comment by thefoxie** [comment]
Reloaded vscode and it works. Tried this before without success 🤷
