### ISSUE TITLE
Where do `prettier/prettier` errors come from?

### ISSUE THREAD

**Issue by hirikarate** [prettier/eslint-plugin-prettier#334]
I am having a lot of (hunreds) `prettier/prettier` error:
```
warning  Replace `,` with `;`  prettier/prettier
```

I'm confused that prettier doesn't prioritize my custom rules. I'm wondering where these kinds of rules are defined in `eslint-plugin-prettier` source code? I want to see how they are defined, and want to override them but don't know the rule name.

My `.eslintrc.js` is:

```javascript
module.exports = {
  env: {
    node: true,
    commonjs: true,
    mocha: true,
  },
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    sourceType: "module",
  },
  plugins: [
    "@typescript-eslint",
    "prettier",
  ],
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended", 
  ],
  rules: {
    "@typescript-eslint/brace-style": [
      "error",
      "1tbs",
      { allowSingleLine: true },
    ],
    "@typescript-eslint/member-delimiter-style": [
      "error",
      {
        multiline: {
          delimiter: "comma",
          requireLast: true,
        },
        singleline: {
          delimiter: "comma",
          requireLast: false,
        },
        overrides: {
          interface: {
            multiline: {
              delimiter: 'semi',
              requireLast: true,
            },
          },
        },
      },
    ],
    'prettier/prettier': 'warn'
  },
};

```

I used VS Code fix-on-save feature, with this setting:

```json
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
},
```

This is the code with prettier/prettier error. After VS Code changed all semi to colons (which is expected because I configured so), running `eslint --fix` yields above errors, telling me to replace `,` with `;`.

```typescript
type LambdaEventType = APIGatewayLambdaEvent & {
  headers: {
    token: string,
  },
  body: {
    propOne: string,
    propTwo: string,
    propThree: number,
  },
};
```

Thank you!

**Comment by BPScott** [comment]
> I'm wondering where these kinds of rules are defined in eslint-plugin-prettier source code?

Only one rule - `prettier/prettier` is defined in this plugin, which just passes code through Prettier. this plugin doesn't have any opinions about formatting itself it just does what prettier says.

The whole point of prettier is that [it wants to be opinionated](https://prettier.io/docs/en/option-philosophy.html). The [integrating with linters](https://prettier.io/docs/en/integrating-with-linters.html) docs explain that you should turn off any rules that conflict with prettier by using [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier).

If you  feel strongly about not  following prettier's suggestions and instead want to override them, then you should run prettier over your files, then run eslint over them by using [`prettier-eslint`](https://github.com/prettier/prettier-eslint).
