### ISSUE TITLE
Definition for rule `prettier/prettier` was not found

### ISSUE THREAD

**Issue by dy** [prettier/eslint-plugin-prettier#343]
Standard create-react-app setup with `.eslintrc` at the root.

```
Failed to compile.
Line 1:1: Definition for rule 'prettier/prettier' was not found prettier/prettier
```

**What version of `eslint` are you using?**
6.8.0

**What version of `prettier` are you using?**
1.19.1

**What version of `eslint-plugin-prettier` are you using?**
3.1.4

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
`.eslintrc`
```json
{
  "plugins": ["prettier"],
  "extends": ["react-app", "airbnb", "plugin:prettier/recommended","prettier/react"],
  "rules": { "react/jsx-props-no-spreading": "off", "react/require-default-props": "off", "react/forbid-prop-types": "off" , "prettier/prettier": "warn" }
}
```

**What source code are you linting?**

```js
/* eslint-disable prettier/prettier */
```

**What did you expect to happen?**

Not to break whole project compilation.

**What actually happened?**

Project compilation broke.

Followed #323, #107, #20 - nothing worked.

**Comment by Relaxe111** [comment]
I have same problem but if `// eslint-disable-next-line prettier/prettier`

**Comment by JMaio** [comment]
Having the same issue, it works fine within VSCode but React throws a compile error. 
A possible workaround is to just disable `eslint` altogether if disabling for a single line:
```
// eslint-disable-next-line
```

**Comment by mehran-m** [comment]
If you have configured your eslintrc correctly and your editor still shows the error, try to restart your editor.
I closed my VSCode and opened it again, all the previous errors were gone.

Also refer to this post for configuration: https://github.com/prettier/eslint-plugin-prettier/issues/20#issuecomment-300981249

**Comment by JounQin** [comment]
This issue seems stale, feel free to create a new one with reproduction, thanks.
