### ISSUE TITLE
Can anyone explain how eslint and prettier must work together?

### ISSUE THREAD

**Issue by inikonorov** [prettier/eslint-plugin-prettier#362]
I added ESLint by docs and get this config (after `npx eslint init`)

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "plugin:react/recommended",
        "airbnb",
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    }
}
```

now I wanna add prettier - I found in docs that I need to install `eslint-config-prettier` to disable eslint formatting rules.

so extends part of eslint config will be:
```
"plugin:react/recommended",
"airbnb",
"prettier"
```
is it right?

this config will override eslint formatting rules, so I must add other plugin, that gives me formatting rules - this plugin is `eslint-plugin-prettier`

and my config will be:

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "plugin:react/recommended",
        "airbnb",
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error"
    }
}
```

am I right? I'm stuck because of different config examples in `eslint-config-prettier`, `eslint-plugin-prettier` and `eslint`

**Comment by lydell** [comment]
The extends part should like like this:

```json
{
  "extends": [
    "airbnb",
    "airbnb/hooks",
    "plugin:prettier/recommended",
    "prettier/react"
  ]
}
```

You can remove `"plugins"` and `"rules"` completely.
