### ISSUE TITLE
Parsing error when using typescript template literals

### ISSUE THREAD

**Issue by gax97** [prettier/eslint-plugin-prettier#372]
**What version of `eslint` are you using?**
7.16.0
**What version of `prettier` are you using?**
2.2.1
**What version of `eslint-plugin-prettier` are you using?**
3.3.0

**What did you expect to happen?**
I expect no errors.
**What actually happened?**
I got this error on template literal type
ESLint: Parsing error: Type expected.(prettier/prettier)
The actual type that causes the error: 
export type SortOption = \`${SortFields}:${SortDirection}\`;

**Comment by kotoyama** [comment]
Hi. If it is still actual, check your TS version. [It should be 4.1](https://prettier.io/blog/2020/11/20/2.2.0.html#template-literal-typeshttpsdevblogsmicrosoftcomtypescriptannouncing-typescript-4-1template-literal-types)

**Comment by jmls** [comment]
I have typescript 4.3.5, but have the same problem

**Comment by seyaobey-dev** [comment]
Same issue here with version `4.4.2`

**Comment by BPScott** [comment]
Support for template literal types was [added to Prettier in v2.2.0](https://prettier.io/blog/2020/11/20/2.2.0.html#typescript. Make sure you're using that at least that version of prettier.
