### ISSUE TITLE
how to disable Delete `··⏎··`eslintprettier/prettier

### ISSUE THREAD

**Issue by mhdalmajid** [prettier/eslint-plugin-prettier#389]
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```javascript

{
  "env": {
    "browser": true,
    "commonjs": true,
    "es2021": true,
    "node": true
  },
  "extends": ["airbnb-base", "prettier", "plugin:prettier/recommended"],
  "parserOptions": {
    "ecmaVersion": 12
  },
  "globals": {
    "ROOTURL": true,
    "db": true
  },
  "rules": {
    "no-console": 0,
    "no-shadow": 0,
    "no-unused-vars": 0,
    "semi": [2, "never"],
    "comma-dangle": [0, "always-multiline"],
    "padded-blocks": [
      2,
      { "blocks": "always", "classes": "always", "switches": "always" },
      { "allowSingleLineBlocks": true }
    ],
    "max-len": [2, { "code": 160, "ignoreUrls": true }],
    "prettier/prettier": [
      "off",
      {
        "endOfLine": "auto",
        "tabWidth": 2,
        "semi": false,
        "trailingComma": "es5",
        "singleQuote": true,
        "printWidth": 145
      }
    ]
  }
}

```
**What source code are you linting?**

```javascript
router.get('/', (req, res) => {
  res.send('Hello from /user/')
})
```

**What did you expect to happen?**

adding padded block first and the last line in the block

```javascript
router.get('/', (req, res) => {

  res.send('Hello from /user/')

})
```

**What actually happened?**

conflict 
--------
`Delete `··⏎··`eslintprettier/prettier`
vs
`Block must be padded by blank lines.eslint(padded-blocks)`

**Comment by lydell** [comment]
Hi!

First – this plugin is just a smaller wrapper around [Prettier](https://github.com/prettier/prettier). So this plugin does not control the formatting in any way, it’s just running Prettier for you.

Prettier does not support that code style. Functions never start or end with blank lines. If that’s not something you can live with, Prettier won’t be the tool you’re looking for.

**Comment by mhdalmajid** [comment]
thanks @lydell 
I love prettier , I thought there is a way to disable this complain by this plugin.
if anyone know how to disable this specific one please share it
