### ISSUE TITLE
Integration between Eslint/Prettier does not work as expected

### ISSUE THREAD

**Issue by vicasas** [prettier/eslint-plugin-prettier#402]
**What version of `eslint` are you using?**
v7.23.0

**What version of `prettier` are you using?**
v2.2.1

**What version of `eslint-plugin-prettier` are you using?**
3.3.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```json
// .eslintrc.json
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": ["plugin:react/recommended", "airbnb", "prettier"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["react", "prettier"],
  "rules": {
    "prettier/prettier": "error",
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-props-no-spreading": "off"
  }
}
```

```json
// .prettierrc.json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true
}

```

**What source code are you linting?**
React using Next.js

**What did you expect to happen?**
That everything worked as before or as expected. It should be able to apply the configurations that are indicated in the file `.prettierrc.json` but it does not recognize them, it marks errors.

**What actually happened?**
When I configure eslint using prettier with the above configuration it does not recognize the `.prettierrc.json` file.

This is using v8 of `eslint-config-prettier`

![image](https://user-images.githubusercontent.com/57921784/112726199-ef23c880-8efa-11eb-9097-834c6fdb4135.png)

**ADITIONAL IINFORMATION**

When I make a rule change in the `.prettierrc` vscode or `eslint-plugin-prettier` in the integration with eslint it does not automatically recognize it. It only recognizes it when you load vscode, but not on the way.

**Comment by vicasas** [comment]
I close this as apparently it is a VS Code problem in reading the config file.

**Comment by robertwt7** [comment]
Hey guys, sorry so how did you fix this again?

**Comment by BPScott** [comment]
If you're making edits to the Prettier configs while VScode is open, VSCode's eslint plugin won't notice those changes until after you reload the VSCode window. You can either do this by choosing "developer: reload window" from the command palette or restarting VSCode.

**Comment by robertwt7** [comment]
Yeah sorry, apparently vs code has to be restarted every time I changed the configs. Thanks!
