### ISSUE TITLE
Extending Default Config in a Package

### ISSUE THREAD

**Issue by bozdoz** [prettier/eslint-plugin-prettier#416]
I want to share a default config which is easily overridable by a project's prettier config.

**What did you expect to happen?**

I expect to be able to configure default prettier settings in eslint, which are overridden by a project's defined prettier settings.

I see two scenarios:

1. **A project has a .prettierrc file**, and they adopt our shared eslint config: their .prettierrc file should take precedence.  If they want to adopt the shared prettier config, they can simply delete their .prettierrc file.
2. **A project does not have a .prettierrc file**, and they adopt our shared eslint config: our shared prettier config should become the new defaults.  If they want to make changes, they can simply create a .prettierrc file.

**What actually happened?**

**I can't** set ESLint prettier settings because that will override local prettier config.

**I can't _not_** set ESLint prettier settings because there appears to be no other way to distribute shared default prettier (current interim solution is to provide a shared .prettierrc file for a local .prettierrc file to extend from, but this makes for the annoying creation of a .prettierrc.js file just to require the package's .prettierrc file)

**Main Question**

Can we just alter the priority of the prettier options?

https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L223-L229
```js
const prettierOptions = Object.assign(
  {},
  initialOptions,
  prettierRcOptions,
  eslintPrettierOptions,
  { filepath }
);
```

Why aren't the prettierRcOptions and eslintPrettierOptions swapped?  Maybe the plugin could provide an option as to which options should take precedence?

**Comment by bozdoz** [comment]
How can this be achieved? Or are you saying it should not be achieved?

**Comment by JounQin** [comment]
You should always prefer `prettier` config for consistent for other tools, instead relying on this plugin.
