### ISSUE TITLE
the prettier config doesn't override the eslint config

### ISSUE THREAD

**Issue by LastStranger** [prettier/eslint-plugin-prettier#419]
**What version of `eslint` are you using?**
^7.27.0
**What version of `prettier` are you using?**
^2.3.0
**What version of `eslint-plugin-prettier` are you using?**
^3.4.0
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.prettierrc.js
```
module.exports = {
    // trailingComma: "es5",
    tabWidth: 4,
    // semi: true,
    // singleQuote: true
    arrowParens: "avoid"
}
```
.eslintrc.js
```
module.exports = {
  env: {
    browser: true,
    node: true,
    es2021: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:prettier/recommended",
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: "module",
  },
  plugins: ["react"],
  // rules: {
  //   "prettier/prettier": "error",
  // },
};
```
**What source code are you linting?**
```
const obj = {
    a: 1,
    b: 2,
    person: {
        name: "tom",
        age: 12,
    },
};
```
**What did you expect to happen?**
it should be 4 tabWith
**What actually happened?**
<img width="443" alt="截屏2021-05-31 下午6 43 29" src="https://user-images.githubusercontent.com/29811304/120181761-191da200-c240-11eb-93c7-ce1f2d87fe89.png">

**Comment by lydell** [comment]
Hi! I don’t understand:

- You have commented out the `"prettier/prettier"` rule?
- You haven’t enabled https://eslint.org/docs/rules/indent – so what ESLint config is there to override?

Please provide steps to reproduce, using only CLI and not VSCode (preferably a repo we can clone.) Thanks!
