### ISSUE TITLE
.prettierrc changes not applying automatically

### ISSUE THREAD

**Issue by Boengar** [prettier/eslint-plugin-prettier#421]
**What version of `eslint` are you using?**
7.31.0
**What version of `prettier` are you using?**
2.3.2
**What version of `eslint-plugin-prettier` are you using?**
3.4.0
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
***.prettierrc***
`
{
  "tabWidth": 4,
  "useTabs": false
}
`
***.eslintrc.js***
```
module.exports = {
    env: {
        browser: true,
        jest: true,
        node: true,
    },
    extends: [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:prettier/recommended",
    ],
    parserOptions: {
        ecmaFeatures: {
            jsx: true,
        },
        ecmaVersion: 12,
        sourceType: "module",
    },
    plugins: ["react", "prettier"],
    rules: {
        "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx"] }],
        "react/forbid-prop-types": [0, { forbid: ["any"] }],
        "react/prop-types": [
            "off",
            { ignore: "ignore", customValidators: "customValidator" },
        ],
    },
};
```

**What did you expect to happen?**
After editing the prettierrc file and modifying the rules the changes should immediately show in the file that's linted.
**What actually happened?**
The file was linted with the previous rules of the prettierrc file, it seems the rules are cached somewhere. Only after restarting VS Code or with the VS Code command "ESLint: Restart ESLint Server" the changes will apply.

This issue was also mentioned at the of the thread in this ticket: #103

**Comment by BPScott** [comment]
This is deliberate, as flushing the prettier config cache on every run means the plugin is very slow. I consider the speed up from persisting the config cache to be worth the inconvenience of occasional stale caches if you change your prettierrc file in editors that use long-running eslint processes. https://github.com/prettier/eslint-plugin-prettier/pull/368

As you hav discovered, if you update your prettierrc file then you will need to run the `ESLint: Restart ESLint Server` command in VScode.

**Comment by Boengar** [comment]
@BPScott 
Good to know, it would be great if you can at least put that point in the beginning of the README.
Also maybe as logs when running eslint with the verbose option, if that's possible.
So at least some people can read over it, before searching for possible issues, since that point is not very obvious.

**Comment by Joebayld** [comment]
This caught me off guard as well as it wasn't obvious I needed to restart the ESLint server. 

I have the prettier VSCode extension installed - I wonder if it would be possible to have the extension implement a watch file for whenever the config changes and restart the server automatically?
