### ISSUE TITLE
deploying vercel "Failed to compile"

### ISSUE THREAD

**Issue by Psychep** [prettier/eslint-plugin-prettier#422]
**What version of `eslint` are you using?**
    "eslint": "^7.31.0",

**What version of `prettier` are you using?**
    "prettier": "^2.3.2",

**What version of `eslint-plugin-prettier` are you using?**
    "eslint-plugin-prettier": "^3.4.0",

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.eslintrc;
module.exports = {
  root: true,
  env: {
    browser: true,
    amd: true,
    node: true,
  },
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  settings: {
    react: {
      version: "detect",
    },
  },
  extends: [
    "next",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:prettier/recommended",
    "eslint:recommended", "next",
  ],
  plugins: ["simple-import-sort"],
  rules: {
    "react/no-unescaped-entities": "off",
    "@next/next/no-page-custom-font": "off",
    "prettier/prettier": ["error", {}, { usePrettierrc: true }],
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "@typescript-eslint/no-unused-vars": ["error"],
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    // eslint-disable-next-line no-dupe-keys
    "react/no-unescaped-entities": "off",
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-namespace": "off",
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx"],
      parser: "@typescript-eslint/parser",
    },
  ],
};

.prettierrc
{
  "semi": true,
  "tabWidth": 2,
  "printWidth": 100,
  "singleQuote": false,
  "trailingComma": "all",
  "jsxBracketSameLine": true,
  "endOfLine": "auto"
}

![image](https://user-images.githubusercontent.com/42694514/127312549-5562dcd1-da4f-4df1-a2cc-75e24236aba4.png)

**Comment by BPScott** [comment]
Your prettierrc contains `"singleQuote": false` which means it wants use double quotes and it's showing linting errors that say you need to change single quotes to double quotes and adjust indentation.

This appears to be raising linting errors correctly based on your configuration, you just need to go and fix them with `eslint's  `--fix` parameter.
