### ISSUE TITLE
error Delete

### ISSUE THREAD

**Issue by RiCoTeRoX** [prettier/eslint-plugin-prettier#43]
i get 
<img width="422" alt="screen shot 2017-08-13 at 4 48 53 pm" src="https://user-images.githubusercontent.com/4624115/29252950-a182a49a-8047-11e7-82b0-fa6c579168fc.png">

.eslintrc

`{
  "extends": ["airbnb", "prettier"],
  "env": {
    "browser": true,
    "node": true
  },
  "globals": {
    "test": true,
    "expect": true,
    "describe": true,
    "FB": true
  },
  "parser": "babel-eslint",
  "plugins": [
    "react",
    "prettier"
  ],
  "parserOptions": {
    "ecmaVersion": 5,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "prettier/prettier": ["error", {
      "singleQuote": true
    }],
    "react/jsx-no-bind": 1,
    "strict": 2,
    "max-len": ["error", 250],
    "space-before-function-paren": ["error", { "anonymous": "always" }],
    "comma-dangle": [1, "never"],
    "import/no-extraneous-dependencies": ["error", { "devDependencies": true }],
    "react/forbid-prop-types": [0],
    "react/jsx-filename-extension": [1, { "extensions": [".js",".jsx"] }],
    "no-param-reassign": ["error", { "props": false }],
    "quotes": [2, "single"]
  }
}`

.babelrc
`{
  "presets": [
    "es2015",
    "react",
    "stage-3",
    "stage-2"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-object-assign",
    "transform-flow-strip-types",
    "syntax-dynamic-import"
  ],
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}`

.editorConfig
`root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
in_empty_tag = true
`
i use webstorm file watcher

`--single-quote --write $FilePath$`

**Comment by not-an-aardvark** [comment]
Thanks for the report. This error is occurring because you have a space between `componentDidMount` and the `(` after it, which goes against `prettier` formatting. If you remove the space, the issue will be resolved.
