### ISSUE TITLE
context.getPhysicalFilename is not a function

### ISSUE THREAD

**Issue by CharlesStover** [prettier/eslint-plugin-prettier#434]
`eslint-plugin-prettier@4.0.0` is not compatible with `eslint@7.11.0` and requires an upgrade to `eslint@7.32.0`. This is particularly relevant as `react-scripts` relies on `eslint@7.11.0`.

**What version of `eslint` are you using?** 7.11.0, 7.32.0

**What version of `prettier` are you using?** 2.3.2

**What version of `eslint-plugin-prettier` are you using?** 4.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

* https://github.com/CharlesStover/charlesstover.com/blob/1fef52f3616173c81d8b6e95f55cb817bd055ca1/.eslintrc.json
* https://github.com/CharlesStover/charlesstover.com/blob/1fef52f3616173c81d8b6e95f55cb817bd055ca1/.prettierrc.json

**What source code are you linting?**

https://github.com/CharlesStover/charlesstover.com/

**What did you expect to happen?**

Success.

**What actually happened?**

https://github.com/CharlesStover/charlesstover.com/runs/3511215999?check_suite_focus=true

```
Run yarn build
Creating an optimized production build...
Failed to compile.

Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
Occurred while linting /home/runner/work/charlesstover.com/charlesstover.com/src/index.tsx

Error: Process completed with exit code 1.
```

However, you can see from the [eslint step](https://github.com/CharlesStover/charlesstover.com/runs/3511213631?check_suite_focus=true) that running `eslint` succeeds. The only two differences between these two steps is the version of ESLint being run.

By upgrading `react-scripts`'s `eslint` version with `yarn up -R eslint`, this error is resolved.

I'm opening this issue for two reasons:

1) Anyone also encountering this error has an easily-googleable solution that does not otherwise exist at time of posting. To re-iterate, that solution is `yarn up -R eslint`.
2) The documentation should probably mention this, just based on the popularity of `react-scripts`. 🙂

I noticed this package lists the correct semvar in peer dependencies, but there are no warning or errors about versioning in the logs (see: GitHub workflow links above).

**Comment by romantech** [comment]
I had the same problem. After Deleting Node_Modules, package.json, and reinstall dependency, then work fine.

**Comment by romantech** [comment]
> `eslint-plugin-prettier@4.0.0` is not compatible with `eslint@7.11.0` and requires an upgrade to `eslint@7.32.0`. This is particularly relevant as `react-scripts` relies on `eslint@7.11.0`.
> 
> **What version of `eslint` are you using?** 7.11.0, 7.32.0
> 
> **What version of `prettier` are you using?** 2.3.2
> 
> **What version of `eslint-plugin-prettier` are you using?** 4.0.0
> 
> **Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
> 
> * https://github.com/CharlesStover/charlesstover.com/blob/1fef52f3616173c81d8b6e95f55cb817bd055ca1/.eslintrc.json
> * https://github.com/CharlesStover/charlesstover.com/blob/1fef52f3616173c81d8b6e95f55cb817bd055ca1/.prettierrc.json
> 
> **What source code are you linting?**
> 
> https://github.com/CharlesStover/charlesstover.com/
> 
> **What did you expect to happen?**
> 
> Success.
> 
> **What actually happened?**
> 
> https://github.com/CharlesStover/charlesstover.com/runs/3511215999?check_suite_focus=true
> 
> ```
> Run yarn build
> Creating an optimized production build...
> Failed to compile.
> 
> Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
> Occurred while linting /home/runner/work/charlesstover.com/charlesstover.com/src/index.tsx
> 
> Error: Process completed with exit code 1.
> ```
> 
> However, you can see from the [eslint step](https://github.com/CharlesStover/charlesstover.com/runs/3511213631?check_suite_focus=true) that running `eslint` succeeds. The only two differences between these two steps is the version of ESLint being run.
> 
> By upgrading `react-scripts`'s `eslint` version with `yarn up -R eslint`, this error is resolved.
> 
> I'm opening this issue for two reasons:
> 
> 1. Anyone also encountering this error has an easily-googleable solution that does not otherwise exist at time of posting. To re-iterate, that solution is `yarn up -R eslint`.
> 2. The documentation should probably mention this, just based on the popularity of `react-scripts`. 🙂
> 
> I noticed this package lists the correct semvar in peer dependencies, but there are no warning or errors about versioning in the logs (see: GitHub workflow links above).

I had same problem. After Deeleting Node_Modules, package.json and reinstall dependency, then work fine.

**Comment by user12043** [comment]
Same problem here.
Solved by `yarn upgrade -R eslint` as you mentioned. Thank you!

**Comment by johannesnagl** [comment]
super helpful!

**Comment by BPScott** [comment]
As first line of the [CHANGELOG entry for v4.0.0](https://github.com/prettier/eslint-plugin-prettier/blob/master/CHANGELOG.md#v400-2021-08-30) states:

> This breaking change drops support for old versions of ESLint, Prettier and Node. You must use at least ESLint v7.28.0, 
Prettier v2.0.0 and Node v12.0.0. Aside from that, usage of this plugin remains identical.

Because the [peer-dependency](https://github.com/prettier/eslint-plugin-prettier/blob/a3d6a2259cbda7b2b4a843b6d641b298f03de5ad/package.json#L34) is also set as to v7.28.0 you probably got n warning when you ran your yarn / npm install that stated that the eslint version you have installed does not match what was required by peer dependencies.

---

> This is particularly relevant as react-scripts relies on eslint@7.11.0.

react-scripts relies on `eslint@^7.11.0` according to [your own yarn.lock](https://github.com/CharlesStover/charlesstover.com/blob/1fef52f3616173c81d8b6e95f55cb817bd055ca1/yarn.lock#L18680
). That means any fresh installs of react-scripts will pick up newer versions of eslint, so this isn't an issue for new users. It only affects people that have an existing install of an older eslint version, and telling people how to their dependency manager isn't the scope of this project.

**Comment by CharlesStover** [comment]
>As first line of the CHANGELOG entry for v4.0.0 states:

Users who have ESLint >=7.28 installed can still encounter this error when using other dependencies that depend on ESLint. My suggestion was for the documentation to address how to resolve this error, which the CHANGELOG neither does nor is it easily accessible, versus the README or an FAQ.

>Because the peer-dependency is also set as to v7.28.0 you probably got n warning when you ran your yarn / npm install that stated that the eslint version you have installed does not match what was required by peer dependencies.

There in fact is not a warning, because I have both versions of ESLint installed. That is the point of this issue. It is quite possible for users to have both installed and get no warnings. They only get cryptic errors which do not tell how to resolve the issue.

>react-scripts relies on eslint@^7.11.0 according to your own yarn.lock. That means any fresh installs of react-scripts will pick up newer versions of eslint, so this isn't an issue for new users.

Correct.

>It only affects people that have an existing install of an older eslint version, and telling people how to their dependency manager isn't the scope of this project.

I feel like unblocking users who encounter common errors is within scope. "I installed `react-scripts` before late 2021" probably represents >90% of React users. I'm not saying it's this project's responsibility to fix the error. I'm saying it's this project's responsibility to help users onboard. The root cause and solution were outlined in the OP. It's minimal effort to point to it as a debug step.

Nonetheless, my intention was for it to become Google-able, as there were _zero_ results for this error previously. Hopefully that goal is still met, even if the project doesn't formally support the unblocking process. 👍

**Comment by Aashimalik** [comment]
> > As first line of the CHANGELOG entry for v4.0.0 states:
> 
> Users who have ESLint >=7.28 installed can still encounter this error when using other dependencies that depend on ESLint. My suggestion was for the documentation to address how to resolve this error, which the CHANGELOG neither does nor is it easily accessible, versus the README or an FAQ.
> 
> > Because the peer-dependency is also set as to v7.28.0 you probably got n warning when you ran your yarn / npm install that stated that the eslint version you have installed does not match what was required by peer dependencies.
> 
> There in fact is not a warning, because I have both versions of ESLint installed. That is the point of this issue. It is quite possible for users to have both installed and get no warnings. They only get cryptic errors which do not tell how to resolve the issue.
> 
> > react-scripts relies on eslint@^7.11.0 according to your own yarn.lock. That means any fresh installs of react-scripts will pick up newer versions of eslint, so this isn't an issue for new users.
> 
> Correct.
> 
> > It only affects people that have an existing install of an older eslint version, and telling people how to their dependency manager isn't the scope of this project.
> 
> I feel like unblocking users who encounter common errors is within scope. "I installed `react-scripts` before late 2021" probably represents >90% of React users. I'm not saying it's this project's responsibility to fix the error. I'm saying it's this project's responsibility to help users onboard. The root cause and solution were outlined in the OP. It's minimal effort to point to it as a debug step.
> 
> Nonetheless, my intention was for it to become Google-able, as there were _zero_ results for this error previously. Hopefully that goal is still met, even if the project doesn't formally support the unblocking process. 👍

@CharlesStover I'm still facing the same issue, Can you help me
My eslintrc 
```javascript
{
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:import/recommended",
    "plugin:prettier/recommended"
    ],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "jsx-a11y", "jest", "react", "prettier"],
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "commonjs": true,
    "es6": true,
    "jest": true
  },
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".ts", ".jsx", ".tsx"]
      },
      "react": {
        "version": "detect"
      }
    }
  },
  "rules": {
    "prettier/prettier": "error",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-empty-function": 0,
    "@typescript-eslint/no-this-alias": 1,
    "@typescript-eslint/no-use-before-define": 1,
    "@typescript-eslint/no-var-requires": 0,
    "camelcase": 1,
    "class-methods-use-this": 1,
    "func-names": 1,
    "global-require": 1,
    "import/named": 1,
    "import/namespace": 1,
    "import/no-mutable-exports": 1,
    "jsx-a11y/anchor-has-content": 1,
    "jsx-a11y/anchor-is-valid": 1,
    "jsx-a11y/click-events-have-key-events": 1,
    "jsx-a11y/control-has-associated-label": 1,
    "jsx-a11y/label-has-associated-control": 1,
    "jsx-a11y/label-has-for": 1,
    "jsx-a11y/mouse-events-have-key-events": 1,
    "jsx-a11y/no-static-element-interactions": 1,
    "max-classes-per-file": 1,
    "no-bitwise": 1,
    // "no-console": 1,
    // this should be enable on actual typescript development
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "jest/no-disabled-tests": "warn",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/prefer-to-have-length": "warn",
    "jest/valid-expect": "error"
  },
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {
        "@typescript-eslint/explicit-module-boundary-types": ["warn"],
        "@typescript-eslint/explicit-function-return-type": ["error"]
      }
    }
  ]
}
```

My package.json
```javascript
"devDependencies": {
    "@babel/cli": "^7.14.8",
    "@babel/core": "^7.15.0",
    "@babel/eslint-parser": "^7.15.4",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-async-to-generator": "^7.14.5",
    "@babel/plugin-transform-modules-commonjs": "^7.14.5",
    "@babel/preset-env": "^7.14.7",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "@types/babel-core": "^6.25.7",
    "@types/eslint": "^7.28.0",
    "@types/jest": "^27.0.1",
    "@types/react": "^17.0.20",
    "@types/webpack": "^5.28.0",
    "@typescript-eslint/eslint-plugin": "^4.30.0",
    "@typescript-eslint/parser": "^4.30.0",
    "airbnb-browser-shims": "^3.0.0",
    "aws-sdk": "2.294.0",
    "aws-xray-sdk-core": "1.3.0",
    "babel-jest": "^27.1.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-root-import": "^6.1.0",
    "babel-plugin-source-map-support": "^2.0.1",
    "babel-plugin-styled-components": "^1.8.0",
    "babel-plugin-transform-async-to-promises": "^0.8.8",
    "babel-plugin-transform-imports": "^1.5.1",
    "babel-preset-airbnb": "^5.0.0",
    "bluebird": "^3.7.0",
    "cap-ui": "git+ssh://git@github.com/capterra/cap-ui.git#v5.2.0",
    "clean-webpack-plugin": "^2.0.1",
    "core-js": "^3.16.4",
    "dotenv": "^6.0.0",
    "enzyme": "^3.4.2",
    "enzyme-adapter-react-16": "^1.2.0",
    "enzyme-to-json": "^3.3.4",
    "es6-promise": "^4.2.4",
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jest": "^24.4.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "exports-loader": "^0.7.0",
    "file-loader": "^1.1.11",
    "foreman": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "http-aws-es": "^6.0.0",
    "http-server": "^0.11.1",
    "imports-loader": "^0.8.0",
    "jest": "^27.0.4",
    "jest-styled-components": "^6.3.4",
    "js-yaml": "^3.13.1",
    "json-loader": "^0.5.7",
    "node-fetch": "^1.7.3",
    "prettier": "2.3.2",
    "prop-types": "^15.6.2",
    "query-string": "^6.1.0",
    "raw-loader": "^1.0.0",
    "react-test-renderer": "^16.4.2",
    "serverless": "^1.43.0",
    "serverless-finch": "^2.4.2",
    "serverless-offline": "^3.25.8",
    "serverless-plugin-common-layers": "^1.0.0",
    "serverless-plugin-tracing": "2.0.0",
    "source-map-support": "^0.5.9",
    "styled-components": "^3.4.2",
    "styled-normalize": "8.0.0",
    "terser-webpack-plugin": "^1.2.3",
    "ts-jest": "^27.0.5",
    "typescript": "^4.4.2",
    "typescript-eslint": "0.0.1-alpha.0",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "url-loader": "^3.0.0",
    "webpack": "^4.29.6",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1",
    "webpack-manifest-plugin": "^2.0.4",
    "webpack-merge": "^4.2.1",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "@babel/polyfill": "^7.12.1",
    "lambda-api": "^0.10.1",
    "lodash.throttle": "^4.1.1",
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
    "redis": "3.1.2",
    "redis-mock": "^0.56.3",
    "rollbar": "^2.4.1",
    "styled-components": "^3.4.2",
    "url-search-params-polyfill": "^7.0.0",
    "whatwg-fetch": "^2.0.4",
    "worker-farm": "^1.7.0",
    "xss-filters": "^1.2.7",
    "yargs": "^14.2.0"
  }
}

```

``` javascript
error
codeclimate analyze
Starting analysis
Running structure: Done!
Running duplication: Done!
Running eslint: Done!
error: (CC::CLI::Analyze::EngineFailure) engine eslint failed with status 1 and stderr 
WARN: Skipping error-notification/notifiers/RollbarNotifier.js: it appears to be minified
/usr/local/node_modules/eslint/lib/linter/linter.js:1194
            throw err;
            ^

TypeError: Error while loading rule 'prettier/prettier': context.getPhysicalFilename is not a function
Occurred while linting /code/util/continueUntilMatch.js
    at Object.create (/code/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:123:40)
    at createRuleListeners (/usr/local/node_modules/eslint/lib/linter/linter.js:758:21)
    at /usr/local/node_modules/eslint/lib/linter/linter.js:928:31
    at Array.forEach (<anonymous>)
    at runRules (/usr/local/node_modules/eslint/lib/linter/linter.js:873:34)
    at Linter._verifyWithoutProcessors (/usr/local/node_modules/eslint/lib/linter/linter.js:1170:31)
    at Linter._verifyWithConfigArray (/usr/local/node_modules/eslint/lib/linter/linter.js:1268:21)
    at Linter.verify (/usr/local/node_modules/eslint/lib/linter/linter.js:1223:25)
    at Linter.verifyAndFix (/usr/local/node_modules/eslint/lib/linter/linter.js:1413:29)


```

**Comment by dalmo3** [comment]
Also "solved" by reverting to `3.3.1` I guess? This has been working for me:

```
    "eslint": "^7.32.0",
    "react-scripts": "^4.0.3", 
    "eslint-plugin-prettier": "3.3.1",
```

**Comment by ChristianIvicevic** [comment]
Small addition: if you're using yarn v2+ the command has been renamed to the following `yarn up -R eslint`.

**Comment by netcoding87** [comment]
Another addition: 

> react-scripts relies on eslint@^7.11.0 according to your own yarn.lock. That means any fresh installs of react-scripts will pick up newer versions of eslint, so this isn't an issue for new users.

Unfortunately this seems not to be correct. Creating a new react app using cra installs current react-scripts `4.0.3` but eslint in version `7.20.0` 🙁

**Comment by Tesserex** [comment]
For what it's worth, googling this error brought me straight here, and the advice to upgrade to `7.32.0` worked for me. So I guess just filing this issue is a good start to help new people.

**Comment by mikehardy** [comment]
I had something else triggering this where just doing a recursive update wasn't persistent for me - deleting yarn.lock and reinstalling, or doing recursive upgrade didn't work, I didn't inspect too much because it also works if you just put a resolutions block in your package.json:
```
resolutions: {
  eslint: "^version-that-works-here"
}
```

**Comment by Hongbo-Miao** [comment]
Hmm, anyone know what is the equal command of `yarn up -R eslint` for npm? Thanks!

**Comment by April-Zheng** [comment]
https://stackoverflow.com/questions/69069719/error-while-loading-rule-prettier-prettier-context-getphysicalfilename-is-not

 yarn upgrade -R eslint

**Comment by jbowen28** [comment]
Updated react-scripts to react-scripts@4.0.3 to resolve the incompatibility of eslint and eslint-plugin-prettier.

**Comment by Hongbo-Miao** [comment]
> Hmm, anyone know what is the equal command of `yarn up -R eslint` for npm? Thanks!

Just add a follow up of my original question:

- This upgrading `eslint-plugin-prettier` from 3.4.1 to 4 pull request from Renovate which fails all the time since 8/30/2021: https://github.com/Hongbo-Miao/hongbomiao.com/pull/3270
- Since then Renovate keeps trying all the time and finally succeed on 1/11/2022: https://github.com/Hongbo-Miao/hongbomiao.com/pull/4185 .
  - Since I didn't to anything special on purpose, I am guessing some sub dependencies get upgraded during this time and got fixed.
  - In my case, it is not related with `react-scripts` as it got upgraded to 4.0.3 on 2/22/2021 https://github.com/Hongbo-Miao/hongbomiao.com/pull/1827 which is after `eslint-plugin-prettier` succeed upgrading from 3.4.1 to 4

**Comment by cherealnice** [comment]
I got this recently due to multiple eslint versions being installed in my monorepo. Resolved the issue and it's better now :)

**Comment by justintemps** [comment]
I'm having this issue with `eslint@8.41.0` and `eslint-plugin-prettier@4.2.1` and I only have one version of eslint installed.

**Comment by CyxouD** [comment]
It helped me to update eslint.
```
 "eslint": "8.57.0",
 "prettier": "3.2.5",
  "eslint-plugin-prettier": "^5.1.3",
 ```
