### ISSUE TITLE
Running prettier via eslint vs standalone will result in different outcomes

### ISSUE THREAD

**Issue by molaeiali** [prettier/eslint-plugin-prettier#436]
**What version of `eslint` are you using?** 7.22.0

**What version of `prettier` are you using?** 2.2.1

**What version of `eslint-plugin-prettier` are you using?** 3.3.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.eslintrc.js
```
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
```

**What source code are you linting?**
```
    await knex.raw(changeSequenceToRandom({ column: 'id', lowerBound: 1, higherBound: 25 }));
```
**What did you expect to happen?**
```
     await knex.raw(
             changeSequenceToRandom({ column: 'id', lowerBound: 1, higherBound: 25 }),
     );
```
**What actually happened?**
```
    await knex.raw(changeSequenceToRandom({ column: 'id', lowerBound: 1, higherBound: 25 }));
```

Actually, when I run prettier standalone, it is doing the job, but when running `eslint --fix` it does not, I have written in more details in this [StackOverflow](https://stackoverflow.com/questions/69237331/running-prettier-via-eslint-vs-standalone-will-result-in-different-outcomes) post, any ideas why this happens?

**Comment by devinrhode2** [comment]
I am also hitting same issue: https://github.com/xojs/xo/issues/614

**Comment by haixiangyan** [comment]
Try `eslint ./src --fix`.

**Comment by JounQin** [comment]
This issue seems stale, feel free to create a new one with reproduction, thanks.
