### ISSUE TITLE
With eslint fix mode, and using eslint-config-prettier, I still get lint errors every time.

### ISSUE THREAD

**Issue by trusktr** [prettier/eslint-plugin-prettier#45]
I was hoping that running `fix` mode of eslint would cause the prettier plugin to fix stuff, and there would be no more prettier-related lint errors, but that isn't the case. Maybe eslint-config-prettier needs an update?

Here's a branch (in the wrong repo) that you can reproduce from: https://github.com/trusktr/gulp-eslint/tree/issue-204

Just clone that repo and checkout that issue-204 branch, `npm i`, then run `./node_modules/.bin/gulp lint` a few times, and each time the output will continue to show prettier-related errors.

I thought there would be no prettier errors at least the second round if it fixed everything the first round.

**Comment by not-an-aardvark** [comment]
Is this the same issue as https://github.com/eslint/eslint/issues/9142?

**Comment by trusktr** [comment]
Yep, it is. I wasn't sure where to post.

**Comment by trusktr** [comment]
Not a prettier issue though.

**Comment by trusktr** [comment]
It turns out it is eslint's fault: https://github.com/eslint/eslint/issues/9142#issuecomment-324183928
