### ISSUE TITLE
Issue with mapped types

### ISSUE THREAD

**Issue by anubra266** [prettier/eslint-plugin-prettier#453]
**What version of `eslint` are you using?**
7.29.0 

**What version of `prettier` are you using?**
2.3.2

**What version of `eslint-plugin-prettier` are you using?**
3.4.0

<img width="1014" alt="CleanShot 2022-01-25 at 09 29 13@2x" src="https://user-images.githubusercontent.com/30869823/150940463-3d523ec7-2112-4863-9a83-f6a1e210395d.png">

**Comment by BPScott** [comment]
The parsing comes from prettier. This plugin doesn't have any opinion about formatting or parsing itself, it just passes code along to prettier. 

Perhaps a newer version of prettier knows about this syntax and you need to update.
If that doesn't work then please file an issue against prettier
