### ISSUE TITLE
useRef with Typescript lint weired syntax in react-native

### ISSUE THREAD

**Issue by Einere** [prettier/eslint-plugin-prettier#458]
**What version of `eslint` are you using?**
7.32.0

**What version of `prettier` are you using?**
2.3.0

**What version of `eslint-plugin-prettier` are you using?**
^4.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
// .eslintrc.js
module.exports = {
  root: true,
  extends: '@react-native-community',
};

```

**What source code are you linting?**
```typescript
const flatListRef = useRef<FlatList>(null);
```
prettier linting
> ESLint: Replace `<FlatList>(null)` with `·<·FlatList·>·null`(prettier/prettier)

**What did you expect to happen?**
don't linting because it is right syntax.

**What actually happened?**
i using running prettier when save code, IDE force like below.
```typescript
const flatListRef = useRef < FlatList > null;
```

**Comment by BPScott** [comment]
This formatting comes from prettier. This plugin doesn't have any opinion about formatting itself, it just passes along prettier's style.

It might be that you have some other rule that conflicts with prettier. You can use https://github.com/prettier/eslint-config-prettier to disable all rules that would conflict with prettier. That package also provides a helper tool that lets you identify any rules that you currently have enabled that would conflict with prettier's styling.

**Comment by Einere** [comment]
@BPScott 
thanks to comment.
I had using `@react-native-community/eslint-config`. so it includes some other configs.
and I had mistake that using TS syntax at `.js` files, so eslint with prettier linting weirdly.
after change extension `.js` to `.tsx`, weird linting disapeared. 😅
i will close this issue. thanks.
