### ISSUE TITLE
Support prettier v1.6.0 config

### ISSUE THREAD

**Issue by jaydenseric** [prettier/eslint-plugin-prettier#46]
[Prettier v1.6.0](https://github.com/prettier/prettier/releases/tag/1.6.0) is out, and it impliments consmiconfig for options.

This plugin currently requires prettier config to be set within ESLint config. It would be awesome to deprecate this and let prettier derive the config itself.

**Comment by not-an-aardvark** [comment]
Seems reasonable to me. It looks like `prettier` exposes a [`resolveConfig`](https://github.com/prettier/prettier/blob/987b931215b7e2f23df037dfa98344f2993949ad/README.md#prettierresolveconfigfilepath--options) function for getting a config, so I think it should be pretty simple to let prettier handle config resolution.

**Comment by not-an-aardvark** [comment]
Actually, I think this is blocked by https://github.com/prettier/prettier/pull/2722.

**Comment by goldo** [comment]
@not-an-aardvark since it has been merged, I guess we have to wait for the next prettier release ?

**Comment by not-an-aardvark** [comment]
Yes, that's correct.

**Comment by azz** [comment]
Tracking for 1.6.2 which will include .sync() https://github.com/prettier/prettier/issues/2804

**Comment by not-an-aardvark** [comment]
Support for prettier config files has been published in `eslint-plugin-prettier@2.3.0`. Thanks to @kombucha for implementing this.
