### ISSUE TITLE
.prettierrc.mjs not resolving

### ISSUE THREAD

**Issue by git-chrisp** [prettier/eslint-plugin-prettier#468]
I have to use a .prettierrc.mjs but the file does not seem to be supported by this plugin. The reason, why I have to use a .mjs configuration is explained here: https://github.com/prettier/prettier/issues/12701

**What version of `eslint` are you using?** 8.12.0

**What version of `prettier` are you using?** 2.6.2

**What version of `eslint-plugin-prettier` are you using?** 4.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**.prettierrc.mjs**
```javascript
const config = {
  singleQuote: true,
  trailingComma: 'none',
  plugins: [
    import.meta.resolve('prettier-plugin-import-sort')
  ]
}

export default config
```

**What source code are you linting?**

console.log('Hello world!')

**What did you expect to happen?**

The configuration should be loaded by the plugin.

**What actually happened?**

The `prettier.resolveConfig.sync` returns `null`

**Comment by git-chrisp** [comment]
Nevermind, I thought prettier supported .mjs but it does not.

**Comment by aetdesenvolvimentoweb** [comment]
Install these two libraries:
eslint-plugin-react-hooks
@next/eslint-plugin-next

example:
`npm i -D eslint-plugin-react-hooks @next/eslint-plugin-next`

configure eslint.config.mjs as follows:

```
import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
 baseDirectory: __dirname,
});

const eslintConfig = [
...compat.config({
plugins: ["react-hooks", "@next/next", "prettier"],
extends: ["next/core-web-vitals", "next/typescript", "prettier"],
rules: {
"prettier/prettier": "error",
},
}),
];
export default eslintConfig;
```

and create the .prettierrc.json file with the following content:

```
{
"endOfLine": "lf",
"printWidth": 80,
"semi": true,
"singleQuote": false,
"trailingComma": "all",
"tabWidth": 2,
"useTabs": false
}
```
or as you prefer...

It worked here.
