### ISSUE TITLE
Prettier wants to remove all return characters in CRLF

### ISSUE THREAD

**Issue by ggtylerr** [prettier/eslint-plugin-prettier#470]
**What version of `eslint` are you using?** 8.15.0

**What version of `prettier` are you using?** 2.6.2

**What version of `eslint-plugin-prettier` are you using?** 4.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
module.exports = {
  env: {
    browser: true,
    node: true,
    es2021: true,
  },
  plugins: ["prettier"],
  extends: ["standard", "plugin:prettier/recommended"],
  parserOptions: {
    ecmaVersion: "latest",
  },
  rules: {
    "prettier/prettier": "warn",
    semi: ["warn", "always"],
  },
};
```

**What source code are you linting?**
```js
console.log("test");
console.log("test");
console.log("test");
console.log("test");
console.log("test");
console.log("test");
```

**What did you expect to happen?**
For there to be no warnings.

**What actually happened?**
Prettier warns about delete "CR" (carriage return):
![image](https://user-images.githubusercontent.com/28498877/168128824-86abcc15-fdca-4f63-8c24-0be383718999.png)
![image](https://user-images.githubusercontent.com/28498877/168128924-54bad43b-6525-41a2-b4cd-0bc8f2273c74.png)

**Additional notes**
* This occurs on new files. After a while (restarting does not fix it, it just randomly happens), it fixes itself.
* I have no idea if the plugin itself is causing this. This may also be due to `eslint-config-prettier`, `standard`, `prettier`'s plugin implementation in `standard`, or ESLint. *I can at least rule out VS Code since this also occurs in terminal.*

**Comment by ggtylerr** [comment]
Update: Changing to `LF` on my IDE fixed it. Updated issue accordingly.

**Comment by Rafeqm** [comment]
I have same issue here. The disaster is that I configure ESLint after my project goes big. Now changing every files' EOL seems hardly possible

**Comment by BPScott** [comment]
Seems like you should set prettier's end-of-line option - https://prettier.io/docs/en/options.html#end-of-line

I'd also suggest looking into [editorconfig](https://editorconfig.org/), which prettier and several popular editors use to specify line endings and other whitespace related settings on a per-repo basis
