### ISSUE TITLE
Relax pragma rules

### ISSUE THREAD

**Issue by sheepsteak** [prettier/eslint-plugin-prettier#48]
At the moment the pragma has to be the first line and in the `/** @yourPragma */` format. If it's used in a file with Flow it means you have to remember to put the Prettier one first.

This isn't a huge hassle but it caused me a few minutes of confusion as I thought I had things set up wrong. It would be nice if this plugin's pragma were more like Flow's and could be in either `// @yourPragma` or `/** @yourPragma */` format and be anywhere in the file.

**Comment by not-an-aardvark** [comment]
Seems reasonable to me.

**Comment by wbinnssmith** [comment]
I actually just got pragma functionality merged into prettier itself: prettier/prettier#2772. Right now it requires the docblock format (so no `// @prettier`), but they might be open to a similar issue over there. It currently uses jest's implementation of pragma parsing (more detail at that PR).

I filed a separate issue here to discuss this plugin's migration to the new core option at #54

**Comment by BPScott** [comment]
Closed as pragma functionality has been removed in favour of using prettier's native pragma support as of v3
