### ISSUE TITLE
v5

### ISSUE THREAD

**Issue by JounQin** [prettier/eslint-plugin-prettier#481]
- [x] drop Node v12 - #488
- [x] drop ESLint v7 - #488
- [x] improve jsdoc inside, generate .d.ts typings - #509
- [x] docs: improve why `usePrettierrc` option is needed
- [ ] prettier v3

related #508

**Comment by JounQin** [comment]
@BPScott I don't quite understand why we add `usePrettierrc` option in #83, `prettierrc` is used for all tools, it should always be preferred, I have no idea about in which case we should have inconsistent prettier settings, what do you think?

**Comment by dangmai** [comment]
When I try to use `5.0.0-alpha.0`, I'm running into an issue where `synckit` can't be detected. I don't see that as a dependency for this project, but maybe it should?

The abbreviated stack trace looks like this:

```
Error: Cannot find module 'synckit'
Require stack:
- C:\Dev\prettier-plugin-apex\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js
- C:\Dev\prettier-plugin-apex\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
```
