### ISSUE TITLE
Option like usePrettierrc but for prettierignore?

### ISSUE THREAD

**Issue by tunnckoCore** [prettier/eslint-plugin-prettier#493]
There is an option for ignoring the prettierrc if there is one. And would be good to be able to disable prettierignore too.

Sorry for removing the template, but versions and such stuff is not relevant.

### The rationale

I'm using both the ESLint and the Prettier VSCode extensions. This is because I want Prettier to format everything except JS/TS and ESLint to format/lint only TS/JS. I also want to be consistent between CLI and the IDE behavior.

To do this, I'm using the prettier plugin, disable reading from the rc file with `usePrettierrc: false`, and passing the config to the plugin.

```
'prettier/prettier': [
  'error',
  prettierConfig,
  { usePrettierrc: false },
],
```

But there's a problem. The Prettier extension still formats JS/TS files with its defaults, thus I ignore TS/JS stuff in `.prettierignore` so it stops, but then it seems that the ESLint's loaded plugin config respects the prettierignore, so it stops formating JS files too.

The fix would be to add option like `usePrettierrc`, for example `usePrettierignore: false`. The other way around is to just pass the same config to the prettier.config.js, but why duplicate stuff when it can be a bit easier. Also, I don't think it's a maintenance burden or breaking change.

**Comment by JounQin** [comment]
That's why you should use `prettierrc` which is used by all tools for consistency.
