### ISSUE TITLE
Problems with comments

### ISSUE THREAD

**Issue by IshanMK** [prettier/eslint-plugin-prettier#495]
**What version of `eslint` are you using?**
8.19.0
**What version of `prettier` are you using?**
2.7.1
**What version of `eslint-plugin-prettier` are you using?**
4.2.1
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
{
  "extends": ["airbnb", "prettier", "plugin:node/recommended"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error",
    "spaced-comment": "off",
    "no-console": "off",
    "consistent-return": "off",
    "func-names": "off",
    "object-shorthand": "off",
    "no-process-exit": "off",
    "no-param-reassign": "off",
    "no-return-await": "off",
    "no-underscore-dangle": "off",
    "class-methods-use-this": "off",
    "prefer-destructuring": ["error", { "object": true, "array": false }],
    "no-unused-vars": ["error", { "argsIgnorePattern": "req|res|next|val" }]
  }
}
**What source code are you linting?**
// First check the id
router.param('id', tourController.checkID);
// Only works when id parameter is given
//   Here val is holding the value of the id parameter
//   Don't forget to call next().otherwise it will stuck in the middleware stack

**What did you expect to happen?**
Check for the coding issues and automatically fix the,
**What actually happened?**
Even the comments are identified as errors

**Comment by JounQin** [comment]
A good format of issue content and minimal reproduction repo is required.

**Comment by JounQin** [comment]
`"extends": ["airbnb", "prettier", "plugin:node/recommended"]`

We are not enabling `eslint-plugin-prettier` correctly, it should be `"extends": ["airbnb", "plugin:node/recommended", "plugin:prettier/recommended"]`, note, `"plugin:prettier/recommended"` always comes last.
