### ISSUE TITLE
Provide clarity on plugin "Options" found in Readme.md - persistent linting errors

### ISSUE THREAD

**Issue by sol-idsnake** [prettier/eslint-plugin-prettier#497]
**What version of `eslint` are you using?**
^8.19.0

**What version of `prettier` are you using?**
^2.7.1

**What version of `eslint-plugin-prettier` are you using?**
^4.2.1

**What version of `eslint-config-prettier` are you using?**
^8.5.0

**Please paste any applicable config files that you're using. .eslintrc.js:**
```
module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    "plugin:prettier/recommended",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["react", "@typescript-eslint"],
  rules: {
    "prettier/prettier": [
      "error",
      {
        singleQuote: true,
      },
    ],
  },
};
```

**What source code are you linting?**
any JS file declared as 'Babel Javascript' by VS Code, the settings are set to use Prettier as the default formatter since the point is to run prettier as an eslint rule.

**Clarification needed:**
I installed the above versions in a fresh project and included `"eslint-config-prettier": "^8.5.0",`.
The [options](https://github.com/prettier/eslint-plugin-prettier#options) for `eslint-plugin-prettier` state the following:

> While it is possible to pass options to Prettier via your ESLint configuration file, it is **not** recommended

This indicates that prettier options should be added in a .prettierrc file.

> The first option: - An object representing options that will be passed into prettier (followed by a JSON object of options)

This indicates that prettier options should be added in the .eslintrc file, presumably under 'rules'.

I am using the singleQuote rule as an example. Adding this option in a dedicated .prettierrc file causes an error by eslint(prettier/prettier), prompting to replace double quotes with single quotes.
Replacing the .prettierrc file in favor of the eslint rule listed above (`"prettier/prettier": ["error", {singleQuote: true}])`) will also incur the this error. Only adding back the .prettierrc file **in addition** with the same rule will stop the error from happening, but the Options section of this plugin rightfully states that having both configs (.prettierrc file & eslint rule)

> can lead to an inconsistent experience.

Please help me understand the best option going forward. Why is there a persistent linting error while following best practice as laid out by this plugin?

I'm happy to contribute to this issue and provide a pull request with an example config/project once this is working as I don't think I'm the only person struggling with the wording in this FAQ. 

Thank you for any help!

**Comment by JounQin** [comment]
`prettierrc` configurations are always preferred way to define options.

> While it is possible to pass options to Prettier via your ESLint configuration file, it is not recommended

It has been documented, it's not the best practice.

You should always use `prettierrc` configurations when possible. If you know how to improve the document, PR welcome.

**Comment by stall84** [comment]
You guys don't label **which rc file** to write the prettier/prettier: [] in .. I'm having this problem right now

Your documents start out talking about how it's not a good idea to pass options in from eslintrc .. but then when you show the "options" to fix the problems.. **you don't say which rc file to write the fix-options in** .. this is simple.. just make a label for which file you are writing things in .
