### ISSUE TITLE
JUST WANT TO SET MYSELF FREE FROM eslint-plugin-prettier

### ISSUE THREAD

**Issue by Nima-net** [prettier/eslint-plugin-prettier#507]
this package annoyingly throws err any time I open a file which is not well formatter
I DIDNT EVEN REMEMBER ADDING IT MYSELF
how can I remove it compeletly or at least disable it?

![20220814_12464120](https://user-images.githubusercontent.com/55187854/184528488-95013bd5-72a5-44cf-8c6a-5206312ac787.png)
t

**Comment by Nima-net** [comment]
...

**Comment by xploSEoF** [comment]
@Nima-net ReactNative added this somewhere between 0.65.1 and 0.70.1. With a bit of digging, I'm sure I could point you at the exact commit. At a guess, you've upgraded ReactNative and found yourself in an unrecognised world of linting.

Here's the good news for you, it's easy to turn off linting on your existing project: edit the `.eslint.js` file in the root of your project, and comment out the line that reads `extends: @react-native-community`.

It's my opinion that frameworks should not try to force a coding style upon the projects using them, but it seems Meta do not share this consideration, so I understand your pain. However, I do recommend starting to use a linter to improve your consistency in your projects.
