### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by qingmingsang** [prettier/eslint-plugin-prettier#51]
```
npm i eslint-plugin-prettier -D
```
```
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: fast-diff@^1.1.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.1.0, 1.0.1, 1.0.0
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. `fast-diff@1.1.1` was published 10 months ago, so I'm not sure why that error is occurring, but I don't think it's an issue with `eslint-plugin-prettier`. If you're using an enterprise npm registry, it's possible the registry needs to be updated (or it should proxy through to the real npm). It's also possible that there is some issue with your local npm cache.

**Comment by qingmingsang** [comment]
Thx,I have found it is private npm registry problem.
