### ISSUE TITLE
 definition is missing display nae

### ISSUE THREAD

**Issue by luancardosoti** [prettier/eslint-plugin-prettier#518]
**What version of `eslint` are you using?**

**What version of `prettier` are you using?**

**What version of `eslint-plugin-prettier` are you using?**

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**What source code are you linting?**

**What did you expect to happen?**

**What actually happened?**

**Comment by JounQin** [comment]
No idea what's your meaning, please provide more details.

**Comment by JounQin** [comment]
close due to lack of details
