### ISSUE TITLE
"README.md/ Recommended Configuration" needs more detail

### ISSUE THREAD

**Issue by ayhanyildiz** [prettier/eslint-plugin-prettier#524]
In Recommended Configuration at step 2. It would be nice if it mentions like:

2.Then you need to add plugin:prettier/recommended as the last extension or for more granular control you can add in each file type in overrides .eslintrc.json:

```
{
  "extends": ["plugin:prettier/recommended"]
}
```

or 
```
{
  "overrides": [
    {
      "files": ["*.ts"],
      "extends": ["plugin:prettier/recommended"]
      },
    {
      "files": ["*.html"],
      "extends": ["plugin:prettier/recommended"]
      }
]
}
```

**Comment by JounQin** [comment]
PR welcome.

**Comment by BPScott** [comment]
Usage of `overrides` is standard eslint functionality and is already adequately covered by eslint's documentation. I do not feel that it is this plugin's job to redescribe standard eslint functionality.
