### ISSUE TITLE
index.html   1:2  error  Parsing error: Unexpected token  prettier/prettier

### ISSUE THREAD

**Issue by aregaieg0406** [prettier/eslint-plugin-prettier#537]
**What version of `eslint` are you using?**
8.31.0

**What version of `eslint-plugin-prettier` are you using?**
4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
https://github.com/aregaieg0406/eslint-html-parser-sample/blob/main/.eslintrc.json 

**What source code are you linting?**
https://github.com/aregaieg0406/eslint-html-parser-sample/blob/main/index.html

**What did you expect to happen?**
I expected the linter to pass with success

**What actually happened?**
I have the following error:  1:2  error  Parsing error: Unexpected token  prettier/prettier

I created a sample case here: https://github.com/aregaieg0406/eslint-html-parser-sample
It's possible to reproduce the error by running "npm run lint" on this project.

I got this error after updating my eslint packages (including plugins and parsers)

Thank you for your help!

**Comment by so1ve** [comment]
https://github.com/prettier/eslint-plugin-prettier/issues/466#issuecomment-1100003233

**Comment by JounQin** [comment]
Sorry but you need to parse a custom `parser` option for eslint-plugin-prettier like @so1ve's comment above in this case, because we're compatible with eslint-plugin-html by default.
