### ISSUE TITLE
The plugin treats line breaks differently when called from VSCode ESLint formatter and react-scripts start

### ISSUE THREAD

**Issue by quassnoi** [prettier/eslint-plugin-prettier#538]
**What version of `eslint` are you using?**

v8.31.0

**What version of `prettier` are you using?**

2.8.1

**What version of `eslint-plugin-prettier` are you using?**

4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.11",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.4",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest",
      "plugin:prettier/recommended"
    ]
  },
  "prettier": {
    "trailingComma": "none",
    "tabWidth": 2,
    "printWidth": 120,
    "singleQuote": false,
    "jsxBracketSameLine": true,
    "useTabs": false
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "prettier": "^2.8.1"
  }
}
```

**What source code are you linting?**

`create-react-app --template=typescript` straight out of box, with prettier added.

```
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer">
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**What did you expect to happen?**

`prettier/prettier` behaves in the same way in VSCode ESLint formatter and `npm start`

**What actually happened?**

VSCode ESLint formatter and `npm start` are in conflict, with `prettier/prettier`, the same plugin, reporting different errors:

### No line breaks, npm start is happy, VSCode is not

![image](https://user-images.githubusercontent.com/588458/210849014-f35c337d-b673-4443-b678-d6d5e17645f6.png)

### Yes line breaks, VSCode is happy, npm start is not

![image](https://user-images.githubusercontent.com/588458/210848258-3ee5291d-554c-40a2-9954-5064c52484f7.png)

**Comment by patrickcate** [comment]
I think I'm running in to the same issue. Seems to only affect line length/line breaks.

**Comment by james1050** [comment]
I fixed my similar issue by going to VSCode settings and searching 'prettier config', and setting the 'Prettier: Config Path' setting to  .prettierrc (which is my prettier config in my workspace).

**Comment by JounQin** [comment]
Did you try to reload VSCode after configging prettier and eslint?
