### ISSUE TITLE
Transition plan for new `requirePragma` in prettier core

### ISSUE THREAD

**Issue by wbinnssmith** [prettier/eslint-plugin-prettier#54]
I just got the pragma functionality merged into prettier itself at prettier/prettier#2772. It is very similar to the functionality implemented here, only:
  * Now editors can use their autoformat functionality and follow the same rules for applying based on the pragma as other tools
  * The name of the pragma is fixed to either `@prettier` or `@format`. There's a bit of discussion in that PR behind this reasoning.

How should we manage the transition from `eslint-plugin-prettier`'s implementation of pragmas to the new one in core? Off the top of my head it makes sense to no longer use the third option for this plugin, and instead either rely on a `.prettierrc` or instruct users to pass along `requirePragma` in the second options argument of this plugin.

Thanks! cc @asuarez

**Comment by not-an-aardvark** [comment]
I think we could probably deprecate the pragma option in `eslint-plugin-prettier` in favor of using `prettier`'s version directly. People won't be able to use pragmas other than `@prettier` or `@format`, but my impression is that being able to customize the pragma isn't a very important feature.

**Comment by BPScott** [comment]
Closed as pragma functionality has been removed in favour of using prettier's native pragma support as of v3
