### ISSUE TITLE
Organizing imports produces two empty lines

### ISSUE THREAD

**Issue by om-ha** [prettier/eslint-plugin-prettier#540]
**What version of `eslint` are you using?**
```"eslint": "^8.32.0",```

**What version of `prettier` are you using?**
```"prettier": "^2.8.3",```

**What version of `eslint-plugin-prettier` are you using?**
```"eslint-plugin-prettier": "^4.2.1",```

**What version of `eslint-config-prettier` are you using?**
```"eslint-config-prettier": "^8.6.0",```

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
### `.prettierrc`
```json
{
  "singleQuote": true,
  "trailingComma": "all"
}
```
### `.eslintrc.js`
```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'tsconfig.json',
    tsconfigRootDir: __dirname,
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint/eslint-plugin'],
  extends: [
    'plugin:@typescript-eslint/recommended',

    // Commenting prettier rules fixes the issue...
    'plugin:prettier/recommended',
  ],
  root: true,
  env: {
    node: true,
    jest: true,
  },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',

    // This commented workaround suppresses the error but stops correct formatting of indentation
    //'prettier/prettier': ["error", { "endOfLine": "off" }]
  },
};
```

**What source code are you linting?**

- **Use  VS Code's "organize imports" feature two times in a row on this input data** (can be triggered from command palette)
```ts
export { SampleModule } from './sample.module';
export { SampleService } from './sample.service';
```

**What did you expect to happen?**
- Only one empty line (added single space character here so it is rendered on GitHub issue).
```ts
export { SampleModule } from './sample.module';
export { SampleService } from './sample.service';
 
```

**What actually happened?**
- Getting an extra line and this linter error: ```Delete `⏎` eslint(prettier/prettier)```
- Two empty line (added single space character here so it is rendered on GitHub issue).
```ts
export { SampleModule } from './sample.module';
export { SampleService } from './sample.service';
 
 
```

### VS Code
Version: 1.74.3 (Universal)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

**Comment by so1ve** [comment]
Have you set editor.formatOnSave to true?

**Comment by BPScott** [comment]
It is not this plugin's problem that running a built-in VSCode command does not produce prettier/eslint-compatible code. You need run eslint after running that command. The easiest way to do that is to set `editor.formatOnSave` to trigger autoformating on save.
