### ISSUE TITLE
Does `eslint --fix` fix all prettier errors?

### ISSUE THREAD

**Issue by ozum** [prettier/eslint-plugin-prettier#545]
Hi,

When using `eslint-plugin-prettier` + `eslint-config-prettier`, eslint detects all prettier errors and warnings. I have some questions.

1. Does `eslint --fix` fix all prettier errors?
2. Can I remove `prettier` dependency from `package.json` and just use `eslint --fix`?
3. Can I remove prettier extension from VSCode and just use eslint extension with:
```
"editor.codeActionsOnSave": {
  "source.fixAll": true
}
```

I want to fix linting and formatting errors in one go and wonder if it is possible using `eslint-plugin-prettier`.

Thanks,

**Comment by so1ve** [comment]
1. Yes
2. No?
3. Yes

**Comment by ozum** [comment]
thanks, for the concise answer.
