### ISSUE TITLE
Render whitespace characters in output

### ISSUE THREAD

**Issue by cristianrgreco** [prettier/eslint-plugin-prettier#547]
**What version of `eslint` are you using?**
8.26.0

**What version of `prettier` are you using?**
2.7.1

**What version of `eslint-plugin-prettier` are you using?**
4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.prettierrc
```
{
    "printWidth": 120
}
```

.eslintrc
```
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  plugins: ["prettier", "@typescript-eslint"],
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:prettier/recommended"],
  rules: {
    "prettier/prettier": "error",
  },
};
```

**What source code are you linting?**
typescript/javascript/JSON

**What did you expect to happen?**
For the error message to be rendered such that it is correctly displayed in a GitHub actions pipeline

**What actually happened?**
The whitespace in the error message is not rendered:
```
/Users/cristian/Documents/code/personal/testcontainers-node/src/startup-check-strategy.ts
  14:98  error  Replace `async·()·=>·await·this.checkStartupState(dockerode,·container.id),·(startupStatus)·=>·startupStatus·===·"SUCCESS"·||·startupStatus·===·"FAIL",·()·=>·new·Error(`Container·not·accessible·after·${this.startupTimeout}ms·for·${container.id}`),·this.startupTimeout` with `⏎······async·()·=>·await·this.checkStartupState(dockerode,·container.id),⏎······(startupStatus)·=>·startupStatus·===·"SUCCESS"·||·startupStatus·===·"FAIL",⏎······()·=>·new·Error(`Container·not·accessible·after·${this.startupTimeout}ms·for·${container.id}`),⏎······this.startupTimeout⏎····`  prettier/prettier
```

This causes the pipeline annotation to look as follows, which is hard to read/understand:
![Screenshot 2023-02-18 at 16 56 26](https://user-images.githubusercontent.com/10348798/219878256-6d387a59-f0bd-4ccc-9c28-96c05205d4c9.png)

**Comment by so1ve** [comment]
Working as intended because spaces are recognized "invisibles" so the plugin replaces them to dots in the message.

**Comment by BPScott** [comment]
Printing invisible characters like spaces with alternative characters is preferable to outputing them directly, Messages like `Replace " " with " "` (that's replacing a tab with a space) is way more confusing.
