### ISSUE TITLE
Which RC file do we do the 'OPTIONS' section of solutions in? (we cant read minds.. label the file you're editing-in)

### ISSUE THREAD

**Issue by stall84** [prettier/eslint-plugin-prettier#551]
Re-open this issue. I'm having it right now
https://github.com/prettier/eslint-plugin-prettier/issues/497#issue-1306383966

Please explain WHICH rc file to write these options to fix the 'prettier/prettier' warnings in .. 

see my comment at the bottom for more context.

You start out describing how it's possible to pass options down from eslintrc .. then you show rules?? are they rules?? to write ```prettier/prettier: [...]``` .. but then we're left not knowing WHICH rc file you're talking about writing these in since you just got finished mentioning BOTH of them (eslintrc and prettierrc)

**Comment by BPScott** [comment]
Configure prettier in your `.prettierrc`
