### ISSUE TITLE
eslint prettier/prettier rule is giving the error against the prettierrc config file.

### ISSUE THREAD

**Issue by rjritik1137** [prettier/eslint-plugin-prettier#554]
eslint-plugin-prettier now knows how to find prettier config files, so the new recommended way is:

```json
// .eslintrc.json
{
    "extends": "prettier",
    "plugins": [
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error"
    }
}
```

```json
// .prettierrc
{
  "singleQuote": true
}
```

_Originally posted by @azz in https://github.com/prettier/prettier/issues/2280#issuecomment-336608596_

**Comment by fisker** [comment]
Ah, seems you didn't install `eslint-plugin-prettier`?

**Comment by rjritik1137** [comment]
eslint-plugin-prettier is installed. Please have a look at package.json.

The error is 
Replace `'expo-linear-gradient'` with `"expo-linear-gradient"`eslint[prettier/prettier] (https://github.com/prettier/eslint-plugin-prettier#options)`

**Comment by BPScott** [comment]
[`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) is what is responsible for turning off all the eslint rules that would conflict with prettier, however it seems you never enable that in your eslintrc.

You enable `"plugin:prettier/recommended"` but that just turns on the prettier rule from `eslint-plugin-prettier`, it doesn't disable things like the `quotes` rule that would conflict with prettier's formatting. Note that in the extends array `prettier` refers to eslint-config-prettier, while `plugin:prettier` refers to eslint-plugin-prettier.


```diff
- "extends": ["airbnb", "airbnb/hooks", "plugin:prettier/recommended"],
+ "extends": ["airbnb", "airbnb/hooks", "plugin:prettier/recommended", "prettier"],
```

**Comment by rjritik1137** [comment]
https://github.com/prettier/eslint-plugin-prettier#recommended-configuration

According to documentation here,  "plugin:prettier/recommended" takes care of enabling the "eslint-config-prettier" that would disable conflicting rules.

Also, after extending to this array
`["airbnb",` "airbnb/hooks", "plugin:prettier/recommended", "prettier"]`
The problem was still the same.
