### ISSUE TITLE
Using ternary on tailwind

### ISSUE THREAD

**Issue by khasmir04** [prettier/eslint-plugin-prettier#559]
**What version of `eslint` are you using?**
^8.36.0

**What version of `prettier` are you using?**
^2.8.8

**What version of `eslint-plugin-prettier` are you using?**
^4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
pretter.config.cjs
/** @type {import("prettier").Config} */
const config = {
  plugins: [require.resolve('prettier-plugin-tailwindcss')],
}

module.exports = config

eslintrc.cjs
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path')

/** @type {import("eslint").Linter.Config} */
const config = {
  overrides: [
    {
      extends: [
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
      ],
      files: ['*.ts', '*.tsx'],
      parserOptions: {
        project: path.join(__dirname, 'tsconfig.json'),
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: path.join(__dirname, 'tsconfig.json'),
  },
  plugins: ['@typescript-eslint', 'prettier'],
  extends: [
    'next/core-web-vitals',
    'plugin:@typescript-eslint/recommended',
    'prettier',
  ],
  rules: {
    '@typescript-eslint/consistent-type-imports': [
      'warn',
      {
        prefer: 'type-imports',
        fixStyle: 'inline-type-imports',
      },
    ],
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    'prettier/prettier': [
      'warn',
      {
        singleQuote: true,
        trailingComma: 'all',
        semi: false,
        useTabs: false,
        tabWidth: 2,
        endOfLine: 'auto',
      },
    ],
  },
}

module.exports = config

**What source code are you linting?**
```
<Button
        className={`self-end ${inputValue.length < 1 ? 'cursor-default' : 'cursor-pointer'}`}
        disabled={inputValue.length < 1}
      >
        Tweet
</Button>
```

**What did you expect to happen?**
```
<Button
        className={`self-end ${
          inputValue.length < 1 ? 'cursor-default' : 'cursor-pointer'
        }`}
        disabled={inputValue.length < 1}
      >
        Tweet
</Button>
```
**What actually happened?**
```
<Button
        className={`self-end ${inputValue.length < 1 ? 'cursor-default' : 'cursor-pointer'
          }`}
        disabled={inputValue.length < 1}
      >
        Tweet
</Button>
```

Additional:
Here it shows the errors when saving it
![image](https://github.com/prettier/eslint-plugin-prettier/assets/61497334/4be0ed3c-a73d-46ab-8704-a261c0f9e5d4)

**Comment by JounQin** [comment]
Please use cleaner issue content and explain why it is related to `eslint-plugin-prettier` instead of `prettier` itself.
