### ISSUE TITLE
New setting `vs-code-prettier-eslint.eslintConfigPath` (and 3 more) to improve Ctrl+S speed

### ISSUE THREAD

**Issue by GreenTea124** [prettier/eslint-plugin-prettier#571]
# Feature idea

I think this plugin could support 4 new VS Code settings like this:

```jsonc
// .vscode/settings.json
{
	// Existing
	"vs-code-prettier-eslint.prettierLast": false,
	// New
	"vs-code-prettier-eslint.eslintConfigPath": ".eslintrc.fix.json",
	"vs-code-prettier-eslint.eslintIgnorePath": ".gitignore",
	"vs-code-prettier-eslint.prettierConfigPath": "prettier.config.js",
	"vs-code-prettier-eslint.prettierIgnorePath": ".gitignore",
}
```

# Why?

Some ESLint rules can be quite slow, and running them on every Ctrl+S can become laggy if you frequently save your files to format them. With my ESLint setup, sometimes I have to wait 10+ seconds, and sometimes VSCode refuses to format things entirely, it just keeps loading until I reset it.

To address this, I propose additional settings, that would allow two-config setups. One ESLint config could be used by `ESLint Plugin` for full linting and in-editor error messages (`.eslintrc.js`), and another one could be very tiny and used by `Prettier ESLint Plugin` for auto-formatting (`.eslintrc.fix.json`).

**Comment by JounQin** [comment]
Did you post in a wrong repository? And this ESLint plugin can not control how VSCode work.
