### ISSUE TITLE
Error on comma after multiline function call

### ISSUE THREAD

**Issue by HaoboZ** [prettier/eslint-plugin-prettier#582]
**What version of `eslint` are you using?** 8.48.0

**What version of `prettier` are you using?** 3.0.3

**What version of `eslint-plugin-prettier` are you using?** 5.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```
{
	"env"          : {
		"browser": true,
		"es2021" : true
	},
	"extends"      : [
		"eslint:recommended",
		"plugin:@typescript-eslint/recommended",
		"plugin:prettier/recommended"
	],
	"parser"       : "@typescript-eslint/parser",
	"parserOptions": {
		"ecmaVersion" : "latest",
		"ecmaFeatures": { "jsx": true },
		"sourceType"  : "module"
	},
	"plugins"      : [ "@typescript-eslint" ],
	"rules"        : {}
}
```

```
{
	"singleQuote": true,
	"useTabs"    : true
}

```

**What source code are you linting?**

```
randomFunction(
	'this is a really long sentence that forces the next argument into the next line, add more if needed',
	'problem',
);
```

**What did you expect to happen?**

no error

**What actually happened?**

Throws an error at the comma of `'problem',` saying to delete the comma, prettier adds the comma back.
Commenting out `"plugin:prettier/recommended"` does make the error go away so I'm assuming its an issue with this.

**Comment by JounQin** [comment]
Please provide an online runnable reproduction.
