### ISSUE TITLE
Support ESLint flat config

### ISSUE THREAD

**Issue by filiptammergard** [prettier/eslint-plugin-prettier#591]
Hey!

Thanks for a useful plugin. Right now, only eslintrc format is supported. In ESLint v9, the new flat format will be the default: https://eslint.org/blog/2023/10/flat-config-rollout-plans/

More and more projects are migrating to flat config format as a preparation. Do you have plans for supporting flat config in this plugin?

I'm willing to help out if this is something you want to do.

**Comment by JounQin** [comment]
Welcome, @filiptammergard ! PR welcome to support ESLint flat config.

**Comment by sdavids** [comment]
Also, update README with flat config example(s).

**Comment by filiptammergard** [comment]
> Also, update README with flat config example(s).

Definitely. Progress can be followed in this PR: https://github.com/prettier/eslint-plugin-prettier/pull/592
