### ISSUE TITLE
Linting fails  importing prettier config.

### ISSUE THREAD

**Issue by ronny-lark** [prettier/eslint-plugin-prettier#601]
**What version of `eslint` are you using?**
8.47

**What version of `prettier` are you using?**
3.0

**What version of `eslint-plugin-prettier` are you using?**
5.0.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```json
// .eslintsrc.json
{
    "extends": [
        "../../../.eslintrc.base.fe.json",
        "plugin:storybook/recommended",
        "prettier"
    ],
    "ignorePatterns": ["build/**/*", "coverage/**/*", "node_modules/**/*"],
    "plugins": [ "prettier" ],
    "rules": {
      "prettier/prettier": "warn"
    }  
}
```

```js
// .prettierrc.js
import { commonPrettierConfig } from '@shared/frontend'

export default commonPrettierConfig;
```

```ts
// commonPrettierConfig.ts
import { Config } from 'prettier';

export const commonPrettierConfig: Config = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'always',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
};
```

**What source code are you linting?**
React TSX an regular TS.

**What did you expect to happen?**
I expected to run `eslint . --fix` and have it work.

**What actually happened?**
```
> eslint . --fix


Oops! Something went wrong! :(

ESLint: 8.47.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ronnyefronny/projects/Flow-Loop/packages/jargonic/frontend/.prettierrc.js from /Users/ronnyefronny/projects/Flow-Loop/node_modules/prettier/internal/internal.mjs not supported.
Instead change the require of .prettierrc.js in /Users/ronnyefronny/projects/Flow-Loop/node_modules/prettier/internal/internal.mjs to a dynamic import() which is available in all CommonJS modules.
```

According to Prettier, Prettier 3 does in fact support modules, so I'm not sure what's going on here.

Also what kind of recommendation is this, to "instead, change the require to an import" in an internal file like that's feasible? Wild.

**Comment by JounQin** [comment]
Did you add `type: module` in your `package.json`? Otherwise `.js` is intercepted as commonjs rather than ESM.

**Comment by ronny-lark** [comment]
This was an issue on my end, the common config was not being exported correctly.
The error message is still wack though.
