### ISSUE TITLE
Support for new experimental ternaries formatting on prettier 3.1.0

### ISSUE THREAD

**Issue by efstathiosntonas** [prettier/eslint-plugin-prettier#606]
**What version of `eslint` are you using?**
 `"eslint": "8.53.0"`
**What version of `prettier` are you using?**
`"prettier": "^3.1.0"`
**What version of `eslint-plugin-prettier` are you using?**
`"eslint-plugin-prettier": "^5.0.1"`

**What source code are you linting?**
React-native

**What did you expect to happen?**
To support new experimental ternaries formatting https://prettier.io/blog/2023/11/13/3.1.0

**What actually happened?**
Eslint complains about bad formatting.

Temp fix was to add prettier on my `resolutions` on `package.json` and `yarn install` afterwards:

```json
  "resolutions": {
    "prettier": "3.1.0"
  },
```

**Comment by JounQin** [comment]
Can't you use `experimentalTernaries` option?
