### ISSUE TITLE
Remove default parser `flow`

### ISSUE THREAD

**Issue by niftylettuce** [prettier/eslint-plugin-prettier#61]
You should use prettier defaults for a plugin.

https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L25

Needs to be removed.

**Comment by not-an-aardvark** [comment]
I don't understand what you mean. As far as I can tell, those options are only in effect when using the special `"fb"` config, and are not used by default. Could you clarify what the problem is?

**Comment by niftylettuce** [comment]
Correct @not-an-aardvark just having issues with #60 still.
