### ISSUE TITLE
Synckit seems incompatible with Node 14.18.1

### ISSUE THREAD

**Issue by tturtonroku** [prettier/eslint-plugin-prettier#618]
I'm getting a module not found error when running eslint in Node v14.18.1.

**What version of `eslint` are you using?**
8.34.0

**What version of `prettier` are you using?**
3.1.0

**What version of `eslint-plugin-prettier` are you using?**
5.0.1

**What actually happened?**
```
> eslint --ext .js,.jsx,.ts,.tsx --max-warnings 0 .
Oops! Something went wrong! :(
ESLint: 8.34.0
Error: Cannot find module 'node:fs'
Require stack:
- /builds/abc/node_modules/synckit/lib/index.cjs
- /builds/abc/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
- /builds/abc/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Occurred while linting /builds/abc/.eslintrc.js:1
```

**Comment by JounQin** [comment]
I don't quite understand

https://2ality.com/2021/12/node-protocol-imports.html#support-for-node%3A-imports

**Comment by JounQin** [comment]
Close due to no response.
