### ISSUE TITLE
useTabs oddity...

### ISSUE THREAD

**Issue by jsg2021** [prettier/eslint-plugin-prettier#63]
I installed this plugin to play with prettier, and set the useTabs true and ran a fix... my file was indented with tabs (expected) but the prettier rule shows errors to replace tabs with spaces...

**Comment by not-an-aardvark** [comment]
Could you paste the errors that get output by ESLint when your file contains tabs?

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided. If this is still a problem, please create a new issue and fill out the new [issue template](https://raw.githubusercontent.com/prettier/eslint-plugin-prettier/master/.github/ISSUE_TEMPLATE.md).
