### ISSUE TITLE
Setting "trailingComma" to "all" does not work

### ISSUE THREAD

**Issue by hegotit** [prettier/eslint-plugin-prettier#632]
**What version of `eslint` are you using?**
8.56.0

**What version of `prettier` are you using?**
3.1.1

**What version of `eslint-plugin-prettier` are you using?**
5.1.2

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
.prettierrc:

```
{
    "semi": true,
    "trailingComma": "all",
    "singleQuote": false,
    "printWidth": 120,
    "tabWidth": 4,
    "endOfLine": "lf"
}
```

.eslintrc file:

```
{
    "ignorePatterns": ["node_modules/", "dist/"],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": ["@typescript-eslint"],
    "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:prettier/recommended"],
    "rules": {
        "prettier/prettier": [
            "error",
            {},
            {
                "usePrettierrc": true
            }
        ],
        "@typescript-eslint/no-explicit-any": ["off"],
        "@typescript-eslint/no-unused-vars": ["off"]
    },
    "env": {
        "browser": true,
        "node": true
    }
}
```

**What source code are you linting?**
.ts files

**What did you expect to happen?**
Stop to hint `ESLint: Insert `,`(prettier/prettier)` when missing a trailing comma with "trailingComma" set to "all". In contrast, when I set it to "es5"/"none", it is able to force/disallow to add a trailing comma.

**What actually happened?**
It keeps hinting `ESLint: Insert `,`(prettier/prettier)` when missing a trailing comma, like below:

![image](https://github.com/prettier/eslint-plugin-prettier/assets/153287866/0235ce61-fc2c-4e1f-aa05-5eb46573ae10)

**Comment by JounQin** [comment]
1. reproduction required
2. Did you reload VSCode after setuping the eslint config?

**Comment by hegotit** [comment]
> 1. Online reproduction required
> 2. Did you reload VSCode after setuping the eslint config?

Not with VSCode but WebStorm 2023.3.2 on Windows-64, I did reload and restart for times but failed to get it work, and you may check this out to confirm the demo file getAxiosInstance.ts to see if the situaction could be reproduced:
https://github.com/hegotit/twitter-downloader.git

**Comment by JounQin** [comment]
This is just how `trailingComma: all` works in `prettier`? I don't understand what are you expecting.

**Comment by hegotit** [comment]
> This is just how `trailingComma: all` works in `prettier`? I don't understand what are you expecting.

Sorry for my misunderstanding that "all" does not refer to supporting both "es5" and "none" but to forcing to add a trailing comma wherever possible.
