### ISSUE TITLE
Removal of eslint-config-prettier from peerDependencies

### ISSUE THREAD

**Issue by dev-boku** [prettier/eslint-plugin-prettier#639]
Since formatting rules in ESLint have been deprecated, it appears that including `eslint-config-prettier` in `peerDependencies` is no longer necessary.

I believe it might be acceptable to remove this from `peerDependencies`, but I am curious about the opinions of others on this matter.

**Comment by JounQin** [comment]
See https://github.com/prettier/eslint-plugin-prettier/pull/592#discussion_r1372774972
