### ISSUE TITLE
Possible to enable for fix only?

### ISSUE THREAD

**Issue by aaronjensen** [prettier/eslint-plugin-prettier#64]
Is it possible to enable this only during a `--fix` and not during a regular run (like in an editor?)

I'd rather not have the noise of auto-fixable errors showing up in my editor since they'd be fixed when I save any way.

Thanks!

**Comment by aaronjensen** [comment]
related: https://github.com/eslint/eslint/issues/8949

**Comment by not-an-aardvark** [comment]
This would depend on the editor integration that you're using. From the command-line, you could turn this off for any given run by adding the `'--rule=prettier/prettier:off'` flag.

**Comment by aaronjensen** [comment]
Thanks, that's helpful.
