### ISSUE TITLE
eslint-plugin-prettier version `3.1.1` and newest prettier version `3.2.5` mismatch causing issues

### ISSUE THREAD

**Issue by marcinskrzynski-knowde** [prettier/eslint-plugin-prettier#644]
**What version of `eslint` are you using?**
8.56.0

**What version of `prettier` are you using?**
3.2.5

**What version of `eslint-plugin-prettier` are you using?**
5.1.3

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**What source code are you linting?**

```
<Comp
  prop={value}
  propThatCausingIssue={object.multiple.nestedAndPrettyLongOne?.find(
    (value) => value.key?.startsWith('string'),
  )}
/>
```

issue:

```
./src/component
130:79  Error: Insert `(value)·=>`  prettier/prettier
131:16  Error: Delete `·(value)·=>`  prettier/prettier
```

**What did you expect to happen?**

Eslint is okay with formatting by prettier 3.2.5

**What actually happened?**

Latest eslint-plugin-prettier package is using prettier `prettier": "^3.1.1"` but the newest version is `3.2.5`. When you prettify your code using `3.2.5.` in some cases (it's single case for me) eslint will report that code as missing prettier formatting.

**Comment by JounQin** [comment]
https://github.com/prettier/eslint-plugin-prettier/blob/248cd17f818b5f09a9519576c1e02b9ef26c64d6/package.json#L55

It's peer dependency. Check your lock file to make sure there is only one prettier installed, and remove related `.eslintcache`.

If you still have problems, please provide a runnable reproduction.

**Comment by fantasy525** [comment]
<img width="689" alt="image" src="https://github.com/prettier/eslint-plugin-prettier/assets/22516157/ed61a3dc-f0ee-4f7e-8ec9-814e6d54ba65">

<img width="433" alt="image" src="https://github.com/prettier/eslint-plugin-prettier/assets/22516157/9669c1f6-4c5d-4977-bf0d-d9462bf04d36">

The first error prompted me to insert a semicolon and a newline, but when I fixed it with the first error, it prompted me to remove the newline
