### ISSUE TITLE
cause endless eslint running

### ISSUE THREAD

**Issue by ichenhe** [prettier/eslint-plugin-prettier#660]
**What version of `eslint` are you using?**

`v8.57.0`

**What version of `prettier` are you using?**

`3.2.5`

**What version of `eslint-plugin-prettier` are you using?**

`5.1.3`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```js
// eslint.config.js

import pluginVue from 'eslint-plugin-vue'
import vueEslintParser from 'vue-eslint-parser'
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended'

export default [
  ...pluginVue.configs['flat/recommended'],
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      parser: vueEslintParser,
      parserOptions: {
        parser: '@typescript-eslint/parser',
        sourceType: 'module',
      },
    },
    files: ['src/**/*.vue', 'src/**/*.js', 'src/**/*.ts'],
    rules: {
      'prettier/prettier': 'warn',
      'vue/attribute-hyphenation': [
        'warn',
        'always',
        {
          ignore: [],
        },
      ],
      'vue/v-on-event-hyphenation': [
        'warn',
        'never',
        {
          autofix: true,
          ignore: [],
        },
      ],
    },
  },
]

```

**What source code are you linting?**

Vue3 + ts

**What did you expect to happen?**

The eslint report the result.

**What actually happened?**

Endless running, over 18 minutes with 100% cpu usage. The problem is solved once remove `eslintPluginPrettierRecommended`.

**Comment by JounQin** [comment]
Please provide runnable reproduction.

**Comment by ichenhe** [comment]
While preparing the reproducible example, I find the key. Deleting `dist` (the output dir of vue build) dir solve the problem. However, this is also strange. Because `dist` is not in eslint's target directorys.


Here's a runnable reproduction:

[example.zip](https://github.com/prettier/eslint-plugin-prettier/files/15431302/example.zip)

```bash
yarn install
yarn build
yarn lint
# or eslint ./
```

**Comment by JounQin** [comment]
It mostly like that you didn't ignore `dist` from linting correctly.

**Comment by ichenhe** [comment]
yes. I add `dist` to `.prettierignore` to fix the issue. I thought just configure the scope of eslint and the plugin would make prettier follow the same rules. Seems that it is not the case.

Thank you for the reply
