### ISSUE TITLE
How to exclude a certain plugin in the .prettierrc configuration from the rules, I don't want eslint to report errors, I just want to format the

### ISSUE THREAD

**Issue by xiongzh120** [prettier/eslint-plugin-prettier#681]
//.prettierrc

```
module.exports = {
  printWidth: 130,
  useTabs: false,
  semi: true,
  singleQuote: false,
  quoteProps: "as-needed",
  jsxSingleQuote: false,
  trailingComma: "none",
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "avoid",
  requirePragma: false,
  insertPragma: false,
  proseWrap: "preserve",
  htmlWhitespaceSensitivity: "css",
  vueIndentScriptAndStyle: false,
  rangeStart: 0,
  rangeEnd: Infinity,
  organizeImportsSkipDestructiveCodeActions: true,
  plugins: ["prettier-plugin-organize-imports"]
};
```

//.eslintrc

    module.exports = {
      root: true,
      env: {
        browser: true,
        node: true,
        es6: true
      },
      parser: "vue-eslint-parser",
      parserOptions: {
        parser: "@typescript-eslint/parser",
        ecmaVersion: 2020,
        sourceType: "module",
        jsxPragma: "React",
        ecmaFeatures: {
          jsx: true
        }
      },
      extends: ["plugin:vue/vue3-recommended", "plugin:@typescript-eslint/recommended", "plugin:prettier/recommended"],
    
      rules: {
        // eslint (http://eslint.cn/docs/rules)
        "no-var": "error",
        "no-multiple-empty-lines": ["error", { max: 1 }],
        "prefer-const": "off",
        "no-use-before-define": "off",
    // typeScript (https://typescript-eslint.io/rules)
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/no-empty-function": "error",
    "@typescript-eslint/prefer-ts-expect-error": "error",
    "@typescript-eslint/ban-ts-comment": "error",
    "@typescript-eslint/no-inferrable-types": "off",
    "@typescript-eslint/no-namespace": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    
    // vue (https://eslint.vuejs.org/rules)
    "vue/v-slot-style": "error",
    "vue/no-mutating-props": "error",
    "vue/custom-event-name-casing": "error",
    "vue/html-closing-bracket-newline": "error",
    "vue/attribute-hyphenation": "error",
    "vue/attributes-order": "off",
    "vue/no-v-html": "off",
    "vue/require-default-prop": "off",
    "vue/multi-word-component-names": "off",
    "vue/no-setup-props-destructure": "off"
     }
    };

For example, I don't want eslint to detect "prettier-plugin-organize-imports"

**Comment by xiongzh120** [comment]
"prettier/prettier": ["off", { plugins: ["prettier-plugin-organize-imports"] }] Is that so?

**Comment by BPScott** [comment]
Prettier does not distinguish between changes because of core opinions and that of a plugin. `eslint-plugin-prettier` just runs `prettier`. it can not an does not try to do anything clever with the results that prettier gives it.

It sounds like you don't want eslint-plugin-prettier, and you'd be better off with running eslint and prettier as two distinct commands.
