### ISSUE TITLE
`plugin:prettier/recommended` doesn't include `prettier/react`

### ISSUE THREAD

**Issue by IanEdington** [prettier/eslint-plugin-prettier#77]
The `plugin:prettier/recommended` doesn't seem to include the `prettier/react` component. Is this my design or by mistake?

I would expect `plugin:prettier/recommended` to take care of all the rule removal that it could possibly want to change.

"eslint": "^4.0.0",
"prettier": "^1.9.2",
"eslint-plugin-prettier": "^2.4.0",

`.eslintrc`
```
{
  "parser": "babel-eslint",
  "extends": [
    "eslint-config-airbnb",
    "plugin:prettier/recommended"
  ]
}
```

**What source code are you linting?**

    const userMenuItems = []
      .concat(
        user ? (
          <UserDetails
            key="userDetails"
            email={user.email_address}
            name={`${user.first_name} ${user.last_name}`}
          />
        ) : null,
        <HorizontalLine key="hr1" />
      );

The react indent rule seems to conflict with prettier and isn't being taken out by the recommended configs.

When 6 spaces:
`      <HorizontalLine key="hr1" />`
Insert `··`  prettier/prettier

When 8 spaces:
`        <HorizontalLine key="hr1" />`
Expected indentation of 6 space characters but found 8  react/jsx-indent

**Comment by not-an-aardvark** [comment]
Thanks for the report. The stylistic rules in `prettier:recommended` come from [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) -- I would recommend filing an issue there instead.
