### ISSUE TITLE
ESLint as peerDependency

### ISSUE THREAD

**Issue by zimme** [prettier/eslint-plugin-prettier#80]
As this is an eslint plugin, shouldn't it have `eslint` as a peer dependency?

A project needs to have `eslint` installed to be able to use this plugin.

**Comment by not-an-aardvark** [comment]
This plugin originally had `eslint` as a peer dependency, but we removed it in https://github.com/prettier/eslint-plugin-prettier/commit/1666067aa396dfe6a622eb1d9fd5d21fa851a612 because it exposes an additional API for use by other libraries, which might not be related to ESLint.

**Comment by zimme** [comment]
Aaah, prettylint 😄

**Comment by offero** [comment]
`npm WARN eslint-plugin-prettier@3.1.0 requires a peer of eslint@>= 5.0.0 but none is installed. You must install peer dependencies yourself.`

?
