### ISSUE TITLE
support multi error level ?

### ISSUE THREAD

**Issue by lili21** [prettier/eslint-plugin-prettier#87]
looks like it only support single error level for all prettier options.

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. Could you please provide more details about what you're trying to do? I don't understand what the suggestion is.

**Comment by lili21** [comment]
my bad.

```js
'prettier/prettier': ['error', {
      singleQuote: true,
      semi: true,
      trailingComma: 'all'
    }],
```

I don't want missing trailingComma to be an **error**. **warning** would be enough.

**Comment by not-an-aardvark** [comment]
Thanks for clarifying. This is a limitation of how ESLint rules work -- it's only possible to have a single error level for a given rule.
