### ISSUE TITLE
ignore no-inline-comments rule

### ISSUE THREAD

**Issue by osmanov** [prettier/eslint-plugin-prettier#93]
This is an awesome project,thank you very much for a such good work!
I spent the all day for resolving this issue,but I couldn't fix it=(
 
**What version of `eslint` are you using?**
^4.18.2
**What version of `prettier` are you using?**
^1.13.3
**What version of `eslint-plugin-prettier` are you using?**
^2.6.0
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
//.eslintrc.json
"parser":"babel-eslint",
"rules":{
 "no-inline-comments":0
},
 "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:prettier/recommended"
    ]
```
**What source code are you linting?**
```js
class User{
  constructor(options){ //this is a comment about constructor
   
 }
}
```

**What did you expect to happen?**
```js
class User{
  constructor(options){ //this is a comment about constructor
   ...code
 }
}
```
**What actually happened?**
after `eslint --fix` i have:
```js
class User{
  constructor(options){
    //this is a comment about constructor
   ...code
 }
}
```

Thanks

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

Could you paste the output that appears when you run `eslint` without the `--fix` flag? It's possible that the fix which moves the comment isn't coming from the `no-inlime-comments` rule.

**Comment by osmanov** [comment]
this is a output:
![image](https://user-images.githubusercontent.com/3253158/40929110-0f7f7fb2-6824-11e8-88fb-ec7c837db4ea.png)

**Comment by not-an-aardvark** [comment]
It looks like the error isn't coming from the `no-inline-comments` rule, but from `eslint-plugin-prettier` itself. I think this is simply a case where `prettier` is changing how your code is formatted. If you think it should be formatting your code a different way, I would recommend filing an issue on the [`prettier/prettier`](https://github.com/prettier/prettier) repository instead.
