### ISSUE TITLE
prettier not fixing vue/max-attributes-per-line

### ISSUE THREAD

**Issue by mike-rotate** [prettier/eslint-plugin-prettier#94]
**What version of `eslint` are you using?**
`"^4.15.0"`

**What version of `prettier` are you using?**
`VS Code plugin for prettier/prettier - 1.4.0`

**What version of `eslint-plugin-prettier` are you using?**
`"^2.6.0"`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```JS
/* .eslintrc */
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'eslint:recommended',
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/strongly-recommended'
  ],
  // required to lint *.vue files
  plugins: [
    'prettier',
    'vue'
  ],
  // add your custom rules here
  rules: {}
}
```

**What source code are you linting?**
```HTML
      <!-- example.vue -->
      <div class="Cart__top">
        <button class="Cart__close  t-h5" type="button" @click="closeCart">Close</button>
        <div class="Cart__subtotal">
          <div class="Cart__subtotalTitle  t-h5">Subtotal</div>
          <div class="Cart__subtotalPrice  t-h1">€150</div>
        </div>
      </div>
```

**What did you expect to happen?**
Output after executing `format document` command in vs code, line 3 would be formatted such that each attribute on the button element would be on a new line.  I could be making a wrong assumption that my vs code prettier extension would make use of these settings, that prettier would ever do this, or that this is even the right place to post this??

**What actually happened?**
No formatting of the attributes occurred.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

I noticed you haven't enabled any rules from `prettier` in your config file. What happens if you add `"plugin:prettier/recommended"` to your `extends` array in your config?

**Comment by mike-rotate** [comment]
I had previously tried that too, i still get the same result.

**Comment by jjohnson1994** [comment]
Also getting this issue.

**What version of eslint are you using?**
"^4.19.1"

**What version of prettier are you using?**
VS Code plugin for prettier/prettier - 1.5.0

**What version of eslint-plugin-prettier are you using?**
"^2.6.0"

**Please paste any applicable config files that you're using (e.g. .prettierrc or .eslintrc files)**
.eslintrc
```{
  "env": {
    "es6": true
  },
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "extends": [
    "plugin:vue/recommended",
    "plugin:prettier/recommended",
    "eslint:recommended"
  ],
  "globals": {
    "_": true,
    "moment": true,
    "$toast": true,
    "firebase": true,
    "module": true,
    "swal": true,
    "atatus": true,
    "Tawk_API": true,
    "Stripe": true
  },
  "rules": {
    "array-bracket-spacing": [2, "never"],
    "no-var": 2,
    "block-scoped-var": 2,
    "brace-style": [2, "1tbs"],
    "camelcase": 1,
    "computed-property-spacing": [2, "never"],
    "curly": 2,
    "eol-last": 2,
    "eqeqeq": [2, "smart"],
    "indent": ["error", 2, {
      "SwitchCase": 1,
      "MemberExpression": 1
    }],
    "max-depth": [1, 3],
    "max-len": [1, 300],
    "max-statements": [1, 45],
    "new-cap": 1,
    "no-extend-native": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-trailing-spaces": 2,
    "no-unused-vars": 2,
    "object-curly-spacing": [2, "always"],
    "quotes": [2, "single", "avoid-escape"],
    "semi": [2, "always"],
    "arrow-spacing": [2, {"before": true, "after": true}],
    "keyword-spacing": [2, {"before": true, "after": true}],
    "space-unary-ops": 2,
    "comma-dangle": ["error", "always-multiline"],
    "prefer-arrow-callback": 2,
    "vue/html-quotes": "single",
    "vue/max-attributes-per-line": [2, {
      "singleline": 1,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }]
  }
}
```
.prettierrc
```
{
  "printWidth": 300,
  "singleQuote" : true,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "arrowParens": "avoid"
}
```

Anyone got any ideas?

**Comment by not-an-aardvark** [comment]
To fix this issue, you should disable the `vue/max-attributes-per-line` rule since it seems like it conflicts with how `prettier` attempts to style your code.

**Comment by diazemiliano** [comment]
Thanks @dsegovia90 !

**Comment by Jewcub** [comment]
I'd prefer to cancel prettier's rule and keep multiline attributes, I think they are more readable. Has anyone done that successfully?

**Comment by BPScott** [comment]
@Jewcub in that case you probably want to use [prettier-eslint](https://github.com/prettier/prettier-eslint) which will run code through prettier then run eslint on it, so you know the eslint rules will take precedence.

**Comment by Valar103769** [comment]
> I'd prefer to cancel prettier's rule and keep multiline attributes, I think they are more readable. Has anyone done that successfully? Also this is what Vue style guide recommends.

 same as you , 
[prettier-eslint](https://github.com/prettier/prettier-eslint) is only resolve js problem, but, for vue 
 template, its invalid,

**Comment by Tinoooo** [comment]
Was anybody able to fix this? I'm struggeling with this problem, too. 🙁

**Comment by braivre** [comment]
Same problem here. I need to disable prettier to make max-attributes-per-line working but obviously it's a shame.

```
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    "plugin:vue/essential",
    "eslint:recommended",
    "@vue/typescript/recommended",
    // "@vue/prettier",
    "@vue/prettier/@typescript-eslint",
  ],
  parserOptions: {
    ecmaVersion: 2020
  },
  rules: {
    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
    // "prettier/prettier": [
    //   'warn',
    //   {
    //     "tabWidth": 4,
    //     "semi": false,
    //     "trailingComma": "all",
    //   }
    // ],
    "vue/max-attributes-per-line": ["warn", {
      "singleline": 1,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }]
  }
};
```

**Comment by hansiemithun** [comment]
Disabling prettier for Vue project, tired researching on the fix..

**Comment by Tinoooo** [comment]
Can somebody maybe reopen this issue. It seems like the problem still exists.

**Comment by engineertdog** [comment]
+1, disabling prettier because it doesn't mesh with `vue/max-attributes-per-line` is quite annoying.

**Comment by braivre** [comment]
I made it work installing this plugin:

https://github.com/meteorlxy/eslint-plugin-prettier-vue

And ignoring template tag to avoid collisions. Here is an example of my .eslintrc.js:

```
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    // "plugin:vue/essential",
    "plugin:vue/strongly-recommended",
    "eslint:recommended",
    "plugin:prettier-vue/recommended",
    "@vue/typescript/recommended",
    // "@vue/prettier",
    "@vue/prettier/@typescript-eslint",
  ],
  parserOptions: {
    ecmaVersion: 2020
  },
  settings: {
      'prettier-vue': {
        // ignoring template tag
        SFCBlocks: {
          template: false
        }
      }
  },
  rules: {
    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
    "prettier-vue/prettier": [
      "warn",
      {
        "semi": false,
        "trailingComma": "all",
        "useTabs": true,
        "tabWidth": 2,
      }
    ],
    "vue/max-attributes-per-line": ["warn", {
      "singleline": 1,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }],
    "vue/html-indent": ["error", "tab", {
      "baseIndent": 1,
    }]
  }
}
```
But I think the goal here is that it should work out of the box without installing plugins.

**Comment by gszsilva** [comment]
I know this thread is closed, but in case someone bump into this problem again, here's a fix that worked for me.
I tested removing some lines from my .prettierc and found out that the following one was conflicting with the eslint rule:

`"useTabs": true`

Just removed and it worked for me.

**Comment by Jikodis** [comment]
So, if no-one else has figured it out by now, I am not going to waste any more time with it than I already have. This line was provided in the eslintrc.js file in the Nuxt documentation: https://nuxtjs.org/guide/development-tools/#eslint-and-prettier I used it and those 100s of errors went away.

```
// add your custom rules here
  rules: {
    'vue/max-attributes-per-line': 'off',
  }
```

**Comment by Tinoooo** [comment]
@Jikodis I'm in the exact same situation as you are. Maybe https://github.com/prettier/prettier/issues/5501 will help.

**Comment by felloz** [comment]
Same problem and I don't have eslint installed.

**Comment by silencerspirit** [comment]
`eslint-config-prettier` `eslint-plugin-prettier` `prettier`

and option `singleAttributePerLine` solved this issue

```Javascript
'prettier/prettier': [
      'error',
      {
        singleAttributePerLine: true,
      },
    ],
```

**Comment by mahmoudsaeed** [comment]
It's important to note that using a linter such as ESLint for stylistic (formatting) rules is [not recommended](https://prettier.io/docs/en/comparison) when used in conjunction with Prettier. This is the primary motivation behind the `eslint-config-prettier` [package](https://github.com/prettier/eslint-config-prettier), which turns off all rules that are unnecessary or might conflict with Prettier.

The optimal resolution is to either remove or turn off the `vue/max-attributes-per-line` rule in your ESLint configuration and allow Prettier to handle it instead.

> In other words, use **Prettier for formatting and linters for catching bugs!**

**Comment by sachinkmohan** [comment]
`"vue/max-attributes-per-line": "off",`

I turned this off in rules and have one less headache. Somehow prettier does opposite to what eslint wants to do here.

**Comment by doox911** [comment]
https://prettier.io/docs/en/options.html#single-attribute-per-line

I think it's a good compromise
